#!/bin/sh
case "$1" in
save)
	/etc/scripts/dbsave.sh
	;;
freset)
	devconf del
	;;
isfreset)
	SIZE=`devconf dump | scut -p "Data size :" -f 1`
	if [ "$SIZE" = "0" ]; then
		echo "YES"
	else
		echo "NO"
	fi
	;;
init)
	if [ $# -ne 8 ]; then
		echo "Usage:"
		echo "  mfc init <lanmac> <wlan24mac> <wanmac> <countrycode> <hw version> <deviceip> <pin>"
		exit 1
	fi
	LANMAC=`echo -e $2 | tr [A-Z] [a-z]`
	WLAN24MAC=`echo -e $3 | tr [A-Z] [a-z]`
	WANMAC=`echo -e $4 | tr [A-Z] [a-z]`
	CCODE="$5"
	HWVER="$6"
	IP="$7"
	PIN="$8"
	[ "$LANMAC" != "" ] && DEVDATA="$DEVDATA -e lanmac=$LANMAC -e wlan24mac=$WLAN24MAC"
	[ "$WANMAC" != "" ] && DEVDATA="$DEVDATA -e wanmac=$WANMAC"
	[ "$CCODE" = "" ] && CCODE="US"
	[ "$HWVER" != "" ] && DEVDATA="$DEVDATA -e hwver=$HWVER"
	[ "$PIN" != "" ] && DEVDATA="$DEVDATA -e pin=$PIN"
	echo "devdata set -e countrycode=$CCODE $DEVDATA -f" > /dev/console
	devdata set -e countrycode=$CCODE $DEVDATA -f
	# Save wireless MAC address to EEPROM
	M1=`echo $LANMAC | cut -d: -f1`
	M2=`echo $LANMAC | cut -d: -f2`
	M3=`echo $LANMAC | cut -d: -f3`
	M4=`echo $LANMAC | cut -d: -f4`
	M5=`echo $LANMAC | cut -d: -f5`
	M6=`echo $LANMAC | cut -d: -f6`
	iwpriv ra0 e2p 04=$M2$M1
	iwpriv ra0 e2p 06=$M4$M3
	iwpriv ra0 e2p 08=$M6$M5
	
	# Set MAC Address and IP Address into u-boot config.
	[ "$LANMAC" != "" ] && UBCFG="$UBCFG ethaddr=$LANMAC"
	[ "$IP" != "" ] && UBCFG="$UBCFG ipaddr=$IP"
	echo "ubcfg set $UBCFG" > /dev/console
	ubcfg set $UBCFG
	# Show devdata and uboot data
	echo "-------- devdata dump ----------------------" > /var/mfcdump
	devdata dump >> /var/mfcdump
	echo "-------- ubcfg get ethaddr ipaddr-----------" >> /var/mfcdump
	ubcfg get ethaddr ipaddr >> /var/mfcdump
	echo "--------------------------------------------" >> /var/mfcdump
	cat /var/mfcdump
	rm /var/mfcdump
	;;
evm)
	if [ $# -ne 11 ]; then
		echo "Usage:"
		echo "  mfc evm <INF> <ATETXFREQOFFSET> <ATETXMODE> <ATETXMCS> <ATETXBW> <ATETXLEN> <ATECHANNEL> <ATETXANT> <ATETXPOW0> <ATETXPOW1>"
		exit 1
	fi
	INF=$2

	iwpriv $INF set ATE=ATESTART
	iwpriv $INF set ATEDA=FF:FF:FF:FF:FF:FF
	iwpriv $INF set ATETXGI=0
	iwpriv $INF set ATETXLEN=$7
	iwpriv $INF set ATETXCNT=1000000
	iwpriv $INF set ATETXANT=$9
	iwpriv $INF set ATECHANNEL=$8
	iwpriv $INF set ATETXMODE=$4
	iwpriv $INF set ATETXMCS=$5
	iwpriv $INF set ATETXBW=$6
	iwpriv $INF set ATETXPOW0=${10}
	iwpriv $INF set ATETXPOW1=${11}
	iwpriv $INF set ATETXFREQOFFSET=$3
	iwpriv $INF set ATEIPG=200	
	iwpriv $INF set ATE=TXFRAME
	;;
wlan)
	DATPATH="/var/run/RT2860.dat"
	cp /etc/scripts/mfc/RT3092.dat $DATPATH
	echo "" >> $DATPATH
	case "$2" in
	"5g")
		echo "CountryRegionABand=7" >> $DATPATH
		echo "WirelessMode=8" >> $DATPATH
		;;
	"2g")
		echo "CountryRegion=0" >> $DATPATH
		echo "WirelessMode=9" >> $DATPATH
		;;
	esac
	case "$5" in
	"HT20")
		echo "HT_BW=0" >> $DATPATH
		;;
	"HT40")
		echo "HT_BW=1" >> $DATPATH
		echo "HT_EXTCHA=1" >> $DATPATH
		;;
	esac
	echo "Channel=$4" >> $DATPATH
	echo "SSID=$3" >> $DATPATH
	killall hostapd
	ifconfig ra0 down
	brctl delif br0 ra0
	ifconfig ra0 txqueuelen 1000
	ifconfig ra0 up
	brctl addif br0 ra0
	brctl setbwctrl br0 ra0 900
	echo 1 > /proc/net/br_forward_br0
	;;
dump)
	devdata dump
	;;
dumpv2)
	# Show devdata and uboot data
	echo "-------- Firmware Version-------------------" > /var/mfcdump
	echo FW_Ver=`cat /etc/config/buildver``cat /etc/config/buildrev` Build `cat /etc/config/buildno` >> /var/mfcdump
	echo "-------- devdata dump ----------------------" >> /var/mfcdump
	devdata dump >> /var/mfcdump
	echo "-------- ubcfg get ethaddr ipaddr-----------" >> /var/mfcdump
	ubcfg get ethaddr ipaddr >> /var/mfcdump
	echo "--------------------------------------------" >> /var/mfcdump
	cat /var/mfcdump
	rm /var/mfcdump
	;;
ver)
	echo Ver `cat /etc/config/buildver``cat /etc/config/buildrev` Build `cat /etc/config/buildno`
	;;
get)
	[ "$2" != "" ] && devdata get -e $2
	;;
set)
	[ "$2" != "" ] && devdata set -e $2
	;;
test)
	case $2 in
	on)
		usockc /var/gpio_ctrl DEBUG
		;;
	off)
		usockc /var/gpio_ctrl NODEBUG
		;;
	esac
	;;
layout)
	case $2 in
	router)
		rtlioc routermode
		rtlioc enlan
		;;
	bridge)
		rtlioc bridgemode
		;;
	esac
	;;
button)
	case $2 in
	reset)
		usockc /var/gpio_ctrl GPIO_FRESET
		cat /var/gpio_ctrl_result
		;;
	wps)
		usockc /var/gpio_ctrl GPIO_WPSPBC
		cat /var/gpio_ctrl_result
		;;
	esac
	;;
led)
	case "$2" in
	wps_blue)
		usockc /var/gpio_ctrl WPS_BLUE
		;;
	wan)
		usockc /var/gpio_ctrl INET_ON
		;;
	esac
	;;
sa_cn_test)
	if [ $# -ne 3 ]; then
		echo "Usage:"
		echo "  mfc sa_cn_test pin1 pin2 "
		echo "  pin avalid 1-6"
		exit 1
	fi
	gpiod sa_cn_test $2 $3
	;;
*)
	echo "Usage: mfc {command} <params>"
	echo "Commands:"
	echo "  init <lanmac> <wlan24mac> <wanmac> <countrycode> <hw version> <bootip> <pin>"
	echo "                           Init flash"
	echo "                           *bootip: Set boot loader IP not device IP."
	echo ""
	echo "  save                     Save current setting to flash"
	echo ""
	echo "  evm <INF> <ATETXFREQOFFSET> <ATETXMODE> <ATETXMCS> <ATETXBW> <ATETXLEN>"
	echo "       <ATECHANNEL> <ATETXANT> <ATETXPOW0> <ATETXPOW1>"
	echo "                           save ATE wireless parameters for 5GHz or 2.4GHz band"
	echo ""
	echo "  wlan 2g <ssid> <channel> <bandwidth>"
	echo "                           Config the wireless setting for testing."
	echo "                           Where the 'bandwidth' should be the value of 'HT20' or 'HT40'."
	echo "  dump                     Dump environment vairables."
	echo "  dumpv2                   Dump environment vairables."
	echo "  ver                      Show firmware version"
	echo ""
	echo "  get <name>               Get current WAN mac address"
	echo "  freset                   Factory reset"
	echo "  isfreset                 Check if the device is reset to factory default."
	echo ""
	echo "  test on                  turn on test mode"
	echo "  test off                 turn off test mode"
	echo ""
	echo "  layout bridge            switch the ethernet ports to bridge layout."
	echo "  layout router            switch the ethernet ports to router layout."
	echo "  button {reset|wps}"
	echo "      reset                Get factory reset button status."
	echo "      wps                  Get WPS button status."
	echo ""
	echo "  led {wps_blue|wan}"
	echo "  sa_cn_test pin1 pin2	test pin1<-->pin2 loobback"
	;;
esac
