//Portuguese
//保留這一行
helppage=new Array(
 "Isto exibe o endereço MAC da interface WAN, bem como o endereço IP, a Máscara de Sub-rede, a Gateway Predefinida e a informação do servidor DNS que o dispositivo obteve do seu ISP. Exibirá também o tipo de ligação (Dinâmico, Estático, ou PPPoE) que é utilizado para estabelecer uma ligação ao seu ISP. "
,"Se o router estiver configurado para Dinâmico, existirão botões para a libertação e renovação do Endereço IP atribuído à interface WAN. Se o router estiver configurado para PPPoE, existirão botões para ligar e desligar a sessão PPPoE."
,"Isto exibe o Nome do Sistema, Tempo de disponibilidade do Sistema, Versão HW e Versão SW."
,"Isto exibe o SSID, o Canal, Total de Clientes e se a Encriptação está ou não ativada na interface Sem Fios."
,"Isto exibe a máscara de sub-rede da interface LAN e o agrupamento do servidor DHCP."
,"Siga a definição do Serviço WAN, mas ative a ligação apenas quando a WAN estiver offline e desative a ligação quando a WAN estiver online."
,"IPv6"
,"A secção IPv6 (Protocolo de Internet versão 6) é onde se configura o tipo de Ligação IPv6."
,"Tipo de Ligação IPv6"
,"Existem vários tipos de ligação que pode escolher: Ligação local, IPv6 Estático, Configuração automática e PPPoE. Se não tiver a certeza do seu método de ligação, contacte o seu Fornecedor de Serviços de Internet IPv6."
,"Nota: Se estiver a utilizar a opção PPPoE, terá de assegurar de que qualquer cliente de software ou hardware PPPoE nos seus computadores foi removido ou desativado."
,"Modo de ligação local"
,"Utiliza-se o endereço da ligação local por nós e routers para comunicar com os nós vizinhos na mesma ligação. Este modo ativa dispositivos IPv6 para comunicarem entre si no lado LAN."
,"Modo de IPv6 Estático"
,"Este modo é utilizado quando o seu ISP lhe fornecer um conjunto de endereços IPv6 que não alteram. A informação IPv6 é introduzida manualmente nas definições de configuração IPv6. Tem de introduzir o endereço IPv6, o Comprimento do Prefixo de Sub-rede, a Gateway Predefinida, o Servidor de DNS Preferido e o Servidor de DNS Alternativo. "
,"O seu ISP fornece-lhe todas estas informações."
,"PPPoE"
,"Selecione esta opção se o seu ISP necessitar da utilização de uma ligação PPPoE (protocolo Ponto-a-ponto sobre Ethernet) à Internet IPv6. Os fornecedores de DSL utilizam normalmente esta opção. "
,"Este método de ligação requer que introduza um Nome de Utilizador e uma Palavra-passe (fornecidos pelo Fornecedor de Serviços Internet) para obter acesso à Internet IPv6. Os protocolos de autenticação suportados são PAP e CHAP."
,"DEFINIÇÕES DO ENDEREÇO IPv6 LAN"
,"Essas são as configurações da interface IPv6 LAN (Rede de Área Local) para o router. A configuração do endereço LAN IPv6 do router é baseada no endereço IPv6 e sub-rede atribuídos pelo seu ISP. (Uma sub-rede com prefixo / 64 é suportada em LAN.)"
,"Definições de Configuração Automática de Endereço LAN"
,"Utilize esta secção para configurar a Configuração Automática IPv6 para atribuir um endereço IPv6 aos computadores na sua rede local. Fornecem-se métodos de Configuração Automática Classificada e Sem Estado."
,"A informação MAC do dispositivo que está ligado ao serviço AP."
,"A página \"Configuração Sem Fios\" contém as definições para a Porção (Ponto de Acesso) do dispositivo. Esta página permite-lhe personalizar sua rede sem fios ou configurar o dispositivo para integrar uma rede sem fios existente que pode ter já configurado."
,"Banda Sem Fios"
,"Mostra a banada do AP atual."
,"Ativar Sem Fios"
,"A configuração para ligar/desligar do serviço sem fios."
,"Nome da sua Rede Sem Fios"
,"Também conhecida como SSID (Service Set Identifier), é o nome da sua Rede de Área Local Sem Fios (WLAN). Pode ser facilmente alterado para estabelecer uma nova rede sem fios ou para adicionar o dispositivo a uma rede sem fios existente."
,"Modo 802.11"
,"Permite ao utilizador alterar o modo suportado. Inclui o modo apenas e o modo misto."
,"Ativar a Pesquisa Automática de Canal"
,"Interruptor ligar/desligar para permitir que o dispositivo pesquise o ambiente antes de iniciar o serviço sem fios."
,"Canal da Ligação sem Fios"
,"Para mostrar o canal atual que o dispositivo está a utilizar e que o utilizador pode alterar quando estiver desativada a opção \"Ativar a Pesquisa Automática de Canal\"."
,"Largura de Canal"
,"O utilizador pode alterar a largura do canal. Os canais mais largos obtêm melhor largura de banda mas pior sensibilidade."
,"Modo de segurança"
,"Proteger a sua rede sem fios é importante porque é utilizada para proteger a integridade das informações transmitidas pela sua rede sem fios. O dispositivo é compatível com 4 tipos de segurança sem fios: WEP, apenas WPA, apenas WPA2 e WPA/WPA2 (deteção automática)."
,"WEP"
,"Wired Equivalent Protocol (WEP) é um protocolo de segurança sem fios para rede de área local sem fios (WLAN). O WEP proporciona segurança encriptando os dados enviados através da WLAN. O dispositivo suporta 2 níveis de Encriptação WEP: 64 bit e 128 bit. O WEP está desativado por defeito. "
,"A definição de WEP pode ser alterada para se ajustar a uma rede sem fios existente ou para personalizar a sua rede sem fios."
,"Autenticação - A autenticação é um processo pelo qual o dispositivo verifica a identidade de um dispositivo de rede que está a tentar juntar-se à rede sem fios. Existem dois tipos de autenticação para este dispositivo quando utilizar WEP."
,"Sistema Aberto - Selecione esta opção para permitir que todos os dispositivos sem fios comuniquem com o dispositivo antes de terem de fornecer a chave de encriptação necessária para acesso à rede."
,"Chave Partilhada - Selecione esta opção para que qualquer dispositivo sem fios que tente comunicar com o dispositivo forneça a chave de encriptação necessária para aceder à rede antes de serem autorizados a comunicar com o dispositivo."
,"Encriptação WEP - Selecione o nível de encriptação WEP que gostaria de utilizar na sua rede. Os dois níveis suportados de encriptação WEP são de 64 bit e 128 bit."
,"Tipo de Chave - Os Tipos de Chave suportados pelo dispositivo são HEX (Hexadecimal) e ASCII (Código Padrão Americano para o Intercâmbio de Informação). O Tipo de Chave pode ser alterado para se ajustar a uma rede sem fios existente ou para personalizar a sua rede sem fios."
,"Chaves - As Chaves permitem-lhe alterar facilmente as definições de encriptação sem fios para manter uma rede segura. Selecione simplesmente a chave específica a utilizar para encriptar os dados sem fios na rede."
,"WPA-Personal"
,"Aceita clientes WPA ou WPA2 apenas e a Chave pré-partilhada (chave de encriptação) deve ser introduzida manualmente. Pode introduzir 8 a 63 caracteres ASCII ou 64 dígitos hexadecimais como Chave pré-partilhada."
,"Tipo de Cifra - O dispositivo suporta dois tipos diferentes de cifras quando se utiliza WPA como Tipo de Segurança. Estas duas opções são TKIP (Protocolo de Integridade de Chave Temporária) e AES (Encriptação Avançada Standard)."
,"Chave Pré-partilhada - É disto que os seus clientes sem fios precisarão para comunicar com o seu dispositivo, quando estiver selecionado PSK. Introduza entre 8 e 63 caracteres alfanuméricos. Certifique-se de que anota a Frase de segurança uma vez que terá de introduzi-la em qualquer dispositivo sem fios que tente adicionar à sua rede."
,"A Configuração Protegida Wi-Fi fornece uma forma mais intuitiva de configurar a segurança sem fios entre o router e o cliente sem fios. Certifique-se de que o cartão sem fios suporta esta funcionalidade ou que utiliza um controlador certificado Windows Vista para poder utilizar esta função."
,"Intervalo de marcação"
,"Os intervalos de marcação são pacotes enviados por um Ponto de Acesso para sincronizar uma rede sem fios. Especifique um valor de Intervalo de marcação entre 20 e 1024."
,"Energia de Transmissão"
,"Selecione a potência de transmissão da antena. O utilizador pode definir o nível de potência para 100%, 50%, 25%,12%."
,"Intervalo DTIM"
,"A DTIM (Delivery Traffic Indication Message - Mensagem de Indicação de Tráfego de Entrega) é uma mensagem de contagem decrescente para o Ponto de Acesso que informa os clientes da janela seguinte para ouvirem mensagens de difusão e multidifusão. "
,"Quando o Ponto de Acesso tiver colocada em memória intermédia mensagens de difusão ou multidifusão para clientes associados, envia a próxima DTIM com um valor de intervalo DTIM. Os clientes AP ouvem os intervalos de marcação e acordam para receber as mensagens de difusão e multidifusão. Introduza um valor entre 1 e 255 para o intervalo DTIM."
,"Suporta WMM"
,"Ativar o WMM pode ajudar a controlar a latência e a instabilidade na transmissão de conteúdo multimédia sobre uma ligação sem fios."
,"Taxas TX"
,"Seleciona as taxas de transmissão dependendo da velocidade da sua rede sem fios. Pode selecionar entre uma amplitude de velocidades de transmissão ou pode selecionar Auto para permitir que o Router selecione automaticamente. A configuração predefinida é Auto."
,"GI Curto"
,"Utilizando um intervalo de protecção curto (400ns) pode aumentar a produtividade. No entanto, pode também aumentar a taxa de erro em algumas instalações, devido a sensibilidade aumentada nos reflexos de radiofrequência. Selecione a opção que funcione melhor para a sua instalação"
,"Coexistência HT 20/40"
,"Ativar ou Desativar a coexistência HT BSS."
,"A lista do dispositivo do cliente DHCP, incluindo Nome do Anfitrião, Endereço IP e Endereço MAC."
,"Estas são as definições da interface LAN (Rede de Área Local) para o dispositivo. Estas definições podem ser referidas como \"definições privadas\". Pode alterar o endereço IP do Router, se necessário. O endereço IP do Router é privado da sua rede interna e não pode ser visto na Internet."
,"Endereço IP do Router"
,"Endereço IP do dispositivo."
,"Máscara de Sub-rede Predefinida"
,"Máscara de Sub-rede do dispositivo."
,"Nome do Domínio Local"
,"Introduza o nome do domínio local para a sua rede. Esta é uma definição opcional."
,"Servidor DHCP"
,"DHCP significa Protocolo de Controlo de Anfitrião Dinâmico. O servidor DHCP atribui endereços IP aos dispositivos na rede que o solicitem. Estes dispositivos devem ser definidos para \"Obter o endereço IP automaticamente\". Por defeito, o servidor DHCP está ativado no dispositivo. "
,"O agrupamento de endereços DHCP contém o intervalo de endereços IP que serão atribuídos automaticamente aos clientes na rede."
,"Ativar Servidor DHCP"
,"O interruptor ligar/desligar controla a função do Servidor DHCP do dispositivo."
,"Intervalo de Endereços IP DHCP"
,"Configuração do endereço IP de início e do endereço IP de fim para a atribuição de IP do servidor DHCP."
,"Tempo de Reserva DHCP"
,"O tempo em minutos para a reserva de IP."
,"Endereço IP do DNS preferido / Endereço IP do DNS alternativo"
,"Estas duas definições são opcionais. O utilizador pode atribuir o servidor DNS que pretende utilizar."
,"O DNS Dinâmico (Serviço de Nome do Domínio) é um método para manter um nome de domínio ligado a um endereço IP que muda (dinâmico). Com a maioria das ligações por Cabo e DSL, é-lhe atribuído um endereço IP dinâmico e esse endereço utiliza-se apenas para a duração dessa ligação específica. "
,"Com o dispositivo, pode configurar o serviço DDNS e o dispositivo irá automaticamente atualizar o servidor DDNS sempre que recebe um novo endereço IP WAN."
,"Endereço do Servidor"
,"Escolha o seu fornecedor DNS Dinâmico no menu pendente."
,"Nome do anfitrião"
,"Introduza o Nome do Anfitrião que registou no seu fornecedor de serviços DDNS."
,"Nome de Utilizador / E-mail"
,"Introduza o nome de utilizador para a sua conta DDNS."
,"Palavra-passe / Chave "
,"Introduza a palavra-passe para a sua conta DDNS."
,"Algumas aplicações necessitam de várias ligações, como os jogos de Internet, conferências de vídeo, comunicações telefónicas via Internet e outros. Devido à função da firewall, estas aplicações não podem funcionar com um router NAT puro. As Aplicações Especiais tornam possível que algumas destas aplicações funcionem com o router NAT."
,"Ativação"
,"O número de porta de saída emitido pela aplicação."
,"Portas de entrada"
,"Quando o pacote de ativação é detetado, é permitida a passagem pela firewall aos pacotes de entrada para os números de porta especificados."
,"Este produto dispõe de algumas definições predefinidas. Selecione a sua aplicação e clique em Copiar para adicionar a definição predefinida à sua lista. Se o mecanismo de Aplicações Especiais não conseguir fazer uma aplicação funcionar, tente o anfitrião DMZ."
,"NOTA: Em qualquer altura, apenas um PC pode utilizar a Aplicação Especial."
,"O computador pode ser configurado como anfitrião DMZ acessível através da Internet, pelo que, entre o anfitrião e a Internet pode ser implementado um número ilimitado de serviços e de transferências de dados. Por exemplo, para jogos na Internet ou teleconferências e outras aplicações especiais."
,"O Servidor Virtual ativa WWW, FTP e outros serviços na sua LAN para estarem acessíveis aos utilizadores da Internet. Consulte os Serviços de Internet para portas conhecidas."
,"O Filtro URL bloqueará o acesso por parte dos computadores da LAN a páginas da Internet predefinidas."
,"Ativar Bloqueio de URL"
,"Marque esta opção se pretende ativar o Bloqueio de URL."
,"URL"
,"Se qualquer parte do URL da página de Internet coincidir com a palavra predefinida, a ligação será bloqueada. Por exemplo, pode utilizar a palavra predefinida \"sexo\" para bloquear qualquer página da Internet cujo URL contenha a palavra \"sexo\". "
,"Ativar"
,"Assinale para ativar cada regra."
,"Nota: O URL de https pode não funcionar nesta função."
,"As definições da Tabela de Encaminhamento são definições utilizadas para configurar as funções do encaminhamento dinâmico e do encaminhamento estático."
,"Definição RIP"
,"O Protocolo de Informação de Encaminhamento (Routing Information Protocol - RIP) irá trocar informações acerca dos destinos para cálculo de rotas por toda a rede. Selecione RIPv2 apenas se dispuser de uma sub-rede diferente na sua rede. Caso contrário, selecione RIPv1 se necessitar deste protocolo. "
,"Regras de Encaminhamento"
,"Para encaminhamento estático, pode especificar até 8 regras de encaminhamento. Pode introduzir o endereço IP de destino, máscara de sub-rede, gateway e salto para cada rota de encaminhamento e, de seguida, ativar ou desativar a regra, marcando ou desmarcando a caixa de verificação Ativar."
,"A Qualidade do Serviço pode fornecer prioridade diferente a utilizadores ou fluxos de dados diferentes, ou garantir um determinado nível de desempenho."
,"Este dispositivo dispõe de duas funções de Controlo de Endereço MAC: Controlo de Ligação e Controlo de Associação. Ambas as funções são do nível MAC. Pode ativar estas funcionalidades assinalando a caixa \"Ativar\"."
,"Controlo de ligação"
,"O controlo de ligação permite-lhe aceitar ou recusar a ligação dos clientes com e sem fios a este dispositivo e à Internet. Assinale \"Controlo de ligação\" para ativar o controlo."
,"Se for recusada a ligação a este dispositivo por parte de um cliente, significa que o cliente não pode aceder à Internet e a alguns recursos da rede. Escolha \"permitir\" ou \"recusar\" para aceitar ou recusar clientes cujos endereços MAC não estejam listados na \"Tabela de controlo\"."
,"Controlo de Associação"
,"O processo de \"Associação\" é a troca de informação entre clientes sem fios e este dispositivo, para estabelecer uma ligação entre eles. Um cliente sem fios será capaz de transmitir e receber dados de/para este dispositivo apenas depois do processo de associação ser concluído com sucesso."
,"O controlo de associação permite-lhe aceitar ou recusar clientes sem fios que queiram ligar-se a este dispositivo. Assinale \"Controlo de associação\" para controlar quais os clientes sem fios que poderão \"associar-se\" à LAN sem fios. "
,"Se for recusada a associação de um cliente à LAN sem fios, significa que o cliente não poderá enviar ou receber quaisquer dados através deste dispositivo. Escolha \"permitir\" ou \"recusar\" para aceitar ou recusar clientes cujos endereços MAC não estejam listados na \"Tabela de controlo\"."
,"O Filtro Interno/Externo permite-lhe controlar quais os pacotes que podem passar pelo router. O Filtro externo aplica-se a todos os pacotes externos. No entanto, o Filtro Interno aplica-se a pacotes que se destinam apenas a Servidores Virtuais ou ao anfitrião DMZ."
,"Pode selecionar uma das duas políticas de filtragem:"
,"Permitir a passagem a todos exceto aos que cumprem as regras especificadas"
,"Recusar a passagem a todos exceto aos que cumprem as regras especificadas"
,"Pode especificar 100 regras para cada direção: interna ou externa. Para cada regra, pode definir o seguinte:"
,"Endereço IP de origem"
,"Endereço de porta de origem"
,"Endereço IP de destino"
,"Endereço de porta de destino"
,"Para endereço IP de origem ou destino, pode definir um único endereço IP (4.3.2.1) . Um campo em branco implica todos os endereços IP."
,"Para a porta de origem ou destino, pode definir uma única porta (80) ou um intervalo de portas (1000-1999). Um campo em branco implica todos os endereços de porta."
,"Cada regra pode ser ativada ou desativada individualmente."
,"Utilizar Regra número"
,"Escolha o agendamento para quando pretender que este serviço produza efeitos e selecione a ID que pretende utilizar com a regra de agendamento. De seguida, clique no botão \"Copiar para\" para o copiar para a caixa \"Utilizar Regra número\" para utilizar o agendamento. Ao escolher a regra 0 para sempre, significa o mesmo que não utilizar o agendamento."
,"Ativar SNMP"
,"Deve marcar a opção Local ou Remota ou ambas para ativar a função SNMP. Se marcar a opção Local, este dispositivo irá responder ao pedido da LAN. Se marcar a opção Remota, este dispositivo irá responder ao pedido da WAN. "
,"Obter Comunidade"
,"Definição da comunidade de Obter Pedido a que o seu dispositivo irá responder."
,"Definir Comunidade"
,"Definição da comunidade de Definir Pedido que o seu dispositivo irá aceitar."
,"UPnP"
,"UPnP é a abreviatura para Universal Plug and Play que se destina a simplificar a instalação e gestão do serviço de rede e do dispositivo. Se ativar esta função, o router irá funcionar com dispositivos/softwares UPnP."
,"NOTA: As portas no intervalo de 1 a 1024 estão bloqueadas. Se for necessário utilizá-las, recorra ao Servidor Virtual ou à zona DMZ."
,"Ping WAN"
,"Se ativar esta função, a porta WAN do seu router responderá aos pedidos de ping a partir da Internet que sejam enviados para o endereço IP da WAN.‎"
,"As definições de Configuração de Tempo são utilizadas pelo router para sincronizar serviços e a atividade de registo do sistema agendados. Necessita de definir o fuso horário correspondente à sua localização. O dispositivo pode ligar a um servidor NTP (Network Time Protocol - Protocolo da Hora da Rede) para recuperar a hora."
,"Fuso Horário - Selecione o Fuso Horário para a região onde se encontra."
,"Configuração Automática da Hora - Selecione um servidor horário com o qual pretende que o dispositivo sincronize a hora."
,"Palavra-passe de administrador"
,"Introduza e confirme a palavra-passe que a conta de administrador vai utilizar para aceder à interface de gestão do router."
,"Gestão remota"
,"A Gestão Remota permite que o dispositivo seja configurado através da porta WAN (Rede de Área Alargada) a partir da Internet utilizando um explorador de Internet. Continua a ser necessário um nome de utilizador e uma palavra-passe para aceder à interface de gestão do router."
,"IP com Acesso Permitido - Esta opção permite aos utilizadores especificar um endereço IP específico a partir da Internet para permitirem o acesso remoto ao router. Por defeito, deixa-se este campo em branco, o que significa que qualquer endereço IP a partir da Internet pode aceder remotamente ao router quando a gestão remota estiver ativa."
,"Porta - Selecione a porta que será utilizada para aceder ao dispositivo."
,"Por exemplo: http://x.x.x.x:8080 onde x.x.x.x é o endereço IP da WAN do dispositivo e 8080 é a porta utilizada para a interface de Gestão na Internet."
,"Guardar as Definições no Disco Rígido Local"
,"Guardar as definições deste dispositivo num ficheiro."
,"Carregar as Definições a partir do Disco Rígido Local"
,"Carregar as definições deste dispositivo a partir de um ficheiro."
,"Repor as Definições Predefinidas de Origem"
,"repor as definições deste dispositivo para os valores predefinidos."
,"Colocar o dispositivo a reiniciar o software."
,"Pode atualizar o firmware do dispositivo utilizando esta ferramenta. Certifique-se de que o firmware que pretende utilizar está guardado no disco rígido local do computador. Clique em Procurar para procurar no disco rígido local o firmware a utilizar na atualização. "
,"Atualizar o firmware não alterará nenhuma das definições de sistema, mas recomenda-se que guarde as suas definições de sistema antes de atualizar o firmware."
,"Ativar o Registo no Servidor de Registo de Sistema"
,"Ativar significa ativar o serviço."
,"Endereço IP do Servidor de Registo de Sistema"
,"O IP do anfitrião de destino, para onde os syslogs serão enviados."
,"Ativar Agendamento - Selecione se quiser Ativar o Programador."
,"Editar - Para editar a regra do agendamento."
,"Eliminar - Para eliminar a regra do agendamento e o número de regra das regras que estão além da que foi eliminada diminuirão automaticamente em uma unidade."
,"Adicionar Nova Regra - Clique em \"Adicionar Nova Regra\" para entrar na página \"Definição de Regra de Agendamento\" para acrescentar uma nova regra de agendamento."
,"Nome da Regra - Pode dar um nome à regra, como FTP, VPN etc."
,"Hora de início - Hora de início do dia de processamento. Pode inserir de 00:01 a 23:59."
,"Hora de fim - Hora de fim do dia de processamento. Pode inserir de 00:01 a 23:59."
,"NOTA: a Hora de fim deve ser posterior à Hora de início."
,"NOTE: The End time should larger then the Start time."
,"When the Transparent Bridge WAN option is enabled the modem will stop its Router/NAT functions.  The Public WAN IP address from your ISP is passed straight through the modem to the local client PC/ or server. Only one port is able to access the Internet details using Transparent Bridge mode as NAT is disabled. Unless you have purchased multiple Public IP address from your ISP. <br>Transparent Bridge mode can only be used when a single IP address has been assigned by the ISP, Transparent Bridge mode is used when the use of NAT is not desired and there is single computer attached to the modem. When the Transparent Bridged modem is used in conjunction with a router handling DHCP, only then can multiple computers connect to the internet."
)