//English
//保留這一行
helppage_en=new Array(
 "This displays the MAC Address of the WAN interface, as well as the IP Address, Subnet Mask, Default Gateway, and DNS server information that the device has obtained from your ISP. It will also display the connection type (Dynamic, Static, or PPPoE) that is used establish a connection with your ISP. "
,"If the router is configured for Dynamic, then there will be buttons for releasing and renewing the IP Address assigned to the WAN interface. If the router is configured for PPPoE, there will be buttons for connecting and disconnecting the PPPoE session."
,"This displays System Name, System Uptime, HW version and SW version."
,"This displays the SSID, Channel, Total Clients and whether or not Encryption is enabled on the Wireless interface."
,"This displays the subnet mask of LAN interface and the pool of DHCP server."
,"Follow the seeting of WAN Service, but just enable the connection when WAN is off line and disable the connection when WAN is on line."
,"IPv6"
,"The IPv6 (Internet Protocol version 6) section is where you configure your IPv6 Connection type."
,"IPv6 Connection Type"
,"There are several connection types to choose from: Link-local, Static IPv6, Autoconfiguration, PPPoE.If you are unsure of your connection method, please contact your IPv6 Internet Service Provider."
,"Note: If using the PPPoE option, you will need to ensure that any PPPoE client software on your computers has been removed or disabled."
,"Link-local Mode"
,"The Link-local address is used by nodes and routers when communicating with neighboring nodes on the same link. This mode enables IPv6-capable devices to communicate with each other on the LAN side."
,"Static IPv6 Mode"
,"This mode is used when your ISP provides you with a set IPv6 addresses that does not change. The IPv6 information is manually entered in your IPv6 configuration settings. You must enter the IPv6 address, Subnet Prefix Length, Default Gateway, Primary DNS Server, and Secondary DNS Server. "
,"Your ISP provides you with all this information."
,"PPPoE"
,"Select this option if your ISP requires you to use a PPPoE (Point to Point Protocol over Ethernet) connection to IPv6 Internet. DSL providers typically use this option. "
,"This method of connection requires you to enter a Username and Password (provided by your Internet Service Provider) to gain access to the IPv6 Internet. The supported authentication protocols are PAP and CHAP."
,"LAN IPv6 ADDRESS SETTINGS"
,"These are the settings of the LAN (Local Area Network) IPv6 interface for the router. The router's LAN IPv6 Address configuration is based on the IPv6 Address and Subnet assigned by your ISP. (A subnet with prefix /64 is supported in LAN.)"
,"LAN Address Autoconfiguration Settings"
,"Use this section to set up IPv6 Autoconfiguration to assign an IPv6 address to the computers on your local network. A Stateless and a Stateful Autoconfiguration method are provided."
,"The MAC information of the device which is connected to the AP service."
,"The \"WiFi Settings\"  page contains the settings for the (Access Point) Portion of the device . This page allows you to customize your wireless network or configure the device to fit an existing wireless network that you may already have setup."
,"Wireless Band"
,"It shows the band of the current AP."
,"Enable Wireless"
,"The on/off configuration of the wireless service."
,"Wireless Network Name"
,"Also known as the SSID (Service Set Identifier), this is the name of your Wireless Local Area Network (WLAN). This can be easily changed to establish a new wireless network or to add the device to an existing wireless network."
,"802.11 Mode"
,"Allow user to chnage the mode which is supported. It is include only mode and mixed mode."
,"Enable Auto Channel Scan"
,"The on/off switch to allow device scan the environment first before starting the wireless service."
,"Wireless Channel"
,"To show the current channel the device is used and user can change it when \"Enable Auto Channenl Scan\" is disabled."
,"Channel Width"
,"User can chnage the width of the channel.Wide channel get better bandwidth but poor sensitivity."
,"Security Mode"
,"Securing your wireless network is important as it is used to protect the integrity of the information being transmitted over your wireless network. The device is capable of 4 types of wireless security; WEP, WPA only, WPA2 only, and WPA/WPA2 (auto-detect)"
,"WEP"
,"Wired Equivalent Protocol (WEP) is a wireless security protocol for Wireless Local Area Networks (WLAN). WEP provides security by encrypting the data that is sent over the WLAN. The device supports 2 levels of WEP Encryption: 64-bit and 128-bit. WEP is disabled by default. "
,"The WEP setting can be changed to fit an existing wireless network or to customize your wireless network."
,"Authentication -  Authentication is a process by which the device verifies the identity of a network devicethat is attempting to join the wireless network. There are two types authentication for this device when using WEP."
,"Open System -  Select this option to allow all wireless devices to communicate with the device before they arerequired to provide the encryption key needed to gain access to the network."
,"Shared Key -  Select this option to require any wireless device attempting to communicate with the device to provide the encryption key needed to access the network before they are allowed to communicate with the device."
,"WEP Encryption -  Select the level of WEP Encryption that you would like to use on your network. The two supported levels of WEP encryption are 64-bit and 128-bit."
,"Key Type -  The Key Types that are supported by the device are HEX (Hexadecimal) and ASCII (American Standard Code for Information Interchange.) The Key Type can be changed to fit an existing wireless network or to customize your wireless network."
,"Keys -  Keys allow you to easily change wireless encryption settings to maintain a secure network. Simply select the specific key to be used for encrypting wireless data on the network."
,"WPA-Personal"
,"Accept WPA or WPA2 clients only and Pre-share key (encryption key) must be entered manually. You can input either 8 to 63 ASCII characters or 64 Hexadecimal digits as Pre-share key."
,"Cipher Type -  The device support two different cipher types when WPA is used as the Security Type. These two options are TKIP (Temporal Key Integrity Protocol) and AES (Advanced Encryption Standard)."
,"Pre-Shared Key -  This is what your wireless clients will need in order to communicate with your device, when PSK is selected. Enter 8-63 alphanumeric characters. Be sure to write this Passphrase down as you will need to enter it on any other wireless devices you are trying to add to your network."
,"Wi-Fi Protected Setup provides a more intuitive way of setting up wireless security between the router and the wireless client. Make sure the wireless card supports such feature or uses a certified Windows Vista driver in order to take advantage of this feature."
,"Beacon Interval"
,"Beacons are packets sent by an Access Point to synchronize a wireless network. Specify a Beacon interval value between 20 and 1024."
,"Transmit Power"
,"Select the transmit power of antenna. User can set the power level to 100%, 50%, 25%,12%."
,"DTIM interval"
,"A DTIM(Delivery Traffic Indication Message) is a countdown message for Access Point to inform clients of the next window for listening to broadcast and multicast messages. "
,"When the Access Point has buffered broadcast or multicast messages for associated clients, it sends the next DTIM with a DTIM Interval value. AP clients hear the beacons and awaken to receive the broadcast and multicast messages. Enter a value between 1 and 255 for the DTIM interval."
,"WMM Capable"
,"Enabling WMM can help control latency and jitter when transmitting multimedia content over a wireless connection."
,"TX Rates"
,"Select the transmission rates depending on the speed of your wireless network. You can select from a range of transmiision speeds, or you can select Auto to let Router to select automatically. The default is Auto."
,"Short GI"
,"Using a short (400ns) guard interval can increase throughput. However, it can also increase error rate in some installations, due to increased sensitivity to radio-frequency reflections. Select the option that works best for your installation."
,"HT 20/40 Coexistence"
,"Enable or Disable HT BSS coexistence."
,"The device list of DHCP client including Host Name, IP Address and MAC Address."
,"These are the settings of the LAN (Local Area Network) interface for the device. These settings may be referred to as \"private settings\". You may change the Router IP address if needed. The Router IP address is private to your internal network and cannot be seen on the Internet."
,"Router IP Address"
,"IP address of the device."
,"Default Subnet Mask"
,"Subnet Mask of device."
,"Local Domain Name"
,"Enter in the local domain name for your network.This is an optional setting."
,"DHCP Server"
,"DHCP stands for Dynamic Host Control Protocol. The DHCP server assigns IP addresses to devices on the network that request them. These devices must be set to \"Obtain the IP address automatically\". By default, the DHCP Server is enabled on the device . "
,"The DHCP address pool contains the range of the IP address that will automatically be assigned to the clients on the network."
,"Enable DHCP Server"
,"The on/off switch controls the DHCP Server function of the device."
,"DHCP IP Address Range"
,"Config the starting IP address and ending IP address for the DHCP server's IP assignment."
,"DHCP Lease Time"
,"The length of time in minutes for the IP lease."
,"Primary DNS IP Address / Secondary DNS IP Address"
,"These two settings are optional. Use can assign the DNS server wanted to use."
,"Dynamic DNS (Domain Name Service) is a method of keeping a domain name linked to a changing (dynamic) IP address. With most Cable and DSL connections, you are assigned a dynamic IP address and that address is used only for the duration of that specific connection. "
,"With the device , you can setup your DDNS service and the device will automatically update your DDNS server every time it receives a new WAN IP address."
,"Server Address"
,"Choose your Dynamic DNS provider from the drop down menu."
,"Host Name"
,"Enter the Host Name that you registered with your DDNS service provider."
,"Username / Email"
,"Enter the username for your DDNS account."
,"Password / Key "
,"Enter the password for your DDNS account."
,"Some applications require multiple connections, like Internet games, Video conferencing, Internet telephony and so on. Due to the firewall function, these applications can not work with pure NAT router. Special Applications makes some of these applications to work with NAT router."
,"Trigger"
,"The outbound port number issued by the application."
,"Incoming ports"
,"When the trigger packet is detected, the inbound packets to the specified port numbers are allowed to pass through the firewall."
,"This product provides some predefined settings. Select your application and click Copy to to add the predefined setting to your list. If the mechanism of Special Applications fails to make an application to work, try DMZ host instead."
,"NOTE: At any time, only one PC can use each Special Application."
,"The computer can be configured as a DMZ host accessible via the Internet, so that between the host and the Internet can be implemented an unlimited number of services and data transfers. For example Internet gaming or teleconferencing, and other special applications."
,"Virtual Server enables WWW, FTP and other services on your LAN to be accessible to Internet users. Refer Internet Services for well known ports."
,"URL Filter will block LAN computers to connect to pre-defined Websites."
,"URL Blocking Enable"
,"Check if you want to enable URL Blocking."
,"URL"
,"If any part of the Website's URL matches the pre-defined word, the connection will be blocked.For example, you can use pre-defined word \"sex\" to block all websites if their URLs contain pre-defined word \"sex\". "
,"Enable"
,"Check to enable each rule."
,"Note: The URL of https may be not working in this function."
,"Routing Table settings are settings used to setup the functions of dynamic routing and static routing."
,"RIP Setting"
,"Routing Information Protocol (RIP) will exchange information about destinations for computing routes throughout the network.Please select RIPv2 only if you have different subnet in your network.Otherwise, please select RIPv1 if you need this protocol. "
,"Routing Rules"
,"For static routing, you can specify up to 8 routing rules.You can enter the destination IP address, subnet mask, gateway, hop for each routing rule, and then enable or disable the rule by checking or unchecking the Enable checkbox."
,"Quality of Service can provide different priority to different users or data flows, or guarantee a certain level of performance."
,"This device provides two features in MAC Address Control: Connection Control and Association Control. Both these features are MAC level. You can enable these features by checking the \"Enable\" box."
,"Connection control"
,"Connection control allows you to allow or deny the wired and wireless clients to connect to this device and the Internet. Check \"Connection control\" to enable the controlling."
,"If a client is denied to connect to this device, it means that the client can't access the Internet and some network resources. Choose \"allow\" or \"deny\" to allow or deny clients whose MAC addresses are not listed in the \"Control table\"."
,"Association control"
,"The \"Association\" process is the exchange of information between wireless clients and this device to establish a link between them. A wireless client is capable of transmitting and receiving data to this device only after the association process is successfully completed."
,"Association control allows you to allow or deny the wireless clients to link up to this device. Check \"Association control\" to control which of the wireless clients will be able to \"associate\" to the wireless LAN. "
,"If a client is denied to associate to the wireless LAN, it means that the client can't send or receive any data through this device. Choose \"allow\" or \"deny\" to allow or deny clients whose MAC addresses are not listed in the \"Control table\"."
,"Outbound/Inbound Filter enables you to control what packets are allowed to pass the router. Outbound filter applies on all outbound packets. However, Inbound filter applies on packets that destined to Virtual Servers or DMZ host only."
,"You can select one of the two filtering policies:"
,"Allow all to pass except those match the specified rules"
,"Deny all to pass except those match the specified rules"
,"You can specify 100 rules for each directions: inbound or outbound. For each rule, you can define the following:"
,"Source IP address"
,"Source port address"
,"Destination IP address"
,"Destination port address"
,"For source or destination IP address, you can define a single IP address (4.3.2.1) . An empty implies all IP addresses."
,"For source or destination port, you can define a single port (80) or a range of ports (1000-1999). An empty implies all port addresses."
,"Each rule can be enabled or disabled individually."
,"Use Rule#"
,"Choose the schedule when you want to make this service take effect, and select the ID you want to use with the schedule rule. Then click \"Copy to\" botton to copy it into the \"Use rule #\" box to use the schedule.When choosing rule 0 for always, it is the same as not using schedule."
,"Enable SNMP"
,"You must check either Local or Remote or both to enable SNMP function.If Local is checked, this device will response request from LAN.If Remote is checked, this device will response request from WAN. "
,"Get Community"
,"Setting the community of GetRequest your device will response."
,"Set Community"
,"Setting the community of SetRequest your device will accept."
,"UPnP"
,"UPnP is short for Universal Plug and Play which is designed to simplify device and network service installation and management.If you enable this function,the router will work with UPnP devices/softwares."
,"NOTE: Ports from range 1 to 1024 are blocked. If you require to use them, use the Virtual Server or DMZ zone."
,"WAN Ping"
,"If you enable this feature, the WAN port of your router will respond to ping requests from the Internet that are sent to the WAN IP Address."
,"The Time Configuration settings are used by the router for synchronizing scheduled services and system logging activities. You will need to set the time zone corresponding to your location. The device can connect to a NTP (Network Time Protocol) server to retrieve the time."
,"Time Zone - Select the Time Zone for the region you are in."
,"Automatic Time Configuration -Select a time server which you would like the device to synchronize its time with."
,"Administrator password"
,"Enter and confirm the password that the admin account will use to access the router's management interface."
,"Remote Management"
,"Remote Management allows the device to be configured through the WAN (Wide Area Network) port from the Internet using a web browser. A username and password is still required to access the router's management interface."
,"IP Allowed to Access - This option allows users to specify a particular IP address from the Internet to be allowed to access the router remotely. This field is left blank by default which means any IP address from the Internet can access the router remotely once remote management is enabled."
,"Port - Select the port which will be used to access the device ."
,"Example:http://x.x.x.x:8080 whereas x.x.x.x is the WAN IP address of the device and 8080 is the port used for the Web-Management interface."
,"Save Settings To Local Hard Drive"
,"Save the settings of this device to a file."
,"Load Settings From Local Hard Drive"
,"Load the settings to this device from a file."
,"Restore To Factory Default Settings"
,"Reset the settings of this device to the default values."
,"Reboot the Device"
,"Make the device doing software reboot."
,"You can upgrade the firmware of the device using this tool. Make sure that the firmware you want to use is saved on the local hard drive of the computer. Click on Browse to search the local hard drive for the firmware to be used for the update. "
,"Upgrading the firmware will not change any of your system settings but it is recommended that you save your system settings before doing a firmware upgrade."
,"Enable Logging To Syslog Server"
,"Enable it to active the service."
,"Syslog Server IP Address"
,"Host IP of destination where syslogs will be sent to."
,"Schedule Enable - Select if you want to Enable the Scheduler."
,"Edit - To edit the schedule rule."
,"Delete - To delete the schedule rule, and the rule# of the rules behind the deleted one will decrease one automatically."
,"Add New Rule - Click \"Add New Rule\" to enter \"Schedule Rule Setting\" page to increase a new schedule rule."
,"Name of Rule - You can give the rule a name, like FTP, VPN etc."
,"Start time - Start time of the processing day.You can input from 00:01 to 23:59."
,"End time -  End time of the processing day.You can input from 00:01 to 23:59."
,"NOTE: The End time should larger then the Start time."
,"When the Transparent Bridge WAN option is enabled the modem will stop its Router/NAT functions.  The Public WAN IP address from your ISP is passed straight through the modem to the local client PC/ or server. Only one port is able to access the Internet details using Transparent Bridge mode as NAT is disabled. Unless you have purchased multiple Public IP address from your ISP. <br>Transparent Bridge mode can only be used when a single IP address has been assigned by the ISP, Transparent Bridge mode is used when the use of NAT is not desired and there is single computer attached to the modem. When the Transparent Bridged modem is used in conjunction with a router handling DHCP, only then can multiple computers connect to the internet."
)