//French
common=new Array(
 "Actualiser"
,"Aide"
,"Fermeture de session"
,"Activer"
,"Désactiver"
,"Élément"
,"Modifier"
,"Supprimer"
,"Retour"
,"Auto"
,"Manuel"
,"Appliquer"
,"Réinitialiser"
,"Ajouter"
,"secondes"
,"octets"
,"ID"
,"Copier sur"
,"Page précédente"
,"Page suivante"
,"Ajouter une règle..."
,"La meilleure"
,"minutes"
,"Activé"
,"Désactivé"
,"First Page"
,"Last Page"
,"Download"
,"Page"
)

others=new Array(
 "Réinitialiser"
,"Redémarrer le routeur ?"
,"Vous vous êtes déconnecté"
,"Page de produits"
,"Version du microprogramme"
,"copyright"
,"Conseils utiles..."
,"Plus…"
,"Enregistrer les paramètres"
,"Ne pas enregistrer les paramètres"
,"Pas de modification"
,"Pas de modification !"
,"Continuer"
,"Paramètres enregistrés !"
,"La modification s'applique immédiatement !"
,"Configuration terminée"
,"Système en cours de traitement, veuillez patienter quelques secondes..."
,"ROUTEUR"
,"Nom d'utilisateur"
,"Mot de passe"
,"Ouverture de session"
,"Nom d'utilisateur ou mot de passe incorrect"
,"Veuillez saisir un nom d'utilisateur valide."
,"Nom d'utilisateur ou mot de passe incorrect"
,"La session s'est bien fermée."
,"Vous vous êtes déconnecté."
,"Veuillez vous connecter d'abord !"
,"Veuillez saisir un nom d'utilisateur valide"
,"Saisissez un mot de passe correct"
,"Saisissez le nom d'utilisateur."
,"La valeur d'entrée ne peut pas être vide."
,"Veuillez patienter quelques secondes..."
,"L'administrateur du compte déjà logined"
,"Êtes-vous d'accord ?"
)

dirary0=new Array(
 "Domicile"
,"internet"
,"Wi-Fi"
,"Réseau local"
,"Avancé"
,"Système"
,"Service WAN"
,"Basculement"
,"IPv6"
,"Liste des périphériques"
,"Paramètres Wi-Fi"
,"WPS"
,"Wi-Fi avancé"
,"Paramètres du LAN"
,"DHCP"
,"DNS"
,"Applications"
,"DMZ"
,"Serveur virtuel"
,"Filtre URL"
,"Redirection"
,"QoS"
,"Filtre d'adresse MAC"
,"Filtre sortant"
,"Filtre entrant"
,"SNMP"
,"Réseau avancé"
,"Paramètres horaires"
,"Administration"
,"Redémarrer et réinitialiser"
,"Mise à jour du microprogramme"
,"Journaux système"
,"Calendriers"
,"Assistant"
,"Network Scan"
,"Réinitialisation de la connexion"
,"Configuration du PIN"
,"Message Service"
,"Boîte de réception SMS"
,"Créer un message"
,"Voix"
,"Transfert d'appel"
,"Appel en attente"
,"Diagnostique"
,"TR-069"
,"Multi-WAN"
)

valchk=new Array(
 "Veuillez revérifier les paramètres !"
,"L'adresse IP n'est pas valide."
,"Le masque de sous-réseau n'est pas valide."
,"La plage d'adresses IP n'est pas valide."
,"L'adresse IP du LAN n'est pas valide."
,"valeur n'est pas valide."
,"Le port n'est pas valide."
,"(Exemple de format : 1-65535,777)"
,"La plage de ports n'est pas valide. (Exemple de format : 1-65535)"
,"La MTU n'est pas valide !"
,"L'heure n'est pas valide."
,"Heure incorrecte."
,"L'adresse MAC n'est pas valide."
,"La clé WEP est incorrecte."
,"La clé pré-partagée est incorrecte."
,"Email non valide."
,"Saisissez 10 ou 26 caractères hexadécimaux dans le champ Clé WEP !"
,"Saisissez 5 ou 13 caractères ASCII dans le champ Clé WEP !"
,"Saisissez 64 caractères hexadécimaux ou 8~63 caractères ASCII dans le champ Clé pré-partagée !"
,"Saisissez 64 caractères hexadécimaux dans le champ Clé pré-partagée !"
," est non valide !"
)

//---------------------------------status---------------------------------
sta=new Array(
 "Général"
,"Heure"
,"Version du microprogramme"
,"WAN"
,"Type de connexion"
,"IP statique"
,"Adresse MAC"
,"Adresse IP"
,"Masque de sous-réseau"
,"Passerelle par défaut"
,"Serveur DNS"
,"Client DHCP"
,"État du réseau"
,"Client déconnecté"
,"Connexion en cours..."
,"Établi"
,"Déconnexion en cours…"
,"Attente de trafic..."
,"Temps de concession restant"
,"Renouveler"
,"Version"
,"PPPoE"
,"Déconnecté"
,"Temps de connexion"
,"Connexion"
,"Déconnecter"
,"Reconnecter"
,"PPTP"
,"L2TP"
,"4G LTE /3G"
,"Force du signal"
,"Info carte"
,"État de la liaison"
,"Échec auth."
,"PIN requis"
,"Erreur de mot de passe"
,"Aucun modem détecté"
,"Connexion impossible ! Vérifiez vos paramètres et réessayez."
,"Nom du réseau"
,"LAN"
,"Serveur DHCP"
,"LAN sans fil"
,"Sans fil"
,"SSID"
,"Sécurité"
,"Ouvrir"
,"Partagé"
,"Auto"
,"WPA-PSK"
,"WPA"
,"WPA2-PSK"
,"WPA2"
,"WPA-PSK / WPA2-PSK"
,"WPA / WPA2"
,"Aucun"
,"WEP"
,"TKIP"
,"AES"
,"TKIP/AES"
,"Canal"
,"Auto"
,"Mode 802.11"
,"B/G mixte"
,"Mode N"
,"B/G/N mixte"
,"Configuration sécurisée du Wi-Fi"
,"Ordinateurs du réseau local"
,"Nom"
,"MAC"
,"Jour"
,"Heure"
,"Min"
,"Sec"
,"S/O"
,"Basculement 3G"
,"Carte 3G"
,"Internet"
,"SSID2"
,"Nombre total de clients"
,"Pool DHCP"
,"Nom du système"
,"Temps d'utilisation du système"
,"Version du matériel"
,"Version logicielle"
,"Basculement"
,"Partage de charge"
,"Type de service"
,"Téléphone"
,"Aucun Service"
,"État"
)

//---------------------------------Internet---------------------------------
prim=new Array(
 "Type de connexion Internet"
,"Ma connexion Internet est"
,"IP statique"
,"IP dynamique (DHCP)"
,"PPPoE (nom d'utilisateur/mot de passe)"
,"PPTP (nom d'utilisateur/mot de passe)"
,"L2TP (nom d'utilisateur/mot de passe)"
,"4G LTE /3G"
,"Sauvegarde automatique"
,"Activer le contrôle du lien WAN filaire"
,"Hôte Internet"
,"Veuillez saisir une adresse IP sur Internet."
,"Connexion Internet de type adresse IP statique"
,"Adresse IP"
,"Masque de sous-réseau"
,"Passerelle par défaut"
,"Serveur DNS principal"
,"Serveur DNS secondaire"
,"MTU"
,"MTU par défaut (octets) = 1500"
,"Adresse MAC"
,"Cloner"
,"Effacer"
,"Connexion Internet de type IP dynamique (DHCP)"
,"Nom d'hôte"
,"Reconnexion automatique"
,"PPPoE"
,"Nom d'utilisateur"
,"Mot de passe"
,"Confirmer le mot de passe"
,"Nom du service"
,"(en option)"
,"Adresse IP"
,"Temps d'inactivité maximum"
,"MTU par défaut (octets) = 1492"
,"PPTP"
,"Mode adresse"
,"Adresse IP dynamique"
,"IP statique"
,"Adresse IP de PPTP"
,"Masque de sous-réseau PPTP"
,"Adresse IP d'une passerelle PPTP"
,"Adresse IP du serveur PPTP"
,"Mode de reconnexion"
,"Toujours activé"
,"Connexion à la demande"
,"L2TP"
,"Adresse IP de L2TP"
,"Masque du sous-réseau L2TP"
,"Adresse IP de la passerelle L2TP"
,"Adresse IP du serveur L2TP"
,"Connexion Internet de type 4G LTE/3G"
,"Compte/Nom du profil"
,"Numéro composé"
,"Authentification"
,"PAP"
,"CHAP"
,"APN"
,"Code PIN"
,"Maintenir actif"
,"Désactiver"
,"Utiliser ping"
,"DNS Query"
,"Utiliser la requête d'écho LCP"
,"Intervalle des échos lcp :"
,"Échec des échos lcp :"
,"fois"
,"Adresse IP du ping"
,"Intervalle entre les pings"
,"Ports Ethernet du pont"
,"L'adresse MAC a été modifiée"
,"La nouvelle adresse MAC sera effective après le redémarrage."
,"Redémarrer maintenant ?"
,"Itinérance"
,"Contrôle DNS"
,"Désactiver NAT"
,"Mode Auto"
,"Mode 4G uniquement"
,"Mode 3G seulement"
,"Mode 2G seulement"
,"Type de service privilégié"
,"Configuration du service WAN"
,"en option"
,"Transparent Bridge"
,"Interface WAN"
,"Fermer"
," WAN Ethernet"
,"Profil de numérotation"
,"Détection automatique"
,"Pays"
,"Télécom"
,"Réseau"
,"Autres"
,"Configuration du réseau"
,"Les nouveaux mots de passe sont différents !"
,"configuration non valide !"
,"Mode Auto"
,"Mode de préférence 3G"
,"Mode 2G d'abord"
,"Chargement"
,"Réseau 3G/4G"
,"WCDMA/HSP"
,"CDMA2000/EV-DO"
,"Adresse IP et passerelle par défaut non valides."
,"La plage de durées d'inactivité maximales doit être entre"
,"Connexion Internet de type 3G"
,"VLAN Tagging"
)

failover=new Array(
 "Configuration du basculement"
,"Type de basculement"
,"Hôte distant pour Keep alive"
,"Liste des basculements"
,"Interface"
,"Changer"
,"La connexion Internet actuelle est"
,"Le type Internet de basculement est"
,"Basculement"
,"Type de connexion de basculement"
,"Configuration de l'interface de basculement"
,"Voulez-vous vraiment supprimer le WAN secondaire ?"
,"Configuration de la sauvegarde automatique"
,"Sauvegarde automatique"
,"Hôte distant pour Keep alive"
,"Liste des connexions WAN"
,"Interface"
,"Veuillez modifier ou supprimer l'interface !"
,"L'hôte distant pour Keep alive ne peut pas être vide !"
,"Sélection invalide !"
,"WAN principal"
,"WAN secondaire"
,"Changer le type de WAN effacera les paramètres de basculement.\nÊtes-vous d'accord ?"
,"Partage de charge"
,"Configuration du basculement..."
,"Charger le type de connexion de partage"
,"Adresse IP dynamique"
,"Adresse IP statique"
,"Port 1"
,"Port 2"
,"Sélectionnez WAN secondaire !"
,"L'activation des ports Bridge Ethernet va désactiver le WAN Ethernet."
)

ipv6=new Array(
 "Paramètres 6 à 4"
,"Adresse 6 à 4"
,"Adresse DNS principale"
,"Adresse DNS secondaire"
,"Paramètres de l’adresse IPv6 du réseau local"
,"Adresse IPv6 du réseau local"
,"Adresse lien-local du réseau local IPv6"
,"Paramètres de configuration automatique de l'adresse"
,"Autoconfiguration"
,"Type d'autoconfiguration"
,"Durée de vie de l'annonce de routeur"
,"Adresse IPv4 distante"
,"Adresse IPv4 locale"
,"Adresse IPv6 locale"
,"Configuration IPv6"
,"Type de connexion IPv6"
,"Sans état"
,"À état (DHCPv6)"
,"Cette section vous permet de configurer les paramètres du réseau interne de votre routeur. L'adresse lien-local IPv6 du réseau local est l'adresse IPv6 que vous utilisez pour accéder à l'interface de gestion Web. Si vous changez l'adresse IPv6 du réseau local ici, vous devrez peut être ajuster les paramètres réseau de votre PC pour accéder de nouveau au réseau."
,"Activer le DHCP-PD"
,"Paramètres de configuration automatique de l'adresse du LAN"
,"Cette section vous permet de paramétrer l'autoconfiguration IPv6 afin d'attribuer des adresses IP aux ordinateurs de votre réseau."
,"Activer l'autoconfiguration"
,"SLAAC+DHCPv6 sans état"
,"Adresse lien-local du réseau local IPv6"
,"Utilisez cette section pour configurer votre type de connexion IPv6. Si vous n'êtes pas sûr de votre méthode de connexion, contactez votre fournisseur d'accès Internet."
,"Lorsque vous configurez le routeur pour accéder à l'Internet IPv6, choisissez l'option Type de connexion IPv6 appropriée dans le menu déroulant. Si vous ne savez pas quelle option choisir, contactez votre fournisseur d'accès Internet (FAI)."
,"Choisissez le mode que le routeur doit utiliser pour se connecter à l'Internet IPv6."
,"Autoconfiguration (SLAAC/DHCPv6);"
,"Tunnel IPv6 sur IPv4"
,"6rd"
,"Lien-local uniquement"
,"Informations sur la connexion IPv6"
,"Type de connexion IPv6"
,"État du réseau"
,"Adresse IPv6 du WAN"
,"Passerelle IPv6 par défaut"
,"Serveur DNS IPv6 principal"
,"Serveur DNS IPv6 secondaire"
,"Adresse LAN lien-local IPv6"
,"DHCP-PD"
,"Réseau IPv6 attribué par DHCP-PD"
,"Adresse LAN IPv6"
,"Adresse IPv6"
,"Nom (le cas échéant)"
,"IPv6 statique"
,"DHCPv6"
,"6 à 4"
,"PPPoA"
,"*Bouton de connexion pour IPv4 et IPv6"
,"*Bouton de déconnexion pour IPv4 et IPv6"
,"Adresse IPv6 globale"
,"Paramètres de l’adresse WAN IPv6 "
,"Longueur du préfixe de sous-réseau"
,"Paramètres PPPoE ou PPPoA"
,"Paramètres du tunnel IPv6 sur IPv4"
,"Adresse IPv6 distante"
,"Paramètres DNS IPv6"
,"Configuration du DNS"
,"Obtenir automatiquement une adresse de serveur DNS"
,"Utiliser l'adresse DNS suivante"
,"Paramètres 6RD"
,"Longueur du masque IPv4"
,"Préfixe distant"
,"Longueur du préfixe"
,"Plage d'adresses IPv6 (début)"
,"Plage d'adresses IPv6 (fin)"
,"Durée de vie de l'adresse IPv6"
,"Activer DS-Lite"
,"Configuration de DS-Lite"
,"Option DHCPv6 de DS-Lite"
,"Configuration manuelle"
,"Adresse lien-local du WAN"
,"IPv6 dynamique"
,"Intercommunication IPv6"
,"Votre adresse WAN IPv4 n'est pas une adresse globale."
,"WAN IPv6 Address Status"
)

//---------------------------------WiFi---------------------------------
wpa=new Array(
 "Paramètres du réseau sans fil"
,"Activer le réseau sans fil"
,"Nom de votre réseau sans fil"
,"(Également appelée SSID)"
,"Mode 802.11"
,"B/G mixte"
,"Mode N"
,"B/G/N mixte"
,"Balayage automatique des canaux"
,"Canal sans fil"
," GHz - CH "
,"État de visibilité"
,"Visible"
,"Invisible"
,"Mode de sécurité sans fil"
,"Mode de sécurité"
,"Aucun"
,"WEP"
,"WPA-Personnel"
,"WPA Entreprise"
,"WEP"
,"Le mode WEP est une norme de chiffrement sans fil. Pour l'utiliser, vous devez entrer les mêmes clés dans le routeur et les stations sans fil. Dans le cas des clés de 64 bits, vous devez entrer 10 caractères hexadécimaux dans chaque champ. Dans le cas des clés de 128 bits, vous devez entrer 26 caractères hexadécimaux dans chaque champ. Un caractère hexadécimal peut être un chiffre de 0 à 9 ou une lettre de A à F. Quand le mode WEP est activé et pour garantir une sécurité optimale, définissez le type d'authentification sur &quot;Clé partagée&quot;."
,"Vous pouvez aussi entrer n'importe quelle chaîne de texte dans le champ de la clé WEP, auquel cas les valeurs ASCII des caractères sont converties en valeurs hexadécimales. Vous pouvez saisir un maximum de 5 caractères de texte pour les clés de 64 bits et un maximum de 13 caractères pour les clés de 128 bits."
,"Authentification"
,"Ouvrir"
,"Partagé"
,"Chiffrement WEP"
,"64 bits"
,"128 bits"
,"Clé WEP par défaut"
,"Clé WEP 1"
,"Clé WEP 2"
,"Clé WEP 3"
,"Clé WEP 4"
,"Clé WEP"
,"HEXADÉCIMAL"
,"ASCII"
,"WPA"
,"Utilisez le mode <B>WPA ou WPA2</b> pour obtenir le meilleur compromis entre sécurité et compatibilité. Ce mode utilise le WPA avec les anciens clients tout en maintenant un niveau de sécurité plus élevé avec les stations compatibles avec le WPA2. Par ailleurs, le chiffrement utilisé est toujours le plus élevé pris en charge par le client. Pour une sécurité optimale, utilisez le mode <B>WPA2 uniquement</B>. Ce mode utilise le protocole de chiffrement AES (CCMP). L'accès est refusé aux anciennes stations compatibles uniquement avec le WPA. Pour une compatibilité maximale, utilisez <B>WPA uniquement</B>. Ce mode utilise le protocole de chiffrement TKIP. Certains périphériques de jeu ou d'ancienne génération ne fonctionnent que dans ce mode.<BR><BR>Pour obtenir de meilleures performances sans fil, utilisez le mode de sécurité <B>WPA2 seulement</b> (en d'autres termes le protocole de chiffrement AES)."
,"Mode WPA"
,"WPA2 seulement"
,"WPA seulement"
,"Type de chiffrement"
,"TKIP"
,"AES"
,"Clé pré-partagée"
,"Saisissez un mot de passe alphanumérique comportant entre 8 et 63 caractères. Plus il est long et original, plus la sécurité est accrue."
,"Clé de réseau"
,"(8~63 ASCII ou 64 HEX)"
,"EAP (802.1x)"
,"Quand le mode WPA entreprise est activé, le routeur utilise le protocole EAP (802.1x) pour authentifier les clients par l'intermédiaire d'un serveur RADIUS externe."
,"Adresse IP du Serveur RADIUS"
,"Port du serveur RADIUS"
,"Secret partagé du Serveur RADIUS"
,"(13 ASCII ou 26 HEX)"
,"(5 ASCII ou 10 HEX)"
,"Les paramètres seront appliqués après le redémarrage."
,"Voulez-vous vraiment modifier ?"
,"Configuration wifi"
,"Dans cette section, vous pouvez configurer l'interface sans fil (point d'accès) disponible sur le routeur."
,"Bande de 2,4GHz"
,"Bande de 5GHz"
,"Bande de fréquences sans fil"
,"Activer le balayage automatique du canal"
,"Largeur de canal"
,"20/40 MHz (Auto)"
,"20/40/80 MHz (Auto)"
,"802.11b seulement"
,"Mode 802.11g seulement"
,"Mode 802.11n seulement"
,"Mode mixte 802.11g et 802.11b"
,"Mode mixte 802.11n et 802.11g"
,"Mode mixte 802.11n, 802.11g et 802.11b"
,"Mode 802.11a seulement"
,"Mode 802.11n seulement"
,"Mode mixte 802.11a et 802.11n"
,"802.11 a/n/ac mixte"
,"la longueur s'applique à toutes les clés"
,"Longueur de la clé WEP"
,"Avertissement ! Régler le mode de sécurité de la bande 2,4 GHz sur « NONE » génèrera des risques de sécurité. Voulez-vous quand même le configurer ?"
,"Il est nécessaire d'arrêter la fonction WPS pour activer le paramètre WEP de la bande 2,4 GHz. Voulez-vous quand même le configurer ?"
,"Avertissement ! Régler le mode de sécurité de la bande 5GHz sur « NONE » génèrera des risques de sécurité. Voulez-vous quand même le configurer ?"
,"Il est nécessaire d'arrêter la fonction WPS pour activer le paramètre WEP de la bande 5GHz. Voulez-vous quand même le configurer ?"
,"64 bits (10 chiffres hexadécimaux)"
,"128 bits (26 caractères hexadécimaux)"
,"Avertissement ! Régler le mode de sécurité de la bande 2,4 GHz sur « NONE » génèrera des risques de sécurité. Voulez-vous quand même le configurer ?"
,"Avertissement ! Régler le mode de sécurité de la bande 5GHz sur « NONE » génèrera des risques de sécurité. Voulez-vous quand même le configurer ?"
,"Il est nécessaire d'arrêter la fonction WPS pour activer le paramètre WEP de la bande 2,4 GHz. Voulez-vous quand même le configurer ?"
,"Il est nécessaire d'arrêter la fonction WPS pour activer le paramètre WEP de la bande 5GHz. Voulez-vous quand même le configurer ?"
,"Auto (WPA ou WPA2)"
)

wps=new Array(
 "NON CONFIGURÉ"
,"Définir"
,"CONFIGURÉ"
,"Version"
,"NON UTILISÉ"
,"INACTIF"
,"PROCESSFAIL"
,"STARTPROCESS"
,"RECVEAPOLSTART"
,"SENDEAPREQID"
,"RECVEAPRSPID"
,"RECVWRGVENDORID"
,"RECVWRGVENDORTYPE"
,"SENDEAPREQSTART"
,"SENDM1"
,"RECVM1"
,"SENDM2"
,"RECVM2"
,"RECVM2D"
,"SENDM3"
,"RECVM3"
,"SENDM4"
,"RECVM4"
,"SENDM5"
,"RECVM5"
,"SENDM6"
,"RECVM6"
,"SENDM7"
,"RECVM7"
,"SENDM8"
,"RECVM8"
,"PROCEAPRSPACK"
,"PROCEAPREQDONE"
,"PROCEAPRSPDONE"
,"SENDEAPFAIL"
,"ERRHASHFAIL"
,"ERRHMACFAIL"
,"ERRDEVPWDAUTHFAIL"
,"CONFIGURÉ"
,"Configuration sécurisée du Wi-Fi"
,"WPS"
,"PIN PA"
,"Générer un nouveau PIN"
,"Mode config"
,"Inscrit"
,"Registraire"
,"État config"
,"Méthode config"
,"Code PIN"
,"Bouton-poussoir"
,"État du WPS"
,"Déclenchement"
,"Lecture..."
,"WPS (Wi-Fi Protected Setup)"
,"La fonction WPS permet de configurer facilement et en toute sécurité une connexion sans fil. Dans cette section, vous pouvez activer WPS pour une connexion cliente utilisant la sécurité WPA/WPA2."
,"La longueur du code PIN doit être = 4 ou 8"
,"Erreur de règle du code PIN !"
,"Désactiver la méthode WPS-PIN"
,"La longueur du code PIN doit être = 4 ou 8"
,"Erreur de règle du code PIN !"
)

wlpfe=new Array(
 "Paramètres sans fil avancés"
,"Intervalle de balise"
,"(ms, plage : 10~1024)"
,"Puissance de transmission"
,"Seuil RTS"
,"(1~2 347, par défaut 2 347)"
,"Fragmentation"
,"(256~2346, par défaut 2346)"
,"Intervalle DTIM"
,"(plage : 1~255)"
,"Compatible WMM"
,"Vitesses des paquets transmis"
,"Spécifiez les paramètres de configuration avancée pour la radio des passerelles à partir de cette page. Les paramètres de sécurité et d'associations des PA peuvent être modifiés à partir des valeurs par défaut si nécessaire."
,"Paramètres sans fil avancés 2,4 G "
,"Paramètres sans fil avancés 5G"
,"GI court"
,"Coexistence HT20/40"
)

//---------------------------------LAN---------------------------------
devlist=new Array(
 "Listes des clients du LAN"
,"Nom de l'hôte (le cas échéant)"
,"Adresse IP"
,"Adresse MAC"
)

lanst=new Array(
 "Paramètres du routeur"
,"Cette section permet de configurer les paramètres du réseau interne du routeur. L'adresse IP qui est configurée ici est l'adresse IP que vous utilisez pour accéder à l'interface de gestion Web. Si vous changez l'adresse IP, vous devrez peut-être ajuster les paramètres réseau de votre PC pour accéder à nouveau au réseau."
,"Adresse IP du routeur"
,"Masque de sous-réseau par défaut"
,"Nom de domaine local"
,"Paramètres du serveur DHCP"
,"Cette section vous permet de configurer le serveur DHCP intégré afin d'attribuer une adresse IP aux ordinateurs de votre réseau."
,"Activer le serveur DHCP"
,"Plage d'adresses IP DHCP"
,"à"
,"(adresses dans le sous-réseau du LAN)"
,"Durée de la concession DHCP"
,"Adresse IP du DNS principal"
,"Adresse IP du DNS secondaire"
,"Adresse IP principale du WINS"
,"Adresse IP secondaire du WINS"
,"La configuration de l'adresse IP du LAN sera effective après le redémarrage."
,"Voulez-vous vraiment modifier ?"
,"Plage d'adresses IP non valide !"
,"Adresse de début de la plage IP"
,"Adresse de fin de la plage IP"
,"Le nom de domaine local est invalide."
,"Cette section vous permet de configurer les paramètres du LAN de votre routeur. Notez que cette section est facultative et que vous n'êtes tenu de modifier aucun paramètre pour rendre votre réseau opérationnel."
,"Configuration de l'interface IP"
,"Serveur DHCP"
,"Configuration du serveur DHCP"
,"Réservation DHCP"
)

//---------------------------------Advanced---------------------------------
ddns=new Array(
 "DNS dynamique"
,"Activer le DDNS"
,"Fournisseur"
,"DynDNS.org(dynamique)"
,"DynDNS.org(personnalisé)"
,"No-IP.com"
,"TZO.com"
,"dhs.org"
,"Nom d'hôte"
,"Nom d'utilisateur/E-mail"
,"Mot de passe/Clé"
,"La résolution de l'adresse IP en noms/domaines d'hôte et vice versa est gérée par le DNS. Les informations requises (adresse IP du dernier serveur DNS) sont généralement fournies par votre FAI. Mais le périphérique est également en mesure de détecter automatiquement les serveurs DNS disponibles."
)

spap=new Array(
 "Applications courantes"
,"-- Sélectionner un --"
,"Battle.net"
,"Dialpad"
,"ICU II"
,"Zone de jeu MSN"
,"PC-Téléphone"
,"Quick Time 4"
,"Règles d'application"
,"Déclenchement"
,"Ports entrants"
,"Application"
,"Le port de service du serveur virtuel et le port d'entrée des règles d'application ne peuvent pas être identiques."
,"La valeur du port d'entrée ne peut pas être identique."
)

dmz=new Array(
 "Paramètres du pare-feu"
,"Activer SPI"
,"Hôte DMZ"
,"L'option DMZ (zone démilitarisée) vous permet de configurer un ordinateur de votre réseau « à l'extérieur » du routeur. Si vous avez un ordinateur qui ne peut pas utiliser correctement des applications Internet derrière le routeur, vous pouvez le placer dans la DMZ pour qu'il puisse accéder à Internet sans aucune restriction."
,"<b>Remarque :</b> Le fait de placer un ordinateur dans la DMZ l'expose à divers risques liés à la sécurité. Utilisez cette option uniquement en dernier recours."
,"Activer la DMZ"
,"Adresse IP de la DMZ"
,"Nom de l'ordinateur"
)

smap=new Array(
 "Services connus"
,"-- Sélectionner un --"
,"AUTH (113)"
,"DNS (53)"
,"FTP (21)"
,"ISAKMP (500)"
,"POP3 (110)"
,"PPTP (1723)"
,"SMTP (25)"
,"TELNET (23)"
,"WEB (80)"
,"Utiliser une règle de calendrier"
,"---TOUJOURS ACTIVÉ---"
,"Liste des serveurs virtuels"
,"Ports de service"
,"Adresse IP du serveur : Port"
,"Activer"
,"N° règle de calendrier"
,"L' Externe se comporte comme un serveur. Il reçoit les demandes des utilisateurs distants sous son adresse IP publique et les transferts automatiquement au serveur virtuel. "
,"De sorte qu'un client de votre réseau derrière une NAT ou un pare-feu peut fournir des services en tant que serveur virtuel. "
,"Il vous suffit d'activer des ports ou des plages de ports et des protocoles spécifiques (UDP/TCP). Des services Web ou de partage tels que HTTP, FTP ou POP3 sont possibles. Les adresses IP privées des serveurs du réseau local demeurent sécurisées. Si vous possédez une adresse IP dynamiques, vous pouvez activer en plus DynDNS."
,"La valeur du port de service ne peut pas être identique."
,"erreur de configuration"
)

uctl=new Array(
 "Configuration du filtrage d'URL"
,"Filtre URL"
,"Activer"
,"Règles de filtrage des URL"
,"URL"
,"Activer"
,"L'URL ne peut pas être vide !"
,"http://' n'est pas autorisé !"
,"Les filtres d'URL sont des outils utiles pour limiter l'accès à Internet. "
,"L'option de blocage des URL des sites Web vous permet de créer rapidement une liste de tous les sites Web pour lesquels vous souhaitez autoriser ou refuser l'accès aux utilisateurs."
,"Filtre URL"
)

rtab=new Array(
 "Configuration RIP"
,"RIP"
,"Activer"
,"RIPv1"
,"RIPv2"
,"Règles d'acheminement"
,"Cible"
,"Masque de sous-réseau"
,"Passerelle"
,"Saut"
,"Les routes pour le trafic de votre réseau sont définies dans la table de routage. En général, les entrées de l'adresse IP et de la passerelle sont suffisantes. Il n'est pas nécessaire de définir d'autres paramètres."
)

qos=new Array(
 "Élevée"
,"Normal"
,"Basse"
,"Configuration du moteur QoS"
,"Activer le filtre de paquets QoS"
,"Largeur de bande montante"
,"Largeur de bande descendante"
,"kbit/s"
,"Utiliser une règle de calendrier"
,"---TOUJOURS ACTIVÉ---"
,"Règles de QoS"
,"IP locale : Ports"
,"IP distante : Ports"
,"Priorité QoS"
,"Activer"
,"Utiliser la règle n°"
,"Configuration du moteur QoS"
)

pmac=new Array(
 "Paramètres de filtrage MAC"
,"Contrôle d'adresse MAC"
,"Activer"
,"Contrôle de connexion"
,"Les clients sans fil et câblés pour lesquels le mode <b>C</b>est sélectionné peuvent se connecter à ce périphérique et "
,"autoriser"
,"refuser"
," la connexion des adresses MAC non spécifiées."
,"Contrôle d'association"
,"Les clients sans fil pour lesquels le mode <b>A</b> est sélectionné peuvent être associés au réseau local sans fil et "
,"autoriser"
,"refuser"
," l'association des adresses MAC non spécifiées."
,"Clients DHCP"
,"-- Sélectionner un --"
,"Règles de filtrage MAC"
,"Adresse MAC"
,"Adresse IP"
,"C"
,"A"
)

iopf=new Array(
 "Configuration des filtres sortants"
,"Configuration des filtres entrants"
,"Filtre sortant"
,"Filtre entrant"
,"Activer"
,"Utiliser une règle de calendrier"
,"---TOUJOURS ACTIVÉ---"
,"Liste des règles de filtre sortant"
,"Liste des règles de filtre entrant"
,"Tout autoriser, sauf ce qui correspond aux règles suivantes."
,"Tout refuser, sauf ce qui correspond aux règles suivantes."
,"IP source:Ports"
,"IP cible:Ports"
,"Activer"
,"N° règle de calendrier"
,"Erreur d'utilisation du nombre de règles !"
)

snmp=new Array(
 "SNMP"
,"SNMP local"
,"SNMP distant"
,"Obtenir communauté"
,"Définir communauté"
,"IP 1"
,"IP 2"
,"IP 3"
,"IP 4"
,"Version SNMP"
,"V1"
,"V2c"
,"Adresse IP d'accès au WAN"
)

fmisc=new Array(
 "UPnP"
,"Le service Universal Plug and Play (UPnP) permet aux périphériques réseau de prendre en charge la fonctionnalité Plug & Play poste à poste."
,"Activer l'UPnP"
,"PING DU WAN"
,"Si vous activez cette fonction, le port WAN de votre routeur répondra aux demandes de ping émises par Internet et envoyées à l'adresse IP du WAN."
,"Activer la réponse aux requêtes ping du WAN"
)

networkscan=new Array(
 "Sélection du fournisseur de réseau"
,"Cette page va analyser les fournisseurs de réseaux à proximité.<br>Veuillez patienter pour chaque analyse."
,"Méthode de sélection du réseau 3G/4G"
,"En cours..."
,"Liste des fournisseurs de réseau"
,"Il n'existe pas de fournisseur de réseau"
,"Vous ne choisissez pas de fournisseur réseau le mode devient Auto"
,"Vos modifications ont été enregistrées. Le routeur doit être redémarré pour que les modifications prennent effet."
,"Vous pouvez redémarrer maintenant ou continuer à réaliser des modifications et redémarrer plus tard."
,"Disponible"
,"Actuel"
,"Interdit"
,"Rechercher"
,"Network Selection Method"
)

//---------------------------------System---------------------------------
sntp=new Array(
 "Configuration de date et heure"
,"Heure"
,"Fuseau horaire"
,"Activer l'heure d'été"
,"Synchroniser les paramètres horaires de votre ordinateur"
,"Configuration automatique de date et heure"
,"Synchroniser automatiquement avec un serveur de temps Internet"
,"Serveur NTP utilisé"
,"Mettre à jour maintenant"
,"Sync. RÉSULTAT"
,"Début"
,"Fin"
,"Heure"
,"Jour"
,"Mois"
,"(heure/jour/mois)"
,"Jan."
,"Févr."
,"Mars"
,"Avr."
,"Mai"
,"Juin"
,"Juil."
,"Août"
,"Sep."
,"Oct."
,"Nov."
,"Déc."
,"Dim"
,"Lun"
,"Mar"
,"Mer"
,"Jeu"
,"Ven"
,"Sam"
,"L'option Configuration de l'heure vous permet de configurer, de mettre à jour et de gérer l'heure de l'horloge système interne."
,"Cette section vous permet également de définir le fuseau horaire ainsi que le serveur NTP (protocole horaire en réseau)."
,"Vous pouvez également configurer l'heure d'été pour que le changement se fasse automatiquement, le cas échéant."
,"Heure"
,"Paramètres horaires"
)

tz=new Array(
 "* Pas encore configuré ! La valeur par défaut est GMT+00:00"
,"Côté ouest de la ligne de changement de date"
,"Îles Midway, Samoa"
,"Hawaii"
,"Alaska"
,"Heure du Pacifique (États-Unis et Canada)"
,"Tijuana"
,"Arizona"
,"Chihuahua, La Paz, Mazatlán"
,"Heure des Rocheuses (États-Unis et Canada)"
,"Amérique centrale"
,"Heure centrale (États-Unis et Canada)"
,"Guadalajara, Mexico, Monterrey"
,"Saskatchewan"
,"Bogota, Lima, Quito"
,"Heure de l'Est (États-Unis et Canada)"
,"Indiana (Est)"
,"Heure de l'Atlantique (Canada)"
,"Caracas, La Paz"
,"Santiago"
,"Terre-Neuve"
,"Brasilia"
,"Buenos Aires, Georgetown"
,"Groënland"
,"Atlantique centrale"
,"Açores"
,"Îles de Cap-Vert"
,"Casablanca, Monrovia"
,"Dublin, Édimbourg, Lisbonne, Londres"
,"Amsterdam, Berlin, Berne, Rome, Stockholm, Vienne"
,"Belgrade, Bratislava, Budapest, Ljubljana, Prague"
,"Bruxelles, Copenhague, Madrid, Paris"
,"Sarajevo, Skopje, Varsovie, Zagreb"
,"Afrique centrale de l'Ouest"
,"Athènes, Beyrouth, Istanbul, Minsk"
,"Bucarest"
,"Le Caire"
,"Harare, Pretoria"
,"Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius"
,"Jérusalem (2007 uniquement)"
,"Bagdad"
,"Koweït, Riyad"
,"Moscou, Saint-Pétersbourg, Volgograd"
,"Nairobi"
,"Téhéran"
,"Abou Dabi, Muscat"
,"Baku"
,"Tbilissi"
,"Yerevan"
,"Kaboul"
,"Ekaterinbourg"
,"Islamabad, Karachi, Tachkent"
,"Chennai, Calcutta, Bombay, New Delhi"
,"Katmandou"
,"Almaty, Novossibirsk"
,"Almaty, Dhaka"
,"Colombo"
,"Rangoun"
,"Bangkok, Hanoï, Jakarta"
,"Krasnoïarsk"
,"Pékin, Chongqing, Hong Kong, Urumqi"
,"Irkutsk"
,"Kuala Lumpur, Singapour"
,"Perth, Australie occidentale"
,"Taipei"
,"Oulan-Bator"
,"Osaka, Sapporo, Tokyo"
,"Séoul"
,"Iakutsk"
,"Adélaïde"
,"Darwin"
,"Brisbane"
,"Canberra, Melbourne, Sydney"
,"Guam, Port Moresby"
,"Hobart"
,"Vladivostok"
,"Magadan, Îles Salomon, Nouvelle Calédonie"
,"Wellington, Auckland"
,"Fiji, Kamchatka, îles Marshall"
,"Nuku'alofa"
,"* Configurez la variable TZ manuellement..."
,"Eniwetok, Kwajalein"
,"Mexico, Tegucigalpa"
,"Bruxelles, Copenhague, Madrid, Paris, Vilnius"
,"Sarajevo, Skopje, Sofia, Varsovie, Zagreb"
,"Athènes, Beyrouth, Le Caire, Istanbul, Minsk"
,"Pékin, Hong-Kong, Taipei"
,"Inde"
)

atbox=new Array(
 "Administrateur (le nom de connexion par défaut est "
,")"
,"Nom de connexion"
,"Nouveau mot de passe"
,"Confirmer le mot de passe"
,"Gestion à distance"
,"Activer la gestion à distance"
,"IP dont l’accès est autorisé"
,"Port"
,"Les nouveaux mots de passe administrateur sont différents !"
,"Voulez-vous enregistrer votre mot de passe comme vide ?"
,"Le port de gestion distant ne doit pas dépasser 1024."
,"Administrateur"
,"Ici, vous pouvez modifier le mot de passe de l'administrateur."
,"Le nom d'utilisateur (admin) ne peut pas être modifié."
,"Paramètres administrateur"
,"SSH"
,"Activer SSH"
,"Autoriser le WAN"
,"Telnet"
,"Activer Telnet"
,"Remote Administration"
)

rebo=new Array(
 "Mise à jour réussie !"
,"Fichier de mise à jour non valide !"
,"Vérifiez que le fichier est correct."
,"Le fichier n'est pas compatible avec le microprogramme ou le matériel actuel."
,"La mise à jour à cette version n'est pas autorisée !"
,"Le processus de mise à jour a été annulé pour une raison inconnue."
,"Réessayez !"
,"Toute la configuration est réinitialisée !"
,"Le périphérique est en cours de réinitialisation..."
,"<font color=red><b>N'ÉTEIGNEZ PAS</b></font> le périphérique."
,"Veuillez patientez "
," secondes..."
,"Veuillez vous reconnecter manuellement."
,"Remarque : L'adresse IP de votre LAN a peut-être changé, veuillez vous reconnecter."
,"Cliquez ici pour vous reconnecter"
,"Le système est prêt"
,"Redémarrer le routeur"
,"Message d'état"
,"Le routeur sera actif dans"
,"Redémarrer maintenant"
,"Redémarrer plus tard"
)

system=new Array(
 "Réinitialiser toute la configuration ?"
,"Enregistrer et restaurer les paramètres"
,"Enregistrer les paramètres sur le disque dur local"
,"Enregistrer"
,"Charger les paramètres depuis le disque dur local"
,"Télécharger les paramètres"
,"Restaurer les paramètres usine"
,"Remettre par défaut"
,"Fichier de mise à jour non valide !"
,"Fichier de mise à jour non autorisé !"
,"Système"
,"Tous les paramètres sont automatiquement enregistrés sur votre périphérique. Il n'est pas nécessaire de les enregistrer manuellement ni de redémarrer. Si vous souhaitez quand même rédémarrer le périphérique, il est préférable de le faire, bouton \"Redémarrer\"."
,"Paramètres système"
,"Rédémarrer le périphérique"
,"Restaurer tous les paramètres par défaut ?"
,"Réinitialiser"
,"Redémarrer et réinitialiser"
)

fwug=new Array(
 "Informations concernant le microprogramme"
,"Version actuelle du microprogramme"
,"Date du microprogramme actuel"
,"Mise à jour du microprogramme"
,"Remarque : N'éteignez pas le périphérique pendant sa mise à jour."
,"La procédure de mise à jour dure environ 180 secondes."
,"Une fois la mise à jour effectuée, le périphérique redémarre automatiquement."
,"Pour pouvoir mettre à jour le microprogramme, le PC doit être relié physiquement au routeur. Entrez le nom du fichier de mise à niveau du microprogramme, puis cliquez sur le bouton Télécharger sur le périphérique."
,"Charger"
,"Mettre à jour"
,"Nom de fichier incorrect"
,"Seul le fichier .bin est accepté."
,"Annuler"
,"La mise à jour d'un autre microprogramme est en cours !"
,"Acceptez un microprogramme non officiel."
,"Utilisez le bouton \"Mettre à niveau\" pour mettre à jour la version du microprogramme de votre périphérique."
,"Mise à jour du microprogramme"
,"Sélectionner un microprogramme"
,"Vérifiez fichier"
,"Nouvelle information Firmware"
,"Nouveau Firmware Version"
,"Nouvelle date de Firmware"
)

logs=new Array(
 "Paramètres de SysLog"
,"Activer la journalisation sur un serveur SysLog"
,"Adresse IP du serveur SysLog"
,"Paramètres E-mail"
,"Activer la notification par E-mail"
,"Adresse IP et port du serveur SMTP"
,"Envoyer une alerte email à"
,"Sujet de l'email"
,"Nom d'utilisateur SMTP"
,"Mot de passe SMTP"
,"Consigner l'email maintenant"
,"Un email est en attente d'envoi..."
,"Journal système"
,"Le journal système vous permet de configurer la journalisation locale, distante et des emails, et d'afficher les journaux que vous avez créés."
,"Clear logs"
,"Log Number"
,"Message"
,"View Logs"
)

smsmsg=new Array(
 "Répondre au message"
,"Transmettre le message"
,"Créer un message"
,"Message texte"
,"Entrer un message..."
,"La longueur maximale d'un message ne peut pas dépasser 160 caractères."
,"Destinataire"
,"Ajoutez ‘+’ pour le format international du numéro de téléphone."
,"Envoyer"
,"Lecture... Veuillez patienter..."
,"Longueur du texte actuellement entré"
,"Envoi du message"
,"Si vous voulez créer et envoyer un message SMS, cliquez sur le bouton ci-dessous."
,"Le destinataire ne peut pas être vide !"
,"The max. length of a message is 160 characters for pure alphabetical or numeric."
)

smsinbox=new Array(
 "État du SMS"
,"SMS reçu"
,"Nouveau SMS"
,"Capacité totale"
,"Boîte de réception"
,"De"
,"Horodateur"
,"Texte"
,"SMS"
,"Lecture... Veuillez patienter..."
,"Répondre"
,"Transférer"
,"Boîte de réception SMS"
,"Si vous voulez afficher le message SMS, cliquez sur le bouton ci-dessous."
,"Configuration de SMSC"
,"Veuillez vérifier si la carte SIM est insérée ou non."
,"La carte SIM est verrouillée ! Impossible de lire les SMS depuis la carte SIM."
,"Le modem n'est pas prêt !"
,"Le modem est occupé par un appel téléphonique ! Veuillez patienter..."
,"Envoyer OK !"
,"Échec envoi !"
,"Le modem est occupé par un appel téléphonique ! Le SMS sera automatiquement envoyé plus tard."
,"Supprimer OK !"
,"Échec de la suppression !"
,"Échec de la commande AT !"
,"Le modem est occupé par un appel téléphonique ! Le SMS sera automatiquement supprimé plus tard."
)

voiceforwd=new Array(
 "Tous les appels"
,"Pas de réponse"
,"Injoignable"
,"Occupé"
,"État"
,"Désenregistrer"
,"Enregistrer"
,"Activer"
,"Désactiver"
,"Numéro"
)

pinco=new Array(
 "État de la demande... Veuillez patienter..."
,"Code PIN SIM"
,"Saisissez 4~8 caractères dans le champ du code PIN SIM !"
,"Fonction de demande du CODE PIN"
,"Entrer le code PIN SIM"
,"Changer le code PIN..."
,"Succès !"
,"Saisissez 4~8 caractères dans le champ de l'ancien code PIN !"
,"Saisissez 4~8 caractères dans le champ du nouveau code PIN !"
,"Saisissez 4~8 caractères dans le champ de vérification du code PIN !"
,"Fonction le changement du CODE PIN"
,"Ancien code PIN"
,"Nouveau code PIN"
,"Vérifier le code PIN"
,"Enregistrer !"
,"Saisissez le code PIN pour déverrouiller la carte SIM"
,"CODE PIN"
,"Saisissez le code PUK pour déverrouiller la carte SIM"
,"CODE PUK"
,"Nouveau CODE PIN"
,"La fonction est déjà désactivée !"
,"La fonction est déjà activée !"
,"Mauvais code PIN !"
,"Vous devez d'abord activer la fonction de demande du code PIN !"
,"Vous avez saisi deux nouveaux codes PIN différents !"
,"Mauvais ancien code PIN !"
,"Mauvais code PUK !"
,"Échec de la commande AT !"
,"Prête"
,"Verrouillé par PIN SIM"
,"Verrouillé par PUK SIM"
,"Carte SIM avec des erreurs."
,"Le modem ne répond pas."
,"Échec de l'envoi de la commande AT !"
,"Le modem n'existe pas ! Veuillez vérifier si la carte SIM est insérée !"
,"Avertissement : Encore 3 essais autorisés."
,"Réessayer"
,"Continuer"
,"Avertissement : "
," essais de plus autorisés."
,"Saisissez 4~8 caractères dans le champ du CODE PIN !"
,"Saisissez 8 caractères dans le champ du CODE PUK !"
,"Contrôle PIN"
,"Le modem est en cours d'initialisation ; veuillez patienter !"
,"Configuration du PIN"
,"Insérer code PIN 3 fois sûr! S'il vous plaît insérer du code PUK."
)

ussd=new Array(
 "USSD"
,"Envoyer"
,"ERREUR"
)

scherebo=new Array(
 "Réinitialisation de la connexion"
,"Redémarrage automatique"
,"Calendrier de redémarrage"
,"Calendrier du journal"
,"Jour de la semaine du calendrier hebdomadaire"
,"Date du mois"
)

sche=new Array(
 "Règle de calendrier"
,"Activer le calendrier"
,"Règle n°"
,"Nom de la règle"
,"Action"
,"Aucune règle ajoutée, veuillez ajouter des règles avant d'activer !"
,"Voulez-vous vraiment supprimer la règle "
,"??"
,"Schedule"
)

rule=new Array(
 "Le nom de la règle ne peut pas être vide !"
,"Le nom du calendrier existe déjà dans une autre règle !"
,"(Règle :"
,")"
,"Contrôlez à nouveau !"
,"L'heure de début du jour "
," est incorrecte !"
,"L'heure de fin du jour "
," est incorrecte !"
,"L'heure du jour "
," est incorrecte !"
,"L'heure de fin doit être postérieure à l'heure de début"
,"(le format de l'heure du calendrier doit être hh:mm)"
,"(0 < heure de début < 23)"
,"(0 < minutes de l'heure de début < 59)"
,"(0 < heure de fin < 23)"
,"(0 < minutes de l'heure de fin < 59)"
,"Sélectionnez un jour dans l'ID de règle "
,"!!"
,"L'heure de la règle du calendrier est vide !"
," Veuillez saisir au moins un calendrier !"
,"Chaque jour"
,"Dimanche"
,"Lundi"
,"Mardi"
,"Mercredi"
,"Jeudi"
,"Vendredi"
,"Samedi"
,"Configuration de la règle de calendrier"
,"Nom de la règle"
,"-- sélectionner --"
,"Politique"
,"Retour"
,"Désactiver"
,"Activer"
,"sauf les jours et heures sélectionnés ci-dessous."
,"Jour"
,"Heure de début (hh:mm)"
,"Heure de fin (hh:mm)"
)

diagnostic=new Array(
 "Informations sur le service"
,"Opérateur"
,"Diffusion de cellule"
,"MCC"
,"MNC"
,"LAC"
,"Type de service"
,"Type de service privilégié"
,"GSM seul"
,"WCDMA seul"
,"Inconnu"
,"La connexion au PS (DONNÉES)"
,"Connexion au CS (VOCAL)"
,"IMSI"
,"SMSC"
,"Connecté"
,"Déconnecté"
,"État de la carte SIM"
,"Verrouillage du code PIN"
,"Nombre de nouvelles tentatives du code PIN"
,"Nombre de nouvelles tentatives du code PUK"
,"État du module"
,"IMEI"
,"Version du microprogramme"
,"Nom du module"
,"ID de cellule"
)

voice=new Array(
 "Voix"
,"Transfert d'appel"
,"Appels entrants à redirection automatique vers un numéro désigné dans différentes conditions."
,"Appel en attente"
,"Suspendre l'appel actuel et pouvoir parler sur un nouvel appel entrant."
,"Accéder au transfert d'appel"
,"Accéder à l'appel en attente"
)

sms=new Array(
 "Créer un message"
,"Vous permet de créer et d'envoyer un nouveau message SMS."
,"boîte de réception"
,"Vous permet de lire un nouveau message SMS et de supprimer/transmettre un message existant."
,"Vous ne pouvez répondre qu'à un seul message à la fois !"
)

tr069=new Array(
 "TR-069"
,"TR-069 Setting"
,"ACS Setting"
,"ACS URL"
,"ACS UserName"
,"ACS Password"
,"CPE Setting"
,"ConnectionRequest Port"
,"ConnectionRequest UserName"
,"ConnectionRequest Password"
,"Inform Setting"
,"Inform"
,"Interval"
,"Interface"
)
