//German
common=new Array(
 "Aktualisieren"
,"Hilfe"
,"Abmelden"
,"Aktivieren"
,"Deaktivieren"
,"Objekt"
,"Bearbeiten"
,"Löschen"
,"Zurück"
,"Auto"
,"Manuell"
,"Anwenden"
,"Rücksetzen"
,"Hinzufügen"
,"Sekunden"
,"Byte"
,"ID"
,"Kopieren nach"
,"Vorherige Seite"
,"Nächste Seite"
,"Neue Regel hinzufügen..."
,"Beste"
,"Minuten"
,"Aktiviert"
,"Deaktiviert"
,"First Page"
,"Last Page"
,"Download"
,"Page"
)

others=new Array(
 "Neu starten"
,"Router neu starten?"
,"Sie sind abgemeldet."
,"Produktseite"
,"Firmware-Version"
,"Copyright"
,"Nützliche Tipps..."
,"Mehr..."
,"Einstellungen speichern"
,"Einstellungen nicht speichern"
,"Keine Änderung"
,"Keine Änderung"
,"Weiter"
,"Einstellungen gespeichert."
,"Die Änderung wird sofort wirksam."
,"Einstellung abgeschlossen"
,"System verarbeitet die Daten, bitte ein paar Sekunden warten..."
,"ROUTER"
,"Benutzername"
,"Passwort"
,"Anmeldung"
,"Benutzername oder Kennwort ungültig"
,"Geben Sie einen gültigen Benutzernamen ein."
,"Benutzername oder Kennwort ungültig"
,"Sie sind nun abgemeldet."
,"Sie sind abgemeldet."
,"Bitte zuerst anmelden!"
,"Geben Sie einen gültigen Benutzernamen ein."
,"Gültiges Kennwort eingeben."
,"Geben Sie bitte den Benutzernamen ein."
,"Der Eingabewert darf nicht leer sein."
,"Bitte ein paar Sekunden warten..."
,"Der Kontoadministrator bereits logined"
,"Sind Sie damit einverstanden?"
)

dirary0=new Array(
 "Home"
,"Internet"
,"Wi-Fi"
,"LAN"
,"Erweitert"
,"System"
,"WAN-Dienst"
,"Failover"
,"IPv6"
,"Geräteliste"
,"Wi-Fi-Einstellungen"
,"WPS"
,"Wi-FI Erweitert"
,"LAN-Einstellungen"
,"DHCP"
,"DNS"
,"Anwendungen"
,"DMZ"
,"Virtueller Server"
,"URL Filter"
,"Routing"
,"QoS"
,"MAC-Adressfilter"
,"Ausgangsfilter"
,"Eingangsfilter"
,"SNMP"
,"Erweitertes Netzwerk"
,"Zeiteinstellungen"
,"Administration"
,"Neustart und Zurücksetzen"
,"Firmware-Upgrade"
,"Systemprotokolle"
,"Zeitpläne"
,"Assistent"
,"Netzwerk-Scan"
,"Rücksetzen der Verbindung"
,"PIN-Konfiguration"
,"Message Service"
,"SMS-Eingang"
,"Nachricht erstellen"
,"Sprache"
,"Anrufweiterleitung"
,"Anklopfen"
,"Diagnose"
,"TR-069"
,"Multi-WAN"
)

valchk=new Array(
 "Prüfen Sie bitte noch einmal die Einstellung."
,"Die IP-Adresse ist ungültig."
,"Die Subnetzmaske ist ungültig."
,"Der IP-Adressbereich ist ungültig."
,"Die LAN-IP-Adresse ist ungültig."
,"Der Wert ist ungültig."
,"Der Port ist ungültig."
,"(Format z. B. 1-65535,777)"
,"Der Portbereich ist ungültig. (Format z. B. 1-65535)"
,"MTU ist ungültig."
,"Die Stundenangabe ist ungültig."
,"Die Zeit ist ungültig."
,"Die Mac-Adresse ist ungültig."
,"Der WEP-Schlüssel ist ungültig."
,"Der Preshare-Schlüssel ist ungültig."
,"Die E-Mail ist ungültig."
,"Geben Sie bitte 10 oder 26 Hexadezimalzeichen im Feld 'WEP-Schlüssel' ein."
,"Geben Sie bitte 5 oder 13 ASCII -Zeichen im Feld 'WEP-Schlüssel' ein."
,"Geben Sie bitte 64 Hexadezimalzeichen oder 8~63 ASCII-Zeichen im Feld 'Preshared Key' ein."
,"Geben Sie bitte 64 Hexadezimalzeichen im Feld 'Preshared Key' ein."
," ist ungültig!"
)

//---------------------------------status---------------------------------
sta=new Array(
 "Allgemein"
,"Zeit"
,"Firmware-Version"
,"WAN"
,"Verbindungstyp"
,"Statische IP-Adresse"
,"MAC-Adresse"
,"IP-Adresse"
,"Subnetzmaske"
,"Standard-Gateway"
,"DNS Server"
,"DHCP Client"
,"Netzwerkstatus"
,"Client-Verbindung getrennt"
,"Verbindung wird hergestellt..."
,"Hergestellt"
,"Verbindung wird getrennt..."
,"Auf Datenverkehr warten..."
,"Verbleibende Lease-Zeit"
,"Erneuern"
,"Freigabe"
,"PPPoE (PPPoE aktivieren)"
,"Getrennt"
,"Verbindungszeit"
,"Verbinden"
,"Verbindung trennen"
,"Wiederverbindung"
,"PPTP"
,"L2TP"
,"4G LTE/3G"
,"Signalstärke"
,"Karteninfo"
,"Link-Status"
,"Auth.-Fehler"
,"PIN erforderlich"
,"Kennwortfehler"
,"Kein Modem erkannt"
,"Keine Verbindung möglich. Überprüfen Sie Ihre Einstellungen und versuchen Sie es noch einmal."
,"Netzwerkname"
,"LAN"
,"DHCP-Server"
,"WLAN"
,"Drahtlos"
,"SSID"
,"Sicherheit"
,"Offen"
,"Freigegeben"
,"Auto"
,"WPA-PSK"
,"WPA"
,"WPA2-PSK"
,"WPA2"
,"WPA-PSK/WPA2-PSK"
,"WPA/WPA2"
,"Keine"
,"WEP"
,"TKIP"
,"AES"
,"TKIP/AES"
,"Kanal"
,"Auto"
,"802.11-Modus"
,"B/G Mischmodus"
,"N-Modus"
,"B/G/N Mischmodus"
,"WPS (Wi-Fi Protected Setup)"
,"LAN-Computer"
,"Name"
,"MAC"
,"Tag"
,"Stunde"
,"Min"
,"Sek"
,"N/V"
,"3G Failover"
,"3G-Karte"
,"Internet"
,"SSID2"
,"Clients insgesamt"
,"DHCP Pool"
,"Systemname"
,"Systembetriebszeit"
,"HW-Version"
,"SW-Version"
,"Failover"
,"Lastverteilung"
,"Diensttyp"
,"Telefon"
,"Kein Service"
,"Status"
)

//---------------------------------Internet---------------------------------
prim=new Array(
 "Art der Internetverbindung"
,"Meine Internetverbindung ist"
,"Statische IP-Adresse"
,"Dynamische IP (DHCP)"
,"PPPoE (Benutzername/Kennwort)"
,"PPTP (Benutzername/Kennwort)"
,"L2TP (Benutzername / Kennwort)"
,"4G LTE/3G"
,"Auto-Backup"
,"Prüfung auf kabelgeb. WAN 'alive' aktivieren"
,"Internet-Host"
,"Geben Sie im Internet eine IP-Adresse ein."
,"Internetverbindungstyp 'Statische IP-Adresse'"
,"IP-Adresse"
,"Subnetzmaske"
,"Standard-Gateway"
,"Primärer DNS Server"
,"Sekundärer DNS Server"
,"MTU"
,"(Byte) MTU-Standard = 1500"
,"MAC-Adresse"
,"Kopieren"
,"Löschen"
,"Internetverbindungstyp 'Dynamische IP (DHCP)'"
,"Host-Name"
,"Autom. Neuverbindung"
,"PPPoE (PPPoE aktivieren)"
,"Benutzername"
,"Passwort"
,"Kennwort bestätigen"
,"Dienstname"
,"(optional)"
,"IP-Adresse"
,"Maximale Leerlaufzeit"
,"(Byte) MTU-Standard = 1492"
,"PPTP"
,"Adressmodus"
,"Dynamische IP-Adresse"
,"Statische IP-Adresse"
,"PPTP-IP-Adresse"
,"PPTP-Subnetzmaske"
,"PPTP-Gateway-IP-Adresse"
,"PPTP-Server-IP-Adresse"
,"Wiederverbindungsmodus"
,"Immer aktiv"
,"Bei Bedarf verbinden"
,"L2TP"
,"L2TP-IP-Adresse"
,"L2TP-Subnetzmaske"
,"L2TP-Gateway-IP-Adresse"
,"L2TP Server IP-Adresse"
,"4G LTE/3G-Internetverbindungstyp"
,"Konto-/Profilname"
,"Gewählte Nummer"
,"Authentifizierung"
,"PAP"
,"CHAP"
,"APN"
,"PIN-Code"
,"Keep-alive"
,"Deaktivieren"
,"Ping verwenden"
,"DNS Query"
,"LCP Echo-Request verwenden"
,"lcp-echo-interval:"
,"lcp-echo-failure:"
,"Mal"
,"Ping IP-Adresse"
,"Ping-Intervall"
,"Bridge-Ethernet-Ports"
,"MAC-Adresse wurde geändert"
,"Neue MAC-Adresse wird nach Neustart wirksam."
,"Jetzt Neustart durchführen?"
,"Roaming"
,"DNS Check"
,"NAT deaktivieren"
,"Auto-Modus"
,"Modus Nur 4G"
,"Modus Nur 3G"
,"Modus Nur 2G"
,"Bevorzugter Servicetyp"
,"WAN-Dienstkonfiguration"
,"optional"
,"Transparente Bridge"
,"WAN-Schnittstelle"
,"Schließen"
,"Ethernet WAN"
,"Einwähl-Profil"
,"Autom. Erkennung"
,"Land"
,"Telecom"
,"Netzwerk"
,"Sonstiges"
,"Netzwerkeinrichtung"
,"Die neuen Kennwörter sind nicht identisch!"
,"Einstellung ungültig."
,"Auto-Modus"
,"Modus 3G bevorzugt"
,"Modus erst 2G"
,"Laden"
,"3G/4G-Netzwerk"
,"WCDMA/HSP"
,"CDMA2000/EV-DO"
,"IP-Adresse und Standard-Gateway sind ungültig!"
,"Bereich der max. Leerlaufzeit liegt zwischen"
,"3G-Internetverbindungstyp"
,"VLAN Tagging"
)

failover=new Array(
 "Failover - Ausfallsicherungseinstellungen"
,"Failover-Typ"
,"Remote Host for Keep Alive (Ferner Host für Keep Alive)"
,"Failover-Liste"
,"Schnittstelle"
,"Ändern"
,"Die aktuelle Internetverbindung ist"
,"Failover Internet-Typ ist"
,"Failover"
,"Failover-Verbindungstyp"
,"Failover-Schnittstelleneinstellung"
,"Möchten Sie das sekundäre WAN wirklich löschen?"
,"Auto-Backup-Einstellung"
,"Auto-Backup"
,"Remote Host for Keep Alive (Ferner Host für Keep Alive)"
,"WAN-Verbindungslisten"
,"Schnittstelle"
,"Bitte ändern oder löschen Sie die Schnittstelle!"
,"Der Remote-Host für Keep Alive darf nicht Null sein!"
,"Ungültige Auswahl!"
,"Primäres WAN"
,"Sekundäres WAN"
,"Das Ändern des WAN-Typs löscht alle Failover-Einstellungen.\nStimmen Sie zu?"
,"Lastverteilung"
,"Failover - Ausfallsicherungseinstellungen..."
,"Lastverteilungs-Verbindungstyp"
,"Dynamische IP-Adresse"
,"Statische IP-Adresse"
,"Port 1"
,"Port 2"
,"Bitte wählen Sie das sekundäre WAN!"
,"Durch die Aktivierung von Bridge Ethernet-Ports wird Ethernet WAN deaktiviert."
)

ipv6=new Array(
 "6 to 4-Einstellungen"
,"6 to 4 Adresse"
,"Primäre DNS-Adresse"
,"Sekundäre DNS-Adresse"
,"LAN IPv6-Adresseneinstellungen"
,"LAN IPv6-Adresse"
,"LAN IPv6 Link-Local-Adresse"
,"Adressen-Autokonfigurationseinstellungen"
,"Autokonfiguration"
,"Autokonfigurationstyp"
,"Router Advertisement Lifetime"
,"Ferne IPv4-Adresse"
,"Lokale IPv4-Adresse"
,"Lokale IPv6-Adresse"
,"IPv6 Setup"
,"IPv6-Verbindung"
,"Zustandslos"
,"Zustandsbehaftet (DHCPv6)"
,"In diesem Abschnitt können Sie die internen Netzwerkeinstellungen Ihres Routers konfigurieren. Die LAN IPv6 Link-Local-Adresse wird auch für den Zugriff auf die webbasierte Verwaltungsschnittstelle genutzt. Wenn Sie die LAN IPv6-Adresse hier ändern, müssen Sie Ihre PC-Netzwerkeinstellungen möglicherweise anpassen, um wieder auf das Netzwerk zugreifen zu können."
,"DHCP-PD aktivieren"
,"Einstellungen für die LAN-Adressen-Autokonfiguration"
,"In diesem Abschnitt können Sie die IPv6-Autokonfiguration einrichten und den Computern in Ihrem Netzwerk IP-Adressen zuweisen."
,"Autokonfiguration aktivieren"
,"SLAAC + Zustandslose DHCPv6"
,"LAN IPv6 Link-Local-Adresse"
,"In diesem Abschnitt können Sie Ihren IPv6-Verbindungstyp konfigurieren. Wenn Sie nicht sicher sind, welche Verbindungsmethode Sie verwenden sollen, wenden Sie sich bitte an Ihren Internetdienstanbieter."
,"Wenn Sie den Router für den Zugang zum IPv6-Internet konfigurieren, wählen Sie im Dropdown-Menü unbedingt den korrekten IPv6-Internet-Verbindungstyp. Wenn Sie nicht sicher ist, welche Option Sie wählen sollen, wenden Sie sich an Ihren Internetdienstanbieter."
,"Wählen Sie den Modus, den der Router für die Verbindung mit dem IPv6-Internet verwenden soll."
,"Autokonfiguration (SLAAC/DHCPv6)"
,"IPv6 over IPv4 Tunnel"
,"6rd"
,"Nur Link-Local"
,"IPv6-Verbindungsdaten"
,"IPv6-Verbindungstyp"
,"Netzwerkstatus"
,"WAN IPv6-Adresse"
,"IPv6 Standard-Gateway"
,"Primärer IPv6 DNS-Server"
,"Sekundärer IPv6 DNS-Server"
,"LAN IPv6 Link-Local-Adresse"
,"DHCP-PD"
,"Von DHCP-PD zugewiesenes IPv6-Netzwerk"
,"LAN IPv6-Adresse"
,"IPv6-Adresse"
,"Name (sofern zutreffend)"
,"Statische IPv6"
,"DHCPv6"
,"6 to 4"
,"PPPoA"
,"*Verbindungsschaltfläche für IPv4 und IPv6"
,"*Schaltfläche zur Trennung der Verbindung für IPv4 und IPv6"
,"Globale IPv6 Adresse"
,"WAN IPv6-Adresseneinstellungen"
,"Subnetzmasken-Präfixlänge"
,"PPPoE- oder PPPoA-Einstellungen"
,"IPv6 over IPv4 Tunneleinstellungen"
,"Ferne IPv6-Adresse"
,"IPv6 DNS-Einstellungen"
,"DNS-Einstellung"
,"DNS-Serveradresse automatisch beziehen"
,"Folgende DNS-Adresse verwenden"
,"6rd-Einstellungen"
,"IPv4-Maskenlänge"
,"Fernes Präfix"
,"Präfixlänge"
,"IPv6-Adressbereich (Start)"
,"IPv6-Adressbereich (Ende)"
,"IPv6-Adresse Lifetime"
,"DS-Lite aktivieren"
,"DS-Lite-Konfiguration"
,"DS-Lite DHCPv6 Option"
,"Manuelle Konfiguration"
,"WAN Link-local-Adresse"
,"Dynamische IPv6"
,"IPv6-Passthrough"
,"Ihre IPv4 WAN-Adresse ist keine globale Adresse."
,"WAN IPv6 Address Status"
)

//---------------------------------WiFi---------------------------------
wpa=new Array(
 "Einstellungen für drahtloses Netzwerk"
,"Drahtlos aktivieren"
,"Drahtloser Netzwerkname"
,"(Auch SSID genannt)"
,"802.11-Modus"
,"B/G Mischmodus"
,"N-Modus"
,"B/G/N Mischmodus"
,"Automatische Kanalsuche"
,"Drahtloser Kanal (Funkkanal)"
," GHz - CH "
,"Sichtbarkeitsstatus"
,"Sichtbar"
,"Unsichtbar"
,"Drahtlos-Sicherheitsmodus"
,"Sicherheitsmodus"
,"Keine"
,"WEP"
,"WPA-Personal"
,"WPA-Enterprise"
,"WEP"
,"WEP ist der Wireless-Verschlüsselungsstandard. Um ihn zu verwenden, müssen Sie auf dem Router und auf den Wireless-Stationen dieselben Schlüssel eingeben. Für 64-Bit-Schlüssel müssen Sie 10 Hexadezimalzeichen in jedes Schlüsselfeld eingeben. Für 128-Bit-Schlüssel müssen Sie 26 Hexadezimalzeichen in jedes Schlüsselfeld eingeben. Ein Hexadezimalzeichen ist entweder eine Zahl zwischen 0 und 9 oder ein Buchstabe von A bis F. Um die höchste Sicherheit bei der Verwendung von WEP zu erreichen, setzen Sie den Authentifizierungstyp auf &quot;Shared Key&quot;, wenn WEP aktiviert ist."
,"Sie können auch eine beliebige Textzeichenfolge in ein WEP-Schlüsselfeld eingeben. Diese wird anschließend mithilfe der ASCII-Werte der einzelnen Zeichen in einen Hexadezimalschlüssel umgewandelt. Für 64-Bit-Schlüssel können höchstens 5 Textzeichen, für 128-Bit-Schlüssel höchstens 13 Zeichen eingegeben werden."
,"Authentifizierung"
,"Offen"
,"Freigegeben"
,"WEP-Verschlüsselung"
,"64Bit"
,"128Bit"
,"WEP-Standardschlüssel"
,"WEP-Schlüssel 1"
,"WEP-Schlüssel 2"
,"WEP-Schlüssel 3"
,"WEP-Schlüssel 4"
,"WEP-Schlüssel"
,"HEX"
,"ASCII"
,"WPA"
,"Verwenden Sie den Modus <B>WPA oder WPA2</b>, um ein ausgewogenes Verhältnis zwischen hoher Sicherheit und optimaler Kompatibilität zu erreichen. Dieser Modus verwendet WPA für Altsystem-Clients und gewährleistet höhere Sicherheit bei WPA2-fähigen Stationen. Zudem wird der wirksamste vom Client unterstützte Verschlüsselungstyp verwendet. Wenn Sie größtmögliche Sicherheit erreichen möchten, wählen Sie den Modus <B>Nur WPA2</B>. Dieser Modus nutzt den Verschlüsselungstyp AES (CCMP). Altsystemstationen erhalten mit dem WPA-Sicherheitsmodus keinen Zugang. Wählen Sie <B>Nur WPA</B> für eine bestmögliche Kompatibilität. Dieser Modus nutzt den TKIP-Verschlüsselungstyp. Manche Spiele- und Altsystemgeräte funktionieren nur in diesem Modus.<BR><BR>	Verwenden Sie für eine bessere Wireless-Leistung den Sicherheitsmodus <B>Nur WPA2</b> (d. h. die AES-Verschlüsselung)."
,"WPA-Modus"
,"Nur WPA2"
,"Nur WPA"
,"Verschlüsselungstyp"
,"TKIP"
,"AES"
,"Pre-Shared Key"
,"Geben Sie einen aus 8 bis 63 Zeichen bestehende Passphrase (Kennsatz oder Kennwortsatz) ein. Zur Gewährleistung höchster Sicherheit sollte dieser ausreichend lang sein und kein allgemein bekannter oder gebräuchlicher Ausdruck oder Satz sein."
,"Netzwerkschlüssel"
,"(8~63 ASCII oder 64 HEX)"
,"EAP (802.1x)"
,"Wenn WPA-Enterprise aktiviert ist, verwendet der Router EAP (802.1x), um Clients über einen Remote-RADIUS-Server zu authentifizieren."
,"IP-Adresse des RADIUS-Servers"
,"RADIUS-Server-Port"
,"RADIUS-Server-\"Shared Secret\""
,"(13 ASCII oder 26 HEX)"
,"(5 ASCII oder 10 HEX)"
,"Die Einstellungen werden nach einem Neustart wirksam."
,"Möchten Sie das wirklich ändern?"
,"WiFi-Einstellung"
,"In diesem Abschnitt können Sie die Wireless-Schnittstelle (den Zugangspunkt) konfigurieren, der am Router zur Verfügung steht."
,"2.4 GHz Band"
,"5GHz Band"
,"Funkfrequenzband"
,"Automatische Kanalsuche aktivieren"
,"Kanalbreite"
,"20/40 MHz (Auto)"
,"20/40/80 MHz (Auto)"
,"Nur 802.11b"
,"Nur 802.11.g"
,"Nur 802.11n"
,"802.11g und 802.11b gemischt"
,"802.11n und 802.11g gemischt"
,"802.11n, 802.11g und 802.11b gemischt"
,"Nur 802.11a"
,"Nur 802.11n"
,"802.11a und 802.11n gemischt"
,"802.11 a/n/ac gemischt"
,"(Länge gilt für alle Schlüssel)"
,"Länge des WEP-Schlüssels"
,"Warnhinweis! Das Einstellen des Sicherheitsmodus für das 2,4 GHz Band auf \"KEINEN\" führt zu Sicherheitsrisiken. Möchten Sie die Einstellung trotzdem konfigurieren?"
,"Die WPS-Funktion muss gestoppt werden, damit die WEP-Einstellung für das 2,4 GHz Band aktiviert werden kann. Möchten Sie die Einstellung trotzdem konfigurieren?"
,"Warnhinweis! Das Einstellen des Sicherheitsmodus für das 5 GHz Band auf \"KEINEN\" führt zu Sicherheitsrisiken. Möchten Sie die Einstellung trotzdem konfigurieren?"
,"Die WPS-Funktion muss gestoppt werden, damit die WEP-Einstellung für das 5GHz Band aktiviert werden kann. Möchten Sie die Einstellung trotzdem konfigurieren?"
,"64Bit (10 Hexadezimalzeichen)"
,"128Bit (26 Hexadezimalzeichen)"
,"Warnhinweis! Das Einstellen des Sicherheitsmodus für das 2,4 GHz Band auf \"KEINEN\" führt zu Sicherheitsrisiken. Möchten Sie die Einstellung trotzdem konfigurieren?"
,"Warnhinweis! Das Einstellen des Sicherheitsmodus für das 5GHz Band auf \"KEINEN\" führt zu Sicherheitsrisiken. Möchten Sie die Einstellung trotzdem konfigurieren?"
,"Die WPS-Funktion muss gestoppt werden, damit die WEP-Einstellung für das 2,4 GHz Band aktiviert werden kann. Möchten Sie die Einstellung trotzdem konfigurieren?"
,"Die WPS-Funktion muss gestoppt werden, damit die WEP-Einstellung für das 5GHz Band aktiviert werden kann. Möchten Sie die Einstellung trotzdem konfigurieren?"
,"Auto (WPA oder WPA2)"
)

wps=new Array(
 "UNKONFIGURIERT"
,"Einrichten"
,"KONFIGURIERT"
,"Freigabe"
,"NOUSED"
,"IDLE"
,"PROCESSFAIL"
,"STARTPROCESS"
,"RECVEAPOLSTART"
,"SENDEAPREQID"
,"RECVEAPRSPID"
,"RECVWRGVENDORID"
,"RECVWRGVENDORTYPE"
,"SENDEAPREQSTART"
,"SENDM1"
,"RECVM1"
,"SENDM2"
,"RECVM2"
,"RECVM2D"
,"SENDM3"
,"RECVM3"
,"SENDM4"
,"RECVM4"
,"SENDM5"
,"RECVM5"
,"SENDM6"
,"RECVM6"
,"SENDM7"
,"RECVM7"
,"SENDM8"
,"RECVM8"
,"PROCEAPRSPACK"
,"PROCEAPREQDONE"
,"PROCEAPRSPDONE"
,"SENDEAPFAIL"
,"ERRHASHFAIL"
,"ERRHMACFAIL"
,"ERRDEVPWDAUTHFAIL"
,"KONFIGURIERT"
,"WPS (Wi-Fi Protected Setup)"
,"WPS"
,"AP PIN"
,"Neue PIN generieren"
,"Konfig.-Modus"
,"Antragsteller"
,"Registrar"
,"Konfig.-Status"
,"Konfig.-Methode"
,"PIN"
,"Konfiguration per Knopfdruck"
,"WPS-Status"
,"Auslöser"
,"Wird gelesen..."
,"Wi-Fi Protected Setup (WPS)"
,"WPS ist ein Standard zum einfachen und sicheren Aufbau eines drahtlosen Netzwerks. In diesem Bereich können Sie WPS für eine Client-Verbindung aktivieren, die die WPA/WPA2 Sicherheit verwendet."
,"PIN-Länge muss = 4 oder 8 sein"
,"PIN-Regelfehler!"
,"WPS-PIN-Methode deaktivieren"
,"PIN-Länge muss = 4 oder 8 sein"
,"PIN-Regelfehler!"
)

wlpfe=new Array(
 "Erweiterte drahtlose Einstellungen"
,"Beacon-Intervall"
,"(msek, Bereich: 10~1024"
,"Übertragungsleistung"
,"RTS-Schwellenwert"
,"(1~2347,Standard 2347)"
,"Fragmentierung"
,"(256~2346,Standard 2346)"
,"DTIM-Intervall"
,"(Bereich: 1~255)"
,"WMM-fähig"
,"TX-Raten"
,"Geben Sie auf dieser Seite erweiterte Konfigurationseinstellungen für den Funkbetrieb an. Bei Bedarf können die Standardwerte für AP Security und Association-Parameter verändert werden."
,"Erweiterte 2,4 G Wireless Einstellungen"
,"Erweiterte 5 G Wireless Einstellungen"
,"Kurzes GI"
,"HT 20/40 Koexistenz"
)

//---------------------------------LAN---------------------------------
devlist=new Array(
 "LAN Clients-Liste"
,"Hostname (sofern zutreffend)"
,"IP-Adresse"
,"MAC-Adresse"
)

lanst=new Array(
 "Routereinstellungen"
,"In diesem Abschnitt können Sie die internen Netzwerkeinstellungen Ihres Routers konfigurieren. Die IP-Adresse, die hier konfiguriert wird, wird ebenfalls für den Zugriff auf die webbasierte Verwaltungsschnittstelle genutzt. Wenn Sie die IP-Adresse hier ändern, müssen Sie Ihre PC-Netzwerkeinstellungen anpassen, um wieder auf das Netzwerk zugreifen zu können."
,"IP-Adresse des Routers"
,"Standard-Subnetzmaske"
,"Lokaler Domänenname"
,"DHCP-Servereinstellungen"
,"In diesem Abschnitt können Sie den integrierten DHCP-Server einrichten und den Computern in Ihrem Netzwerk IP-Adressen zuweisen."
,"DHCP-Server aktivieren"
,"DHCP-IP-Adressbereich"
,"bis"
,"(Adressen innerhalb des LAN-Subnetzes)"
,"DHCP-Lease-Zeit"
,"Primäre DNS-IP-Adresse"
,"Sekundäre DNS-IP-Adresse"
,"Primäre WINS IP-Adresse"
,"Sekundäre WINS IP-Adresse"
,"LAN-IP-Adresseneinstellung wird nach Neustart wirksam."
,"Möchten Sie das wirklich ändern?"
,"IP-Pool-Bereich ist ungültig."
,"IP-Pool-Startadresse"
,"IP-Pool-Endadresse"
,"Der lokale Domain-Name ist ungültig"
,"In diesem Abschnitt können Sie die lokalen Netzwerkeinstellungen Ihres Routers konfigurieren. Beachten Sie, dass dieser Abschnitt optional ist und Sie keine dieser Einstellungen ändern müssen, um Ihr Netzwerk in Betrieb zu nehmen."
,"IP-Interface Konfiguration"
,"DHCP-Server"
,"DHCP-Serverkonfiguration"
,"DHCP Reservation"
)

//---------------------------------Advanced---------------------------------
ddns=new Array(
 "Dynamischer DNS (DDNS)"
,"DDNS aktivieren"
,"Anbieter"
,"DynDNS.org(Dynamic)"
,"DynDNS.org (Benutzerdef.)"
,"No-IP.com"
,"TZO.com"
,"dhs.org"
,"Host-Name"
,"Benutzername / E-Mail"
,"Kennwort / Schlüssel"
,"Die Auflösung der IP-Adresse in Hostnamen/Domains und umgekehrt wird über den DNS verwaltet. Die erforderlichen Informationen (IP-Adresse mindestens eines DNS-Servers) erhalten SIe in der Regel von Ihrem ISP. Das Gerät ist jedoch auch in der Lage, die verfügbaren DNS-Server automatisch zu erkennen."
)

spap=new Array(
 "Beliebte Anwendungen"
,"-- Eine auswählen --"
,"Battle.net"
,"Dialpad"
,"ICU II"
,"MSN Gaming Zone"
,"PC-to-Phone"
,"Quick Time 4"
,"Anwendungsregeln"
,"Auslöser"
,"Eingangs-Ports"
,"Anwendung"
,"Der Service-Port des virtuellen Servers und der Eingangsport für Anwendungsregeln können nicht identisch sein."
,"Eingehender Port-Wert darf nicht gleich sein."
)

dmz=new Array(
 "Firewall-Einstellungen"
,"SPI aktivieren"
,"DMZ-Host"
,"Mit der Option \"DMZ\" können Sie einen einzelnen Computer in Ihrem Netzwerk außerhalb des Routers platzieren. Wenn Sie einen Computer haben, auf dem Internet-Anwendungen hinter dem Router nicht erfolgreich ausgeführt werden, können Sie den Computer für uneingeschränkten Internet-Zugriff in der DMZ platzieren."
,"<b>Hinweis:</b> Wenn ein Computer der DMZ zugeordnet wird, ist dieser Computer möglicherweise zahlreichen Sicherheitsrisiken ausgesetzt. Diese Option sollte daher nur als letzter Ausweg genutzt werden."
,"DMZ aktivieren"
,"DMZ-IP-Adresse"
,"Computername"
)

smap=new Array(
 "Bekannte Dienste"
,"-- Eine auswählen --"
,"AUTH (113)"
,"DNS (53)"
,"FTP (21)"
,"ISAKMP (500)"
,"POP3 (110)"
,"PPTP (1723)"
,"SMTP (25)"
,"TELNET (23)"
,"WEB (80)"
,"Zeitplanregel verwenden"
,"---IMMER AKTIV---"
,"Virtuelle Serverliste"
,"Service-Ports"
,"Server-IP: Port"
,"Aktivieren"
,"Zeitplanregelnr."
,"Der externen fungiert als Server. Er empfängt unter seiner öffentlichen IP-Adresse Anfragen von Remote-Nutzern und leitet sie automatisch an den virtuellen Server weiter. "
,"Ein Client in Ihrem Netzwerk hinter einem NAT oder einer Firewall kann daher als virtueller Server Dienste bereitstellen. "
,"Sie aktivieren lediglich spezifische Ports oder Portbereiche und Protokolle (UDP/TCP). So sind beispielsweise der gemeinsame Dateizugriff oder Webdienste für HTTP, FTP oder POP3 möglich. Die privaten IP-Adressen der Server im lokalen Netzwerk bleiben sicher. Wenn Sie eine dynamische IP-Adresse verwenden, müssen Sie möglicherweise zusätzlich DynDNS aktivieren."
,"Service-Port-Wert darf nicht gleich sein."
,"Einstellungsfehler"
)

uctl=new Array(
 "URL-Filterungseinstellung"
,"URL-Filterung"
,"Aktivieren"
,"URL-Filterungsregeln"
,"URL"
,"Aktivieren"
,"URL muss angegeben werden"
,"http://' ist nicht zulässig!"
,"URL-Filter sind nützliche Tools zur Einschränkung des Internetzugangs. "
,"Die Option des Blockierens von Website-URLs ermöglicht Ihnen die schnelle Erstellung von Listen aller Websites, deren Zugriff für Benutzer erlaubt oder verweigert werden soll."
,"URL Filter"
)

rtab=new Array(
 "RIP-Einstellung"
,"RIP"
,"Aktivieren"
,"RIPv1"
,"RIPv2"
,"Routing-Regel"
,"Ziel"
,"Subnetzmaske"
,"Gateway"
,"Hop"
,"Die Routen für den Traffic in Ihrem Netzwerk werden über die Routing-Tabelle definiert. Normalerweise reicht das Eingeben der IP-Adresse und des Gateway aus. Sie brauchen keine weiteren Einstellungen zu definieren."
)

qos=new Array(
 "Hoch"
,"Normal"
,"Niedrig"
,"QoS-Engine-Setup"
,"QoS-Paketplaner aktivieren"
,"Upstream-Bandbreite"
,"Downstream-Bandbreite"
,"KBit/s"
,"Zeitplanregel verwenden"
,"---IMMER AKTIV---"
,"QoS-Regeln"
,"Local IP (Lokale IP-Adr.): Ports"
,"Remote IP : Ports"
,"QoS-Priorität"
,"Aktivieren"
,"Regelnr. verwenden"
,"QoS-Engine-Setup"
)

pmac=new Array(
 "MAC-Filterungseinstellungen"
,"MAC-Adressensteuerung"
,"Aktivieren"
,"Connection control (Verbindungssteuerung)"
,"Drahtlose und kabelgebundene Clients (bei entspr. Markierung der Connection control <b>C</b> können eine Verbindung zu diesem Gerät herstellen und können "
,"erlauben"
,"verweigern"
," unspezifizierte MAC-Adressen zu verbinden."
,"Association control"
,"Sie können drahtlosen Clients (bei entspr. Markierung der Association control <b>A</b> ) "
,"erlauben"
,"verweigern"
," dass unspezifizierte MAC-Adressen auf das LAN zugreifen."
,"DHCP-Clients"
,"-- Eine auswählen --"
,"Regeln für MAC-Filterung"
,"MAC-Adresse"
,"IP-Adresse"
,"C"
,"A"
)

iopf=new Array(
 "Ausgangsfilter-Einstellung"
,"Eingangsfilter-Einstellung"
,"Ausgangsfilter"
,"Eingangsfilter"
,"Aktivieren"
,"Zeitplanregel verwenden"
,"---IMMER AKTIV---"
,"Ausgangsfilter-Regelliste"
,"Eingangsfilter-Regelliste"
,"Alle passieren lassen, außer jene, die den folgenden Regeln entsprechen."
,"Alle ablehnen, außer jene, die den folgenden Regeln entsprechen."
,"Quell-IP:Ports"
,"Ziel-IP:Ports"
,"Aktivieren"
,"Zeitplanregelnr."
,"Regelnummerfehler verwenden!"
)

snmp=new Array(
 "SNMP"
,"SNMP Lokal"
,"SNMP Remote"
,"Get Community"
,"Set Community"
,"IP 1"
,"IP 2"
,"IP 3"
,"IP 4"
,"SNMP-Version"
,"V1"
,"V2c"
,"WAN-Zugriff IP-Adresse"
)

fmisc=new Array(
 "UPnP"
,"UPnP (Universal Plug and Play) unterstützt die Peer-to-Peer-Plug&Play-Funktionalität für Geräte im Netzwerk."
,"UPnP aktivieren"
,"WAN PING"
,"Wenn Sie diese Funktion aktivieren, reagiert der WAN-Port Ihres Routers auf Ping-Anfragen aus dem Internet, die an die WAN-IP-Adresse gesendet werden."
,"WAN-Ping-Antwort aktivieren"
)

networkscan=new Array(
 "Auswahl Netzwerkanbieter"
,"Diese Seite sucht nach Netzwerkanbietern in der Nähe. <br>Bitte waren Sie kurz, bis die Suche jeweils beendet ist."
,"3G/4G Network Selection Method (3G/4G-Netzauswahlmethode)"
,"Läuft..."
,"Liste der Netzwerkanbieter"
,"Es steht kein Netzwerkanbieter zur Verfügung"
,"Wenn Sie keinen Netzwerkanbieter auswählen, wird der Modus zu Automatisch geändert"
,"Ihre Änderungen wurden gespeichert. Damit die neuen Einstellungen übernommen werden können, müssen Sie den Router neu starten."
,"Sie können jetzt einen Neustart durchführen oder weitere Änderungen vornehmen und den Neustart später durchführen."
,"Verfügbar"
,"Aktuell"
,"Nicht zulässig"
,"Suchen"
,"Network Selection Method"
)

//---------------------------------System---------------------------------
sntp=new Array(
 "Uhrzeit und Datum konfigurieren"
,"Zeit"
,"Zeitzone"
,"Sommer-/Winterzeit aktivieren"
,"Mit Zeiteinstellungen Ihres Computers synchronisieren"
,"Uhrzeit und Datum automatisch konfigurieren"
,"Automatisch mit Internet-Zeitserver synchronisieren"
,"Verwendeter NTP-Server"
,"Jetzt aktualisieren"
,"Sync. ERGEBNIS"
,"Starten"
,"Ende"
,"Stunde"
,"Tag"
,"Monat"
,"(Stunde/Tag/Monat)"
,"Jan"
,"Feb"
,"Mär"
,"Apr"
,"Mai"
,"Jun"
,"Jul"
,"Aug"
,"Sep"
,"Okt"
,"Nov"
,"Dez"
,"So"
,"Mo"
,"Di"
,"Mi"
,"Do"
,"Fr"
,"Sa"
,"Mit der Option \"Zeitkonfiguration\" können Sie die richtige Zeit der internen Systemuhr konfigurieren, aktualisieren und verwalten."
,"In diesem Abschnitt können Sie Ihre Zeitzone und den NTP-Server (Network Time Protocol / Netzwerkzeitprotokoll) einstellen."
,"Auch die Sommerzeit kann konfiguriert werden, um die Einstellung der Zeit bei Bedarf automatisch anzupassen."
,"Zeit"
,"Zeiteinstellungen"
)

tz=new Array(
 "* Noch nicht konfiguriert! Standard ist GMT +00.00."
,"Internationale Datumsgrenze West"
,"Midway-Inseln, Samoa"
,"Hawaii"
,"Alaska"
,"Pacific Time (USA & Kanada)"
,"Tijuana"
,"Arizona"
,"Chihuahua, La Paz, Mazatlan"
,"Mountain Time (USA & Kanada)"
,"Mittelamerika"
,"Central Time (USA & Kanada)"
,"Guadalajara, Mexiko, Monterrey"
,"Saskatchewan"
,"Bogota, Lima, Quito"
,"Eastern Time (USA &amp; Kanada)"
,"Indiana (Ost)"
,"Atlantic Time (Kanada)"
,"Caracas, La Paz"
,"Santiago"
,"Neufundland"
,"Brasilia"
,"Buenos Aires, Georgetown"
,"Grönland"
,"Mittelatlantik"
,"Azoren"
,"Kapverdische Inseln"
,"Casablanca, Monrovia"
,"Dublin, Edinburgh, Lissabon, London"
,"Amsterdam, Berlin, Bern, Rom, Stockholm, Wien"
,"Belgrad, Bratislava, Budapest, Ljubljana, Prag"
,"Brüssel, Kopenhagen, Madrid, Paris"
,"Sarajevo, Skopje, Warschau, Zagreb"
,"West-Zentralafrika"
,"Athen, Beirut, Istanbul, Minsk"
,"Bukarest"
,"Kairo"
,"Harare, Pretoria"
,"Helsinki, Kiew, Riga, Sofia, Tallinn, Vilnius"
,"Jerusalem (nur 2007)"
,"Bagdad"
,"Kuwait, Riad"
,"Moskau, St. Petersburg, Wolgograd"
,"Nairobi"
,"Teheran"
,"Abu Dhabi, Muskat"
,"Baku"
,"Tiflis"
,"Erewan"
,"Kabul"
,"Jekaterinburg"
,"Islamabad, Karatschi, Taschkent"
,"Chennai, Kalkutta, Mumbai, Neu-Delhi"
,"Kathmandu"
,"Almaty, Nowosibirsk"
,"Astana, Dhaka"
,"Colombo"
,"Rangun"
,"Bangkok, Hanoi, Jakarta"
,"Krasnojarsk"
,"Peking, Chongqing, Hongkong, Urumqi"
,"Irkutsk"
,"Kuala Lumpur, Singapur"
,"Perth, Westaustralien"
,"Taipeh"
,"Ulaan Bataar"
,"Osaka, Sapporo, Tokio"
,"Seoul"
,"Jakutsk"
,"Adelaide"
,"Darwin"
,"Brisbane"
,"Canberra, Melbourne, Sydney"
,"Guam, Port Moresby"
,"Hobart"
,"Wladiwostok"
,"Magadan, Solomoninseln, Neukaledonien"
,"Auckland, Wellington"
,"Fidschi, Kamschatka, Marshall-Inseln"
,"Nuku'alofa"
,"* ZZ-Variable manuell konfigurieren..."
,"Eniwetok, Kwajalein"
,"Mexiko-Stadt, Tegucigalpa"
,"Brüssel, Kopenhagen, Madrid, Paris, Vilnius"
,"Sarajevo, Skopje, Sofia, Warschau, Zagreb"
,"Athen, Beirut, Kairo, Istanbul, Minsk"
,"Beijing, Hongkong, Taipeh"
,"Indien"
)

atbox=new Array(
 "Administrator (der Standard-Anmeldename ist "
,")"
,"Anmeldename"
,"Neues Kennwort"
,"Kennwort bestätigen"
,"Fernverwaltung"
,"Remote-Management aktivieren"
,"IP zum Zugriff freigegeben"
,"Port"
,"Die neuen Administratorkennwörter sind nicht identisch!"
,"Möchten Sie als Kennwort ein leeres Kennwort speichern?"
,"Der Fernverwaltungs-Port sollte größer als 1024 sein."
,"Administrator"
,"Hier können Sie das Kennwort für den Administrator ändern."
,"Das Benutzernamenfeld (admin) kann nicht geändert werden."
,"Administratoreinstellungen"
,"SSH"
,"SSH aktivieren"
,"WAN zulassen"
,"Telnet"
,"Telnet aktivieren"
,"Remote Administration"
)

rebo=new Array(
 "Upgrade erfolgreich!"
,"Ungültige Upgrade-Datei."
,"Vergewissern Sie sich, dass das die korrekte Datei ist."
,"Die Datei ist mit der aktuellen Firmware oder Hardware nicht kompatibel."
,"Ein Upgrade auf diese Version ist nicht zulässig."
,"Upgrade wurde aus unbekannten Gründen abgebrochen."
,"Versuchen Sie es bitte noch einmal."
,"Alle Einstellungen werden zurückgesetzt."
,"Das Gerät wird neu gestartet..."
,"<font color=red><b>SCHALTEN SIE DAS GERÄT BITTE NICHT AUS</b></font>."
,"Und warten Sie bitte "
," ein paar Sekunden..."
,"Verbindung bitte manuell erneut herstellen."
,"Hinweis: Ihre LAN IP hat sich möglicherweise geändert. Bitte Verbindung erneut herstellen."
,"Hier zur Herstellung einer erneuten Verbindung klicken"
,"System ist betriebsbereit"
,"Router neu starten"
,"Statusmeldung"
,"Router wird aktiv in"
,"Jetzt neu starten"
,"Später neu starten"
)

system=new Array(
 "Alle Einstellungen auf Standard zurücksetzen?"
,"Einstellungen speichern und wiederherstellen"
,"Einstellungen auf der lokalen Festplatte speichern"
,"Speichern"
,"Einstellungen von der lokalen Festplatte laden"
,"Einstellungen hochladen"
,"Auf Werkseinstellungen zurücksetzen"
,"Auf Standard zurücksetzen"
,"Ungültige Upgrade-Datei."
,"Unzulässige Upgrade-Datei."
,"System"
,"Alle Einstellungen werden automatisch auf Ihrem Gerät gespeichert. Sie müssen nicht manuell speichern oder neu starten. Wenn Sie das Gerät dennoch neu starten möchten, ist es besser, die Schaltfläche \"Reboot\" zu verwenden."
,"Systemeinstellungen"
,"Gerät neu starten"
,"Alle Einstellungen auf werkseitige Standardeinstellungen zurücksetzen?"
,"Neu starten"
,"Neustart und Zurücksetzen"
)

fwug=new Array(
 "Firmware-Information"
,"Aktuelle Firmware-Version"
,"Aktuelles Firmware-Datum"
,"Firmware-Upgrade"
,"Hinweis: Gerät nicht während eines Upgrade ausschalten."
,"Der Upgrade-Vorgang dauert etwa 180 Sekunden."
,"Sobald das Upgrade erfolgreich abgeschlossen ist, wird das Gerät automatisch neu gestartet."
,"Damit die Firmware aktualisiert werden kann, muss Ihr PC über eine Kabelverbindung zum Router verfügen. Geben Sie den Namen der Firmware-Aktualisierungsdatei ein und klicken Sie anschließend auf die Schaltfläche \"Hochladen\"."
,"Hochladen"
,"Upgrade"
,"Falscher Dateiname"
,"Es wird nur eine .bin-Datei akzeptiert."
,"Abbrechen"
,"Ein anderes Firmware-Upgrade ist zurzeit im Gange!"
,"Nicht offizielle Firmware akzeptieren."
,"Bitte verwenden Sie die Schaltfläche \"Upgrade\", um die Firmware-Version für Ihr Gerät zu aktualisieren."
,"Firmware-Aktualisierung"
,"Firmware auswählen"
,"Datei prüfen"
,"Neue Firmware-Informationen"
,"Neue Firmware-Version"
,"Neue Firmware Datum"
)

logs=new Array(
 "SysLog-Einstellungen"
,"Protokollieren auf Syslog-Server aktivieren"
,"SysLog-Server-IP-Adresse"
,"E-Mail-Einstellungen"
,"E-Mail-Benachrichtigung aktivieren"
,"SMTP Server-IP und Port"
,"E-Mail-Warnhinweis senden an"
,"E-Mail-Betreff"
,"SMTP-Benutzername"
,"SMTP-Kennwort"
,"E-Mail jetzt protokollieren"
,"Eine E-Mail in der Warteschlange steht zum Senden bereit..."
,"Systemprotokoll"
,"Mit der Funktion \"Systemprotokoll\" können Sie Konfigurationen für lokale, ferne und E-Mail-Protokolle erstellen und die erstellten Protokolle anzeigen."
,"Clear logs"
,"Log Number"
,"Message"
,"View Logs"
)

smsmsg=new Array(
 "Antworten"
,"Nachricht weiterleiten"
,"Nachricht erstellen"
,"Textnachricht"
,"Nachricht eingeben..."
,"Die Nachricht darf maximal 160 Zeichen lang sein."
,"Empfänger"
,"Fügen Sie dem internationalen Format der Telefonnummer ein '+' hinzu."
,"Senden"
,"Wird gelesen... Etwas Geduld bitte..."
,"Aktuelle Textlänge"
,"Nachricht senden"
,"Wenn Sie SMS-Mitteilungen erstellen und senden möchten, klicken Sie auf die Schaltfläche unten."
,"Der Empfänger darf nicht leer sein!"
,"The max. length of a message is 160 characters for pure alphabetical or numeric."
)

smsinbox=new Array(
 "SMS-Status"
,"Erhaltene SMS"
,"Neue SMS"
,"Gesamtkapazität"
,"Posteingang"
,"Von"
,"Zeitstempel"
,"Text"
,"SMS"
,"Wird gelesen... Etwas Geduld bitte..."
,"Antworten"
,"Weiterleiten"
,"SMS-Eingang"
,"Wenn Sie SMS-Mitteilungen anzeigen möchten, klicken Sie auf die Schaltfläche unten."
,"SMSC Einstellung"
,"Bitte überprüfen Sie, ob die SIM-Karte eingelegt ist."
,"SIM-Karte ist gesperrt! SMS kann nicht von der SIM-Karte gelesen werden."
,"Modem nicht bereit!"
,"Das Modem ist durch einen Telefonanruf blockiert! Bitte warten..."
,"Senden OK!"
,"Fehler beim Senden!"
,"Das Modem ist durch einen Telefonanruf blockiert! Die SMS wird später automatisch gesendet."
,"Löschen OK!"
,"Löschvorgang fehlgeschlagen."
,"AT Befehl fehlgeschlagen!"
,"Das Modem ist durch einen Telefonanruf blockiert! Die SMS wird später automatisch gelöscht."
)

voiceforwd=new Array(
 "Alle Anrufe"
,"Keine Antwort"
,"Nicht erreichbar"
,"Besetzt"
,"Status"
,"Registrierung aufheben"
,"Registrieren"
,"Aktivieren"
,"Deaktivieren"
,"Nummer"
)

pinco=new Array(
 "Abfragestatus... Etwas Geduld bitte..."
,"SIM PIN-Code"
,"Geben Sie 4~8 Zeichen im Feld SIM PIN-Code ein."
,"Funktion PIN-CODE Anforderung"
,"SIM PIN-Code eingeben"
,"PIN-Code ändern..."
,"Erfolgreich!"
,"Geben Sie 4~8 Zeichen im Feld alter PIN-Code ein."
,"Geben Sie 4~8 Zeichen im Feld neuer PIN-Code ein."
,"Geben Sie 4~8 Zeichen im Feld PIN-Code bestätigen ein."
,"Funktion PIN-CODE Ändern"
,"Alter PIN-Code"
,"Neuer PIN-Code"
,"PIN-Code bestätigen"
,"Speichern!"
,"Bitte geben Sie den PIN-Code ein, um die SIM-Karte zu entsperren"
,"PIN-CODE"
,"Bitte geben Sie den PUK-Code ein, um die SIM-Karte zu entsperren"
,"PUK-CODE"
,"Neuer PIN-CODE"
,"Die Funktion ist bereits deaktiviert!"
,"Die Funktion ist bereits aktiviert!"
,"PIN-Code falsch!"
,"Sie müssen erst die Funktion PIN-Code Anforderung aktivieren!"
,"Sie haben zwei unterschiedliche neue PIN-Codes eingegeben!"
,"Alter PIN-Code falsch!"
,"PUK-Code falsch!"
,"AT Befehl fehlgeschlagen!"
,"Bereit"
,"Durch SIM PIN gesperrt."
,"Durch SIM PUK gesperrt."
,"SIM-Karte fehlerhaft."
,"Das Modem reagiert nicht."
,"Senden des AT-Befehls fehlgeschlagen!"
,"Modem existiert nicht! Bitte überprüfen Sie, ob die SIM-Karte eingesetzt ist!"
,"Warnung: Nur noch 3 Versuche zulässig."
,"Wiederholen"
,"Weiter"
,"Warnung: "
," weitere Versuche zulässig."
,"Geben Sie 4~8 Zeichen im Feld PIN-CODE ein."
,"Geben Sie 8 Zeichen im Feld PUK-CODE ein."
,"PIN-Kontrolle"
,"Das Modem wird initialisiert, bitte kurz warten!"
,"PIN-Konfiguration"
,"Stifteinsatz scheitern 3 mal! Bitte geben Sie den PUK-Code."
)

ussd=new Array(
 "USSD"
,"Senden"
,"FEHLER"
)

scherebo=new Array(
 "Rücksetzen der Verbindung"
,"Auto-Reboot (Autom. Neustart)"
,"Reboot-Schedule (Neustart zeitlich einplanen)"
,"Täglicher Zeitplan"
,"Weekly Schedule Day of Week (Zeitplan wöchentlich/Wochentag)"
,"Monatsdatum"
)

sche=new Array(
 "Zeitplanregel"
,"Zeitplan aktivieren"
,"Regelnr."
,"Regelname"
,"Aktion"
,"Keine Regel hinzugefügt. Vor Aktivierung bitte Regel hinzufügen."
,"Regel wirklich löschen? "
,"??"
,"Schedule"
)

rule=new Array(
 "Der Regelname muss angegeben werden."
,"Name des Zeitplans ist Duplikat anderer Regel."
,"(Regel:"
,")"
,"Bitte noch einmal prüfen."
,"Startzeit des Wochentags "
," ist ungültig."
,"Endzeit des Wochentags "
," ist ungültig."
,"Zeit des Wochentags "
," ist ungültig."
,"Endzeit muss nach Startzeit liegen"
,"(Zeitplanformat sollte hh:mm sein)"
,"(0 < Die Stunden der Startzeit < 23 )"
,"(0 < Die Minuten der Startzeit < 59 )"
,"(0 < Die Stunden der Endzeit < 23 )"
,"(0 < Die Minuten der Endzeit < 59 )"
,"Bitte Wochentag in Regelkennung wählen "
,"!!"
,"Die Zeit der Zeitplanregel ist nicht angegeben."
," Geben Sie mindestens einen Zeitplan ein."
,"Jeden Tag"
,"Sonntag"
,"Montag"
,"Dienstag"
,"Mittwoch"
,"Donnerstag"
,"Freitag"
,"Samstag"
,"Zeitplanregel-Einstellung"
,"Name der Regel"
,"-- Eine(n) auswählen --"
,"Richtlinie"
,"Zurück"
,"Deaktivieren"
,"Aktivieren"
,"außer die unten ausgewählten Tage und Stunden."
,"Wochentag"
,"Startzeit (hh:mm)"
,"Endzeit (hh:mm)"
)

diagnostic=new Array(
 "Dienstinformationen"
,"Betreiber"
,"Cell Broadcast"
,"MCC"
,"MNC"
,"LAC"
,"Diensttyp"
,"Modus Dienst bevorzugt"
,"Nur GSM"
,"Nur WCDMA"
,"Unbekannt"
,"PS Attach (DATEN)"
,"CS Attach (SPRACHE)"
,"IMSI"
,"SMSC"
,"Angehängt"
,"Entfernt"
,"SIM-Status"
,"PIN-Code-Sperre"
,"PIN-Code Wiederholungen"
,"PUK-Code Wiederholungen"
,"Modulstatus"
,"IMEI"
,"FW-Version"
,"Modulname"
,"Funkzellen-ID"
)

voice=new Array(
 "Sprache"
,"Anrufweiterleitung"
,"Leitet eingehende Anrufe unter unterschiedlichen Bedingungen automatisch an eine festgelegte Nummer weiter."
,"Anklopfen"
,"Aktuellen Anruf aussetzen und einen neuen Anruf annehmen können "
,"Zur Anrufweiterleitung"
,"Zum Anklopfen"
)

sms=new Array(
 "Nachricht erstellen"
,"Ermöglicht Ihnen das Erstellen und Versenden einer neuen SMS-Nachricht."
,"Eingang"
,"Ermöglicht Ihnen das Lesen neuer SMS-Nachrichten und das Löschen/Weiterleiten vorhandener Nachrichten."
,"Sie können nur jeweils auf eine Nachricht antworten!"
)

tr069=new Array(
 "TR-069"
,"TR-069 Setting"
,"ACS Setting"
,"ACS URL"
,"ACS UserName"
,"ACS Password"
,"CPE Setting"
,"ConnectionRequest Port"
,"ConnectionRequest UserName"
,"ConnectionRequest Password"
,"Inform Setting"
,"Inform"
,"Interval"
,"Interface"
)
