//English
common_en=new Array(
 "Refresh"
,"Help"
,"Logout"
,"Enable"
,"Disable"
,"Item"
,"Edit"
,"Delete"
,"Back"
,"Auto"
,"Manual"
,"Apply"
,"Reset"
,"Add"
,"seconds"
,"bytes"
,"ID"
,"Copy to"
,"Previous page"
,"Next page"
,"Add New Rule..."
,"Best"
,"minutes"
,"Enabled"
,"Disabled"
,"First Page"
,"Last Page"
,"Download"
,"Page"
)

others_en=new Array(
 "Reboot"
,"Reboot Router?"
,"You have logged out"
,"Product Page"
,"Firmware Version"
,"copyright"
,"Helpful Hints.."
,"More..."
,"Save Settings"
,"Don't Save Settings"
,"No change"
,"No change!!"
,"Continue"
,"Settings Saved!"
,"The change takes effective immediately!"
,"Setting completed"
,"System is processing, please wait a few seconds ..."
,"ROUTER"
,"Username"
,"Password"
,"Login"
,"Invalid username or password"
,"Please enter a valid user name."
,"Invalid username or password"
,"You have successfully logged out."
,"You have logged out."
,"Please log in first!"
,"Please enter a valid user name"
,"Please enter a valid password"
,"Please input the User Name."
,"Input value can't be empty."
,"Please wait a few seconds ..."
,"The account administrator already logined"
,"Do you agree?"
)

dirary0_en=new Array(
 "Home"
,"Internet"
,"Wi-Fi"
,"LAN"
,"Advanced"
,"System"
,"WAN Service"
,"Failover"
,"IPv6"
,"Device List"
,"Wi-Fi Settings"
,"WPS"
,"Wi-Fi Advanced"
,"LAN Settings"
,"DHCP"
,"DNS"
,"Applications"
,"DMZ"
,"Virtual Server"
,"URL Filter"
,"Routing"
,"QOS"
,"MAC Address Filter"
,"Outbound Filter"
,"Inbound Filter"
,"SNMP"
,"Advanced Network"
,"Time Settings"
,"Administration"
,"Reboot & Reset"
,"Firmware Upgrade"
,"System Logs"
,"Schedules"
,"Wizard"
,"Network Scan"
,"Connection Reset"
,"PIN Configuration"
,"Message Service"
,"SMS Inbox"
,"Create Message"
,"Voice"
,"Call Forwarding"
,"Call Waiting"
,"Diagnostic"
,"TR-069"
,"Multi-WAN"
)

valchk_en=new Array(
 "Please check the settings again!!"
,"IP address is invalid."
,"Subnet mask is invalid."
,"IP address range is invalid."
,"LAN IP address is invalid."
,"value is invalid."
,"Port is invalid."
,"(Format eg. 1-65535,777)"
,"Port range is invalid. (Format eg. 1-65535)"
,"MTU is invalid!"
,"Hour is invalid."
,"Time is invalid."
,"MAC address is invalid."
,"WEP key is invalid."
,"Preshare key is invalid."
,"Email is invalid."
,"Please input 10 or 26 hexadecimal digits in WEP Key field!!"
,"Please input 5 or 13 ASCII characters in WEP Key field!!"
,"Please input 64 hexadecimal digits or 8~63 ASCII character in Preshare Key field!!"
,"Please input 64 hexadecimal digits in Preshare Key field!!"
," is invalid!"
)

//---------------------------------status---------------------------------
sta_en=new Array(
 "General"
,"Time"
,"Firmware Version"
,"WAN"
,"Connection Type"
,"Static IP"
,"MAC Address"
,"IP Address"
,"Subnet Mask"
,"Default Gateway"
,"DNS Server"
,"DHCP Client"
,"Network Status"
,"Client Disconnected"
,"Connecting..."
,"Established"
,"Disconnecting..."
,"Wait for traffic..."
,"Remaining Lease Time"
,"Renew"
,"Release"
,"PPPoE"
,"Disconnected"
,"Connection Time"
,"Connect"
,"Disconnect"
,"Reconnect"
,"PPTP"
,"L2TP"
,"4G LTE /3G"
,"Signal Strength"
,"Card Info"
,"Link Status"
,"Auth. failure"
,"PIN is required"
,"Password error"
,"No Modem Detected"
,"Unable to connect! Please check your settings and try again."
,"Network Name"
,"LAN"
,"DHCP Server"
,"Wireless LAN"
,"Wireless"
,"SSID"
,"Security"
,"Open"
,"Shared"
,"Auto"
,"WPA-PSK"
,"WPA"
,"WPA2-PSK"
,"WPA2"
,"WPA-PSK/WPA2-PSK"
,"WPA/WPA2"
,"None"
,"WEP"
,"TKIP"
,"AES"
,"TKIP/AES"
,"Channel"
,"Auto"
,"802.11 Mode"
,"B/G Mixed"
,"N mode"
,"B/G/N Mixed"
,"Wi-Fi Protected Setup"
,"LAN Computers"
,"Name"
,"MAC"
,"Day"
,"Hour"
,"Min"
,"Sec"
,"N/A"
,"3G Failover"
,"3G Card"
,"Internet"
,"SSID2"
,"Total Clients"
,"DHCP Pool"
,"System Name"
,"System Uptime"
,"HW Version"
,"SW Version"
,"Failover"
,"Loadsharing"
,"Service Type"
,"Phone"
,"No Service"
,"Status"
)

//---------------------------------Internet---------------------------------
prim_en=new Array(
 "Internet Connection Type"
,"My Internet Connection is"
,"Static IP"
,"Dynamic IP (DHCP)"
,"PPPoE (Username / Password)"
,"PPTP (Username / Password)"
,"L2TP (Username / Password)"
,"4G LTE /3G"
,"Auto-Backup"
,"Enable checking wired-WAN alive"
,"Internet host"
,"Please input an IP address on the internet."
,"Static IP Address Internet Connection Type"
,"IP Address"
,"Subnet Mask"
,"Default Gateway"
,"Primary DNS Server"
,"Secondary DNS Server"
,"MTU"
,"(bytes) MTU default = 1500"
,"MAC Address"
,"Clone"
,"Clear"
,"Dynamic IP (DHCP) Internet Connection Type"
,"Host Name"
,"Auto-reconnect"
,"PPPoE"
,"Username"
,"Password"
,"Verify Password"
,"Service Name"
,"(optional)"
,"IP Address"
,"Maximum Idle Time"
,"(bytes) MTU default = 1492"
,"PPTP"
,"Address Mode"
,"Dynamic IP"
,"Static IP"
,"PPTP IP Address"
,"PPTP Subnet Mask"
,"PPTP Gateway IP Address"
,"PPTP Server IP Address"
,"Reconnect Mode"
,"Always-on"
,"Connect-on-demand"
,"L2TP"
,"L2TP IP Address"
,"L2TP Subnet Mask"
,"L2TP Gateway IP Address"
,"L2TP Server IP Address"
,"4G LTE /3G Internet Connection Type"
,"Account/Profile Name"
,"Dialed Number"
,"Authentication"
,"PAP"
,"CHAP"
,"APN"
,"Pin Code"
,"Keep Alive"
,"Disable"
,"Use Ping"
,"DNS Query"
,"Use LCP Echo Request"
,"lcp-echo-interval"
,"lcp-echo-failure"
,"times"
,"Ping IP Address"
,"Ping Interval"
,"Bridge ethernet ports"
,"MAC address had been changed"
,"New MAC address will take effective after rebooting."
,"Reboot right now?"
,"Roaming"
,"DNS check"
,"NAT disable"
,"Auto Mode"
,"4G Only Mode"
,"3G Only Mode"
,"2G Only Mode"
,"Prefer Service Type"
,"WAN Service Configuration"
,"optional"
,"Transparent Bridge"
,"WAN Interface"
,"Close"
,"Ethernet WAN"
,"Dial-Up Profile"
,"Auto-Detection"
,"Country"
,"Telecom"
,"Network"
,"Others"
,"Network Setup"
,"New passwords are not identical!"
,"setting invalid!"
,"Auto Mode"
,"3G Prefer Mode"
,"2G First Mode"
,"Loading"
,"3G/4G Network"
,"WCDMA/HSPA"
,"CDMA2000/EV-DO"
,"IP Address and Default Gateway is invalid!"
,"Maximum Idle Time rang must between"
,"3G Internet Connection Type"
,"VLAN Tagging"
)

failover_en=new Array(
 "Failover Setting"
,"Failover type"
,"Remote Host for Keep Alive"
,"Failover List"
,"Interface"
,"Change"
,"Current Internet Connection is"
,"Failover Internet Type is"
,"Failover"
,"Failover Connection type"
,"Failover Interface setting"
,"Are you sure to delete secondary WAN?"
,"Auto Backup Setting"
,"Auto Backup"
,"Remote Host for Keep Alive"
,"WAN Connection Lists"
,"Interface"
,"Please change or delete the interface!"
,"Remote Host for Keep Alive can not be Null!"
,"Invalid selection!!"
,"Primary WAN"
,"Secondary WAN"
,"Change WAN type will clean all failover Settings,\nDo you agree?"
,"Load Sharing"
,"Failover Setting..."
,"Load Sharing Connection type"
,"Dynamic IP Address"
,"Static IP Address"
,"Port 1"
,"Port 2"
,"Please select Secondary WAN!"
,"Enable Bridge ethernet ports will disable ethernet WAN."
)

ipv6_en=new Array(
 "6 to 4 Settings"
,"6 to 4 Address"
,"Primary DNS Address"
,"Secondary DNS Address"
,"LAN IPv6 Address Settings"
,"LAN IPv6 Address"
,"LAN IPv6 Link-Local Address"
,"Address Autoconfiguration Settings"
,"Autoconfiguration"
,"Autoconfiguration Type"
,"Router Advertisement Lifetime"
,"Remote IPv4 Address"
,"Local IPv4 Address"
,"Local IPv6 Address"
,"IPv6 Setup"
,"IPv6 Connection"
,"Stateless"
,"Stateful (DHCPv6)"
,"Use the section to configure the internal network settings of your router. The LAN IPv6 Link-Local Address is the IPv6 Address that you use to access the Web-based management interface. If you change the LAN IPv6 Address here,you may need to adjust your PC's network settings to access the network again."
,"Enable DHCP-PD"
,"LAN Address Autoconfiguration Settings"
,"Use this section to setup IPv6 Autoconfigruation to assign IP addresses to the computers on your network."
,"Enable Autoconfiguration"
,"SLAAC+Stateless DHCPv6"
,"LAN IPv6 Link-Local Address"
,"Use this section to configure your IPv6 Connection Type. If you are unsure of your connection method,please contact your Internet Service Provider."
,"When configuring the router to access the IPv6 internet be sure to coose the corred IPv6 Connection Type from the drop down menu,Ifyor are unsrue of which option to choose,contact your internet Service Prvider(ISP.)"
,"Choose the mode to be used by the router to connect to the IPv6 Internet."
,"Autoconfiguration (SLAAC/DHCPv6)"
,"IPv6 over IPv4 Tunnel"
,"6rd"
,"Link-local Only"
,"IPv6 Connection Information"
,"IPv6 Connection Type"
,"Network status"
,"Wan IPv6 Address"
,"IPv6 Default Gateway"
,"Primary IPv6 DNS Server"
,"Secondary IPv6 DNS Server"
,"LAN IPv6 Link-Local Address"
,"DHCP-PD"
,"IPv6 Network assigend by DHCP-PD"
,"LAN IPv6 Address"
,"IPv6 Address"
,"Name(if any)"
,"Static IPv6"
,"DHCPv6"
,"6 to 4"
,"PPPoA"
,"*Connect button for both IPv4 and IPv6"
,"*Disconnect button for both IPv4 and IPv6"
,"Global IPv6 Address"
,"WAN IPv6 Address Settings"
,"Subnet Prefix Length"
,"PPPoE Settings or PPPoA Settings"
,"IPv6 over IPv4 Tunnel Settings"
,"Remote IPv6 Address"
,"IPv6 DNS Settings"
,"DNS Setting"
,"Obtain DNS Server address Automatically"
,"Use the following DNS address"
,"6rd Settings"
,"IPv4 Mask Length"
,"Remote Prefix"
,"Prefix Length"
,"IPv6 Address Range(Start)"
,"IPv6 Address Range(End)"
,"IPv6 Address Lifetime"
,"DS-Lite Enable"
,"DS-Lite Configuration"
,"DS-Lite DHCPv6 Option"
,"Manual Configuration"
,"WAN Link-Local Address"
,"Dynamic IPv6"
,"IPv6 Passthrough"
,"Your IPv4 WAN address is not a Global address."
,"WAN IPv6 Address Status"
)

//---------------------------------WiFi---------------------------------
wpa_en=new Array(
 "Wireless Network Settings"
,"Enable Wireless"
,"Wireless Network Name"
,"(Also called the SSID)"
,"802.11 Mode"
,"B/G Mixed"
,"N mode"
,"B/G/N mixed"
,"Auto Channel Scan"
,"Wireless Channel"
," GHz - CH "
,"Visibility Status"
,"Visible"
,"Invisible"
,"Wireless Security Mode"
,"Security Mode"
,"None"
,"WEP"
,"WPA-Personal"
,"WPA-Enterprise"
,"WEP"
,"WEP is the wireless encryption standard. To use it you must enter the same key(s) into the router and the wireless stations. For 64 bit keys you must enter 10 hex digits into each key box. For 128 bit keys you must enter 26 hex digits into each key box. A hex digit is either a number from 0 to 9 or a letter from A to F. For the most secure use of WEP set the authentication type to &quot;Shared Key&quot; when WEP is enabled."
,"You may also enter any text string into a WEP key box, in which case it will be converted into a hexadecimal key using the ASCII values of the characters. A maximum of 5 text characters can be entered for 64 bit keys, and a maximum of 13 characters for 128 bit keys."
,"Authentication"
,"Open"
,"Shared"
,"WEP Encryption"
,"64Bit"
,"128Bit"
,"Default WEP Key"
,"WEP Key 1"
,"WEP Key 2"
,"WEP Key 3"
,"WEP Key 4"
,"WEP Key"
,"HEX"
,"ASCII"
,"WPA"
,"Use <B>WPA or WPA2</b> mode to achieve a balance of strong security and best compatibility. This mode uses WPA for legacy clients while maintaining higher security with stations that are WPA2 capable. Also the strongest cipher that the client supports will be used. For best security, use <B>WPA2 Only</B> mode. This mode uses AES(CCMP) cipher and legacy stations are not allowed access with WPA security. For maximum compatibility, use <B>WPA Only</B>. This mode uses TKIP cipher. Some gaming and legacy devices work only in this mode.<BR><BR>To achieve better wireless performance use <B>WPA2 Only</b> security mode (or in other words AES cipher)."
,"WPA Mode"
,"WPA2 only"
,"WPA only"
,"Cipher Type"
,"TKIP"
,"AES"
,"Pre-Shared Key"
,"Enter an 8- to 63-character alphanumeric pass-phrase. For good security it should be of ample length and should not be a commonly known phrase."
,"Network Key"
,"(8~63 ASCII or 64 HEX)"
,"EAP (802.1x)"
,"When WPA enterprise is enabled, the router uses EAP (802.1x) to authenticate clients via a remote RADIUS server."
,"RADIUS Server IP Address"
,"RADIUS server Port"
,"RADIUS server Shared Secret"
,"(13 ASCII or 26 HEX)"
,"(5 ASCII or 10 HEX)"
,"The settings will take effective after rebooting."
,"Are you sure to change?"
,"WiFi Setting"
,"In this section you can configure the wireless interface (access point) available on the router."
,"2.4GHz Band"
,"5GHz Band"
,"Wireless Band"
,"Enable Auto Channel Scan"
,"Channel Width"
,"20/40MHz (Auto)"
,"20/40/80MHz (Auto)"
,"802.11b only"
,"802.11g only"
,"802.11n only"
,"Mixed 802.11g and 802.11b"
,"Mixed 802.11n and 802.11g"
,"Mixed 802.11n, 802.11g and 802.11b"
,"802.11a only"
,"802.11n only"
,"Mixed 802.11a and 802.11n"
,"802.11 a/n/ac Mixed"
,"length applies to all keys"
,"WEP Key Length"
,"Warning! Setting the security mode of 2.4GHz band as \"NONE\" will cause security risks. Are you still going to configure it?"
,"It needs to stop WPS feature to enable WEP setting for 2.4GHz band. Are you still going to configure it?"
,"Warning! Setting the security mode of 5GHz band as \"NONE\" will cause security risks. Are you still going to configure it?"
,"It needs to stop WPS feature to enable WEP setting for 5GHz band. Are you still going to configure it?"
,"64Bit (10 hex digits)"
,"128Bit (26 hex digits)"
,"Warning! Setting the security mode of 2.4GHz band as \"NONE\" will cause security risks. Are you still going to configure it?"
,"Warning! Setting the security mode of 5GHz band as \"NONE\" will cause security risks. Are you still going to configure it?"
,"It needs to stop WPS feature to enable WEP setting for 2.4GHz band. Are you still going to configure it?"
,"It needs to stop WPS feature to enable WEP setting for 5GHz band. Are you still going to configure it?"
,"Auto (WPA or WPA2)"
)

wps_en=new Array(
 "UNCONFIGURED"
,"Set"
,"CONFIGURED"
,"Release"
,"NOUSED"
,"IDLE"
,"PROCESSFAIL"
,"STARTPROCESS"
,"RECVEAPOLSTART"
,"SENDEAPREQID"
,"RECVEAPRSPID"
,"RECVWRGVENDORID"
,"RECVWRGVENDORTYPE"
,"SENDEAPREQSTART"
,"SENDM1"
,"RECVM1"
,"SENDM2"
,"RECVM2"
,"RECVM2D"
,"SENDM3"
,"RECVM3"
,"SENDM4"
,"RECVM4"
,"SENDM5"
,"RECVM5"
,"SENDM6"
,"RECVM6"
,"SENDM7"
,"RECVM7"
,"SENDM8"
,"RECVM8"
,"PROCEAPRSPACK"
,"PROCEAPREQDONE"
,"PROCEAPRSPDONE"
,"SENDEAPFAIL"
,"ERRHASHFAIL"
,"ERRHMACFAIL"
,"ERRDEVPWDAUTHFAIL"
,"CONFIGURED"
,"Wi-Fi Protected Setup"
,"WPS"
,"AP PIN"
,"Generate New PIN"
,"Config Mode"
,"Enrollee"
,"Registrar"
,"Config Status"
,"Config Method"
,"PIN Code"
,"Push Button"
,"WPS status"
,"Trigger"
,"Reading..."
,"Wi-Fi Protected Setup (WPS)"
,"WPS is a standard for easy and secure setup of a wireless connection. In this section you can can enable WPS for a client connection using WPA/WPA2 security."
,"PIN Code length must = 4 or 8"
,"PIN Code rule error!"
,"Disable WPS-PIN Method"
,"PIN Code length must = 4 or 8"
,"PIN Code rule error!"
)

wlpfe_en=new Array(
 "Advanced Wireless Settings"
,"Beacon Interval"
,"(msec, range:10~1024)"
,"Transmit Power"
,"RTS Threshold"
,"(1~2347,default 2347)"
,"Fragmentation"
,"(256~2346,default 2346)"
,"DTIM Interval"
,"(range: 1~255)"
,"WMM Capable"
,"TX Rates"
,"Specify advanced configuration settings for the gateways radio from this page. AP security and association parameters can be modified from the default values if needed."
,"Advanced 2.4G Wireless Settings"
,"Advanced 5G Wireless Settings"
,"Short GI"
,"HT 20/40 Coexistence"
)

//---------------------------------LAN---------------------------------
devlist_en=new Array(
 "LAN Clients List"
,"Host Name (if any)"
,"IP Address"
,"MAC Address"
)

lanst_en=new Array(
 "Router Settings"
,"Use this section to configure the internal network settings of your router. The IP address that is configured here is the IP address that you use to access the Web-based management interface. If you change the IP address here, you may need to adjust your PC's network settings to access the network again."
,"Router IP Address"
,"Default Subnet Mask"
,"Local Domain Name"
,"DHCP Server Settings"
,"Use this section to configure the built-in DHCP server to assign IP address to the computers on your network."
,"Enable DHCP Server"
,"DHCP IP Address Range"
,"to"
,"(addresses within the LAN subnet)"
,"DHCP Lease Time"
,"Primary DNS IP Address"
,"Secondary DNS IP Address"
,"Primary WINS IP Address"
,"Secondary WINS IP Address"
,"LAN IP Address setting will take effective after rebooting."
,"Are you sure to change?"
,"IP pool range is invalid!"
,"IP Pool Starting Address"
,"IP Pool Ending Address"
,"Local Domain name is invalid."
,"This section allows you to configure the local network settings of your router. Please note that this section is optional and you should not need to change any of the settings here to get your network up and running."
,"IP Interface Configuration"
,"DHCP Server"
,"DHCP Server Configuration"
,"DHCP Reservation"
)

//---------------------------------Advanced---------------------------------
ddns_en=new Array(
 "Dynamic DNS"
,"Enable DDNS"
,"Provider"
,"DynDNS.org(Dynamic)"
,"DynDNS.org(Custom)"
,"No-IP.com"
,"TZO.com"
,"dhs.org"
,"Host Name"
,"Username / E-mail"
,"Password / Key"
,"The resolving of IP address to host names/domains and voice versa is managed by the DNS. The required information(IP address of at least one DNS server) is normally provided by your ISP. But this device is also able to detect the DNS servers available automatically."
)

spap_en=new Array(
 "Popular applications"
,"-- Select one --"
,"Battle.net"
,"Dialpad"
,"ICU II"
,"MSN Gaming Zone"
,"PC-to-Phone"
,"Quick Time 4"
,"Application Rules"
,"Trigger"
,"Incoming Ports"
,"Application"
,"Service port of virtual server and incoming port of application rules cannot be the same."
,"Incoming Port value can not be the same."
)

dmz_en=new Array(
 "Firewall Settings"
,"Enable SPI"
,"DMZ Host"
,"The DMZ (Demilitarized Zone) option lets you set a single computer on your network outside of the router. If you have a computer that cannot run Internet applications successfully from behind the router, then you can place the computer into the DMZ for unrestricted Internet access."
,"<b>Note:</b> Putting a computer in the DMZ may expose that computer to a variety of security risks. Use of this option is only recommended as a last resort."
,"Enable DMZ"
,"DMZ IP Address"
,"Computer Name"
)

smap_en=new Array(
 "Well known services"
,"-- Select one --"
,"AUTH (113)"
,"DNS (53)"
,"FTP (21)"
,"ISAKMP (500)"
,"POP3 (110)"
,"PPTP (1723)"
,"SMTP (25)"
,"TELNET (23)"
,"WEB (80)"
,"Use schedule rule"
,"---ALWAYS ON---"
,"Virtual Servers List"
,"Service Ports"
,"Server IP : Port"
,"Enable"
,"Schedule Rule#"
,"The Externally acts as server. It receives the requests of remote users under its public IP address and forwards them automatically to the Virtual Server."
,"So a client in your network behind NAT or firewall can provide services as a Virtual Server."
,"You just have to enable specific ports or port ranges and protocols (UDP/TCP). File sharing or web services for e.g. HTTP, FTP or POP3 are possible. The private IP addresses of the servers in the local network remain safe. If you have a dynamic IP address, you may want to enable DynDNS additionally."
,"Service Port value can not be the same."
,"setting error"
)

uctl_en=new Array(
 "URL Filtering Setting"
,"URL Filtering"
,"Enable"
,"URL Filtering Rules"
,"URL"
,"Enable"
,"URL can not be empty!!"
,"'http://' is not allowed!"
,"URL Filter provides the useful tools for restricting Internet access."
,"Website URL Blocking allows you to quickly create a list of all web sites that you wish to allow or deny users from accessing."
,"URL Filter"
)

rtab_en=new Array(
 "RIP Setting"
,"RIP"
,"Enable"
,"RIPv1"
,"RIPv2"
,"Routing Rules"
,"Destination"
,"Subnet Mask"
,"Gateway"
,"Hop"
,"The routes for the traffic in your network are defined in the routing table. Normally, the entries for IP Address and Gateway are sufficient. You do not need to define any settings."
)

qos_en=new Array(
 "High"
,"Normal"
,"Low"
,"QoS Engine Setup"
,"Enable QoS Packet Filter"
,"Upstream bandwidth"
,"Downstream bandwidth"
,"kbps"
,"Use schedule rule"
,"---ALWAYS ON---"
,"QoS Rules"
,"Local IP : Ports"
,"Remote IP : Ports"
,"QoS Priority"
,"Enable"
,"Use Rule#"
,"QoS Engine Setup"
)

pmac_en=new Array(
 "MAC Filtering Settings"
,"MAC Address Control"
,"Enable"
,"Connection control"
,"Wireless and wired clients with <b>C</b> checked can connect to this device; and "
,"allow"
,"deny"
,"unspecified MAC addresses to connect."
,"Association control"
,"Wireless clients with <b>A</b> checked can associate to the wireless LAN; and "
,"allow"
,"deny"
,"unspecified MAC addresses to associate."
,"DHCP clients"
,"-- Select one --"
,"MAC Filtering Rules"
,"MAC Address"
,"IP Address"
,"C"
,"A"
)

iopf_en=new Array(
 "Outbound Filter Setting"
,"Inbound Filter Setting"
,"Outbound Filter"
,"Inbound Filter"
,"Enable"
,"Use schedule rule"
,"---ALWAYS ON---"
,"Outbound Filter Rules List"
,"Inbound Filter Rules List"
,"Allow all to pass except those match the following rules."
,"Deny all to pass except those match the following rules."
,"Source IP:Ports"
,"Destination IP:Ports"
,"Enable"
,"Schedule Rule#"
,"Use the rule number error!!"
)

snmp_en=new Array(
 "SNMP"
,"SNMP Local"
,"SNMP Remote"
,"Get Community"
,"Set Community"
,"IP 1"
,"IP 2"
,"IP 3"
,"IP 4"
,"SNMP Version"
,"V1"
,"V2c"
,"WAN Access IP Address"
)

fmisc_en=new Array(
 "UPNP"
,"Universal Plug and Play (UPnP) supports peer-to-peer Plug and Play functionality for network devices."
,"Enable UPnP"
,"WAN PING"
,"If you enable this feature, the WAN port of your router will respond to ping requests from the Internet that are sent to the WAN IP Address."
,"Enable WAN Ping Respond"
)

networkscan_en=new Array(
 "Network Provider Selection"
,"This page will scan near network providers.<br>Please wait for a while for each scan."
,"Network Selection Method"
,"In Progressing..."
,"List of Network Providers"
,"There is no any network provider"
,"You doesn't choose Network Providers the mode will change to Auto"
,"Your changes have been saved. The router must be rebooted for the changes to take effect."
,"You can reboot now, or you can continue to make other changes and reboot later."
,"Available"
,"Current"
,"Forbidden"
,"Scan"
,"Network Selection Method"
)

//---------------------------------System---------------------------------
sntp_en=new Array(
 "Time and Date Configuration"
,"Time"
,"Time Zone"
,"Enable Daylight Saving"
,"Sync. your computer's time settings"
,"Automatic Time and Date Configuration"
,"Automatically synchronize with Internet time server"
,"NTP Server Used"
,"Update Now"
,"Sync. RESULT"
,"Start"
,"End"
,"Hour"
,"Day"
,"Month"
,"(Hour/Day/Month)"
,"Jan"
,"Feb"
,"Mar"
,"Apr"
,"May"
,"Jun"
,"Jul"
,"Aug"
,"Sep"
,"Oct"
,"Nov"
,"Dec"
,"Sun"
,"Mon"
,"Tue"
,"Wed"
,"Thu"
,"Fri"
,"Sat"
,"The time Configuration option allows you to configure, update, and maintain the correct time on the internal system clock."
,"From this section you can set the time zone that you are in and set the NTP (Network Time Protocol) Server."
,"Daylight Saving can also be configured to automatically adjust the time when needed."
,"Time"
,"Time Settings"
)

tz_en=new Array(
 "* Not yet configured! The default is GMT+00:00"
,"International Date Line West"
,"Midway Island, Samoa"
,"Hawaii"
,"Alaska"
,"Pacific Time (US & Canada)"
,"Tijuana"
,"Arizona"
,"Chihuahua, La Paz, Mazatlan"
,"Mountain Time (US & Canada)"
,"Central America"
,"Central Time (US & Canada)"
,"Guadalajara, Mexico, Monterrey"
,"Saskatchewan"
,"Bogota, Lima, Quito"
,"Eastern Time (US & Canada)"
,"Indiana (East)"
,"Atlantic Time (Canada)"
,"Caracas, La Paz"
,"Santiago"
,"Newfoundland"
,"Brasilia"
,"Buenos Aires, Georgetown"
,"Greenland"
,"Mid-Atlantic"
,"Azores"
,"Cape Verde Is."
,"Casablanca, Monrovia"
,"Dublin, Edinburgh, Lisbon, London"
,"Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna"
,"Belgrade, Bratislava, Budapest, Ljubljana, Prague"
,"Brussels, Copenhagen, Madrid, Paris"
,"Sarajevo, Skopje, Warsaw, Zagreb"
,"West Central Africa"
,"Athens, Beirut, Istanbul, Minsk"
,"Bucharest"
,"Cairo"
,"Harare, Pretoria"
,"Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius"
,"Jerusalem (2007 only)"
,"Baghdad"
,"Kuwait, Riyadh"
,"Moscow, St. Petersburg, Volgograd"
,"Nairobi"
,"Tehran"
,"Abu Dhabi, Muscat"
,"Baku"
,"Tbilisi"
,"Yerevan"
,"Kabul"
,"Ekaterinburg"
,"Islamabad, Karachi, Tashkent"
,"Chennai, Kolkata, Mumbai, New Delhi"
,"Kathmandu"
,"Almaty, Novosibirsk"
,"Astana, Dhaka"
,"Colombo"
,"Rangoon"
,"Bangkok, Hanoi, Jakarta"
,"Krasnoyarsk"
,"Beijing, Chongqing, Hong Kong, Urumqi"
,"Irkutsk"
,"Kuala Lumpur, Singapore"
,"Perth, Western Australia"
,"Taipei"
,"Ulaan Bataar"
,"Osaka, Sapporo, Tokyo"
,"Seoul"
,"Yakutsk"
,"Adelaide"
,"Darwin"
,"Brisbane"
,"Canberra, Melbourne, Sydney"
,"Guam, Port Moresby"
,"Hobart"
,"Vladivostok"
,"Magadan, Solomon Is., New Caledonia"
,"Auckland, Wellington"
,"Fiji, Kamchatka, Marshall Is."
,"Nuku'alofa"
,"* Configure TZ variable manually..."
,"Eniwetok, Kwajalein"
,"Mexico City, Tegucigalpa"
,"Brussels, Copenhagen, Madrid, Paris, Vilnius"
,"Sarajevo, Skopje, Sofija, Warsaw, Zagreb"
,"Athens, Beirut, Cairo, Istanbul, Minsk"
,"Beijing, Hong Kong, Taipei"
,"India"
)

atbox_en=new Array(
 "Administrator (The default login name is "
,")"
,"Login Name"
,"New Password"
,"Confirm Password"
,"Remote Management"
,"Enable Remote Management"
,"IP Allowed to Access"
,"Port"
,"New Administrator passwords are not identical!"
,"Do you want to save your password to empty password?"
,"Remote Management Port should be larger than 1024."
,"Administrator"
,"Here you can change the password for the administrator."
,"The username (admin) can not be change."
,"Administrator Settings"
,"SSH"
,"Enable SSH"
,"Allow Wan"
,"Telnet"
,"Enable Telnet"
,"Remote Administration"
)

rebo_en=new Array(
 "Upgrade successful!"
,"Invalid upgrade file!"
,"Please make sure you have correct file."
,"The file is not compatible with current firmware or hardware."
,"Upgrade to this version is not allowed!"
,"Upgrading process was aborted by unknown reason."
,"Please try again!"
,"All setting is reset!"
,"The device is rebooting..."
,"Please <font color=red><b>DO NOT POWER OFF</b></font> the device."
,"And please wait for "
," seconds..."
,"Please reconnect manually."
,"Note! Your LAN IP might change, Please reconnect."
,"Click here to reconnect"
,"System is ready"
,"Restart Router"
,"Status Message"
,"Router Will be up in"
,"Reboot Now"
,"Reboot Later"
)

system_en=new Array(
 "Reset all setting to default?"
,"Save and Restore Settings"
,"Save Settings To Local Hard Drive"
,"Save"
,"Load Settings From Local Hard Drive"
,"Upload Settings"
,"Restore To Factory Default Settings"
,"Reset to Default"
,"Invalid upgrade file!"
,"Unallowable upgrade file!"
,"System"
,"All settings will be automatically saved to your device. There is no need to manually save or reboot. If you want to restart the device anyway, it is better done via the \"Reboot\" button."
,"System settings"
,"Reboot the Device"
,"Reset all settings to factory default?"
,"Reboot"
,"Reboot & Reset"
)

fwug_en=new Array(
 "Firmware Information"
,"Current Firmware Version"
,"Current Firmware Date"
,"Firmware Upgrade"
,"Note! Do not power off the unit when it is being upgraded."
,"The upgrade procedure takes about 180 seconds."
,"When the upgrade is done successfully, the unit will be restarted automatically."
,"To upgrade the firmware, your PC must have a wired connection to the router. Enter the name of the firmware upgrade file, and click on the Upload button."
,"Upload"
,"Upgrade"
,"Incorrect Filename"
,"Only .bin file is accepted."
,"Cancel"
,"Another firmware upgrading is in process now!"
,"Accept unofficial firmware."
,"Please use the \"Upgrade\" button to update firmware version for your device."
,"Firmware Update"
,"Select Firmware"
,"Check File"
,"New Firmware Information"
,"New Firmware Version"
,"New Firmware Date"
)

logs_en=new Array(
 "SysLog Settings"
,"Enable Logging To Syslog Server"
,"Syslog Server IP Address"
,"Email Settings"
,"Enable Email Notification"
,"SMTP Server IP and Port"
,"Send E-mail alert to"
,"E-mail Subject"
,"SMTP Username"
,"SMTP Password"
,"Email Log Now"
,"An email is queued for sending..."
,"System Log"
,"The System Log allows you to configure local, remote and email logging, and to view the logs that have been created."
,"Clear logs"
,"Log Number"
,"Message"
,"View Logs"
)

smsmsg_en=new Array(
 "Reply Message"
,"Forward Message"
,"Create Message"
,"Text message"
,"Enter Message..."
,"The max. length of a message is 160 characters."
,"Receiver"
,"Add '+' for international format of the phone number."
,"Send"
,"Reading... Please wait a moment..."
,"Current input text length"
,"Send message"
,"If you would like to create and send SMS message, then click on the button below."
,"Receiver can not be empty!"
,"The max. length of a message is 160 characters for pure alphabetical or numeric."
)

smsinbox_en=new Array(
 "SMS Status"
,"Received SMS"
,"New SMS"
,"Total Capacity"
,"Inbox"
,"From"
,"Timestamp"
,"Text"
,"SMS"
,"Reading... Please wait a moment..."
,"Reply"
,"Forward"
,"SMS Inbox"
,"If you would like to view SMS message, click on the button below."
,"SMSC Setting"
,"Please check the SIM card inserted or not."
,"SIM card is locked! Cannot read SMS from SIM card."
,"Modem isn't Ready!"
,"Modem is busy by Phone call! Please wait..."
,"Send OK!"
,"Send Failed!"
,"Modem is busy by phone call!SMS will be sent automatically later."
,"Delete OK!"
,"Delete failed!"
,"AT Command Failed!"
,"Modem is busy by phone call!SMS will be deleted automatically later."
)

voiceforwd_en=new Array(
 "All calls"
,"No Answer"
,"Unreachable"
,"Busy"
,"Status"
,"Unregister"
,"Register"
,"Activate"
,"Deactivate"
,"Number"
)

pinco_en=new Array(
 "Query status... Please wait a moment..."
,"SIM PIN Code"
,"Please input 4~8 characters in SIM PIN Code field!"
,"PIN Code Request function"
,"Input SIM PIN Code"
,"Change PIN Code..."
,"Success!"
,"Please input 4~8 characters in Old PIN Code field!"
,"Please input 4~8 characters in New PIN Code field!"
,"Please input 4~8 characters in Verify PIN Code field!"
,"PIN Code Change function"
,"Old PIN Code"
,"New PIN Code"
,"Verify PIN Code"
,"Save!"
,"Please input the PIN Code to unlock the SIM card"
,"PIN Code"
,"Please input the PUK Code to unlock the SIM card"
,"PUK Code"
,"New PIN Code"
,"Function is already disabled!"
,"Function is already enabled!"
,"PIN Code wrong!"
,"You have to enable PIN Code request function first!"
,"You have entered two different new PIN Codes!"
,"Old PIN Code wrong!"
,"PUK Code wrong!"
,"AT Command Failed!"
,"Ready"
,"Locked by SIM PIN"
,"Locked by SIM PUK"
,"SIM card with some errors."
,"Modem has no response."
,"Send AT command failed!"
,"Modem does not exist! Please check if SIM card is inserted!"
,"Warning : 3 more tries allowed."
,"Retry"
,"Continue"
,"Warning : "
," more tries allowed."
,"Please input 4~8 characters in PIN Code field!"
,"Please input 8 characters in PUK Code field!"
,"PIN Control"
,"Modem is initializing, please wait a minute!"
,"PIN Configuration"
,"Insert PIN Code 3 times fail! Please insert PUK Code."
)

ussd_en=new Array(
 "USSD"
,"Send"
,"ERROR"
)

scherebo_en=new Array(
 "Connection Reset"
,"Auto-Reboot"
,"Reboot-Schedule"
,"Diary Schedule"
,"Weekly Schedule Day of Week"
,"Date of Month"
)

sche_en=new Array(
 "Schedule Rule"
,"Enable Schedule"
,"Rule#"
,"Rule Name"
,"Action"
,"No rule added, please add rules before enable!"
,"Are you sure to delete rule "
,"??"
,"Schedule"
)

rule_en=new Array(
 "Rule name can not be empty!"
,"The schedule name is duplicate with other rule!"
,"(Rule:"
,")"
,"Pleasse check again!"
,"Start Time of week day "
," is invalid!!"
,"End Time of week day "
," is invalid!!"
,"Time of week day "
," is invalid!!"
,"End time must be larger than start time"
,"(Schedule time format should be hh:mm)"
,"(0 < The hours of start time < 23 )"
,"(0 < The minutes of start time < 59 )"
,"(0 < The hours of end time < 23 )"
,"(0 < The minutes of end time < 59 )"
,"Please select weekday in rule ID "
,"!!"
,"The time of Schedule rule is empty!!"
," Please enter at least one schedule!!"
,"Every Day"
,"Sunday"
,"Monday"
,"Tuesday"
,"Wednesday"
,"Thursday"
,"Friday"
,"Saturday"
,"Schedule Rule Setting"
,"Name of Rule"
,"-- choose one --"
,"Policy"
,"Back"
,"Inactivate"
,"Activate"
,"except the selected days and hours below."
,"Week Day"
,"Start Time (hh:mm)"
,"End Time (hh:mm)"
)

diagnostic_en=new Array(
 "Service Information"
,"Operator"
,"Cell Broadcast"
,"MCC"
,"MNC"
,"LAC"
,"Service Type"
,"Service Prefer Mode"
,"GSM only"
,"WCDMA only"
,"Unknown"
,"PS attach(DATA)"
,"CS attach(VOICE)"
,"IMSI"
,"SMSC"
,"Attached"
,"Detached"
,"SIM Status"
,"PIN Code Lock"
,"PIN Code Retry Times"
,"PUK Code Retry Times"
,"Module Status"
,"IMEI"
,"FW Version"
,"Module Name"
,"Cell ID"
)

voice_en=new Array(
 "Voice"
,"Call Forwarding"
,"Auto-forwarding incoming calls to a designated number in different conditions."
,"Call Waiting"
,"Suspend current call, and be able to talk to a new incoming call."
,"Go Call Forwarding"
,"Go Call Waiting"
)

sms_en=new Array(
 "Create Message"
,"Allow you to create and send new SMS message."
,"inbox"
,"Allow you to read new SMS message, and delete/forward existed message."
,"You can reply only one message at a time!"
)

tr069_en=new Array(
 "TR-069"
,"TR-069 Setting"
,"ACS Setting"
,"ACS URL"
,"ACS UserName"
,"ACS Password"
,"CPE Setting"
,"ConnectionRequest Port"
,"ConnectionRequest UserName"
,"ConnectionRequest Password"
,"Inform Setting"
,"Inform"
,"Interval"
,"Interface"
)
