//Portuguese
common=new Array(
 "Atualizar"
,"Ajuda"
,"Fim de sessão"
,"Ativar"
,"Desativar"
,"Item"
,"Editar"
,"Eliminar"
,"Voltar"
,"Auto"
,"Manual"
,"Aplicar"
,"Repor"
,"Adicionar"
,"segundos"
,"bytes"
,"ID"
,"Copiar para"
,"Página anterior"
,"Página seguinte"
,"Adicionar Regra Nova..."
,"Melhor"
,"minutos"
,"Ativado"
,"Desativado"
,"First Page"
,"Last Page"
,"Download"
,"Page"
)

others=new Array(
 "Reiniciar"
,"Reiniciar Router?"
,"Terminou a sessão"
,"Página do Produto"
,"Versão de Firmware"
,"direitos de autor"
,"Sugestões Úteis..."
,"Mais..."
,"Guardar Definições"
,"Não Guardar as Definições"
,"Sem alterações"
,"Sem alterações!!"
,"Continuar"
,"Definições Guardadas!"
,"As alterações têm efeito imediatamente!"
,"Definição concluída"
,"O sistema está a processar, aguarde alguns segundos..."
,"ROUTER"
,"Nome de utilizador"
,"Palavra-passe"
,"Iniciar sessão"
,"Nome de utilizador ou palavra-passe inválidos"
,"Introduza um nome de utilizador válido."
,"Nome de utilizador ou palavra-passe inválidos"
,"Terminou a sessão com sucesso."
,"Terminou a sessão."
,"Inicie sessão primeiro!"
,"Introduza um nome de utilizador válido"
,"Introduza uma palavra-passe válida"
,"Introduza o Nome de Utilizador."
,"O valor da entrada não pode estar vazio."
,"Aguarde alguns segundos..."
,"O administrador da conta já logined"
,"Concorda?"
)

dirary0=new Array(
 "Início"
,"internet"
,"Wi-Fi"
,"LAN"
,"Avançadas"
,"Sistema"
,"Serviço WAN"
,"Ativação pós-falha"
,"IPv6"
,"Lista de Dispositivos"
,"Definições Wi-Fi"
,"WPS"
,"Wi-Fi Avançado"
,"Definições LAN"
,"DHCP"
,"DNS"
,"Aplicações"
,"DMZ"
,"Servidor Virtual"
,"Filtro URL"
,"Encaminhamento"
,"QOS"
,"Filtro de Endereços MAC"
,"Filtro Externo"
,"Filtro Interno"
,"SNMP"
,"Rede Avançada"
,"Definições da Hora"
,"Administração"
,"Reiniciar e Repor"
,"Atualização de Firmware"
,"Registos do sistema"
,"Agendamentos"
,"Assistente"
,"Digitalização Em Rede"
,"Repor Ligação"
,"Configuração do PIN"
,"Message Service"
,"Caixa de entrada de SMS"
,"Criar Mensagem"
,"Voz"
,"Reencaminhamento de Chamadas"
,"Chamada em Espera"
,"Diagnóstico"
,"TR-069"
,"Multi-WAN"
)

valchk=new Array(
 "Por favor volte a verificar as definições!!"
,"O endereço IP é inválido."
,"A máscara de sub-rede é inválida."
,"O intervalo de endereço IP é inválido."
,"O endereço IP LAN é inválido."
,"o valor é inválido."
,"A porta é inválida."
,"(Exemplo de formato 1-65535,777)"
,"O intervalo das portas é inválido. (Exemplo de formato 1-65535)"
,"A MTU é inválida!"
,"A hora é inválida."
,"As horas são inválidas."
,"O endereço MAC é inválido."
,"A chave WEP é inválida."
,"A chave pré-partilhada é inválida."
,"O e-mail é inválido."
,"Introduza 10 ou 26 dígitos hexadecimais no campo da chave WEP!!"
,"Introduza 5 ou 13 caracteres ASCII no campo da chave WEP!!"
,"Introduza 64 dígitos hexadecimais ou 8~63 caracteres ASCII no campo da Chave Pré-partilhada!!"
,"Introduza 64 dígitos hexadecimais no campo da Chave Pré-partilhada!!"
," é inválida!"
)

//---------------------------------status---------------------------------
sta=new Array(
 "Geral"
,"Hora"
,"Versão de Firmware"
,"WAN"
,"Tipo de Ligação"
,"IP Estático"
,"Endereço MAC"
,"Endereço IP"
,"Máscara de Sub-rede"
,"Gateway predefinida"
,"Servidor DNS"
,"Cliente DHCP"
,"Estado da Rede"
,"Cliente Desligou"
,"A ligar..."
,"Estabelecida"
,"A desligar..."
,"A aguardar pelo tráfego..."
,"Tempo de Reserva Restante"
,"Renovar"
,"Versão"
,"PPPoE"
,"Desligado"
,"Tempo de Ligação"
,"Ligar"
,"Desligar"
,"Ligar novamente"
,"PPTP"
,"L2TP"
,"4G LTE /3G"
,"Intensidade do Sinal"
,"Informação da Placa"
,"Estado da Ligação"
,"Falha na autenticação"
,"É necessário o PIN"
,"Erro de palavra-passe"
,"Nenhum Modem Detetado"
,"Não foi possível ligar! Verifique as definições e tente novamente."
,"Nome da Rede"
,"LAN"
,"Servidor DHCP"
,"LAN Sem Fios"
,"Sem Fios"
,"SSID"
,"Segurança"
,"Abrir"
,"Partilhado"
,"Auto"
,"WPA-PSK"
,"WPA"
,"WPA2-PSK"
,"WPA2"
,"WPA-PSK/WPA2-PSK"
,"WPA/WPA2"
,"Nenhum"
,"WEP"
,"TKIP"
,"AES"
,"TKIP/AES"
,"Canal"
,"Auto"
,"Modo 802.11"
,"B/G Misto"
,"Modo N"
,"B/G/N Misto"
,"Configuração Protegida Wi-Fi"
,"Computadores da LAN"
,"Nome"
,"MAC"
,"Dia"
,"Horas"
,"Min"
,"Seg"
,"N/D"
,"Ativação pós-falha 3G"
,"Placa 3G"
,"Internet"
,"SSID2"
,"Total de Clientes"
,"Agrupamento DHCP"
,"Nome do Sistema"
,"Tempo de disponibilidade do Sistema"
,"Versão de HW"
,"Versão de SW"
,"Ativação pós-falha"
,"Partilha de carga"
,"Tipo de Serviço"
,"Telefone"
,"Nenhum Serviço"
,"Estado"
)

//---------------------------------Internet---------------------------------
prim=new Array(
 "Tipo de Ligação à Internet"
,"A minha ligação à Internet é"
,"IP Estático"
,"IP Dinâmico (DHCP)"
,"PPPoE (Nome de Utilizador/Palavra-passe)"
,"PPTP (Nome de Utilizador/Palavra-passe)"
,"L2TP (Nome de Utilizador/Palavra-passe)"
,"4G LTE /3G"
,"Cópia de Segurança Automática"
,"Ativar verificação de WAN com fios ativa"
,"Anfitrião de Internet"
,"Introduza um endereço IP na Internet."
,"Tipo de Ligação à Internet com Endereço IP Estático"
,"Endereço IP"
,"Máscara de Sub-rede"
,"Gateway predefinida"
,"Servidor de DNS Preferido"
,"Servidor de DNS Alternativo"
,"MTU"
,"MTU predefinido (bytes) = 1500"
,"Endereço MAC"
,"Clonar"
,"Limpar"
,"Tipo de Ligação à Internet com Endereço IP Dinâmico (DHCP)"
,"Nome do anfitrião"
,"Voltar a ligar automaticamente"
,"PPPoE"
,"Nome de utilizador"
,"Palavra-passe"
,"Confirmar a Palavra-passe"
,"Nome do Serviço"
,"(opcional)"
,"Endereço IP"
,"Tempo Máximo de Inatividade"
,"MTU predefinido (bytes) = 1492"
,"PPTP"
,"Modo Endereço"
,"IP Dinâmico"
,"IP Estático"
,"Endereço IP PPTP"
,"Máscara de Sub-rede PPTP"
,"Endereço IP Gateway PPTP"
,"Endereço IP do Servidor PPTP"
,"Modo Ligar Novamente"
,"Sempre ligado"
,"Ligar a pedido"
,"L2TP"
,"Endereço IP L2TP"
,"Máscara de Sub-rede L2TP"
,"Endereço IP Gateway L2TP"
,"Endereço IP do Servidor L2TP"
,"Tipo de Ligação à Internet 4G LTE /3G"
,"Nome da Conta/Perfil"
,"Número Marcado"
,"Autenticação"
,"PAP"
,"CHAP"
,"APN"
,"Código PIN"
,"Keep Alive"
,"Desativar"
,"Utilizar Ping"
,"DNS Query"
,"Utilizar Pedido Echo LCP"
,"intervalo-echo-lcp:"
,"falha-echo-lcp:"
,"horas"
,"Endereço IP de Ping"
,"Intervalo de Ping"
,"Contornar portas de ethernet"
,"O endereço MAC foi alterado"
,"O novo endereço MAC produz efeitos depois de reiniciar."
,"Reiniciar agora?"
,"Roaming"
,"Verificação de DNS"
,"desativar NAT"
,"Modo Automático"
,"Modo Apenas 4G"
,"Modo Apenas 3G"
,"Modo Apenas 2G"
,"Tipo de Serviço preferido"
,"Configuração do Serviço WAN"
,"opcional"
,"Bridge Transparente"
,"Interface WAN"
,"Fechar"
,"WAN de Ethernet"
,"Perfil por Marcação"
,"Deteção Automática"
,"País"
,"Telecom"
,"Rede"
,"Outros"
,"Configuração de Rede"
,"As novas palavras-passe não são idênticas!"
,"definição inválida!"
,"Modo Automático"
,"Modo Preferido 3G"
,"Primeiro Modo 2G"
,"A carregar"
,"Rede 3G/4G"
,"WCDMA/HSP"
,"CDMA2000/EV-DO"
,"O Endereço IP e a Gateway Predefinida são inválidos!"
,"O intervalo de Tempo Máximo de Inatividade deve estar entre"
,"Tipo de Ligação à Internet 3G"
,"VLAN Tagging"
)

failover=new Array(
 "Definição de Ativação pós-falha"
,"Tipo de Ativação pós-falha"
,"Anfitrião Remoto para Keep Alive "
,"Lista de Ativação pós-falha"
,"Interface"
,"Alterar"
,"A Ligação à Internet atual é"
,"O tipo de Ativação pós-falha da Internet é"
,"Ativação pós-falha"
,"Tipo de Ativação pós-falha da Ligação"
,"Definição da Ativação pós-falha da Interface"
,"Tem a certeza de que pretende eliminar a WAN secundária?"
,"Definição da Cópia de Segurança automática"
,"Cópia de Segurança Automática"
,"Anfitrião Remoto para Keep Alive "
,"Listas de Ligação WAN"
,"Interface"
,"Altere ou elimine a interface!"
,"O Anfitrião Remoto para Keep Alive não pode ser Nulo!"
,"Seleção inválida!"
,"WAN primária"
,"WAN secundária"
,"Mudar o tipo de WAN vai limpar todas as Definições de ativação pós-falha,\nConcorda?"
,"Partilha de carga"
,"A definir a Ativação pós-falha..."
,"Tipo de Ligação de Partilha de carga"
,"Endereço IP Dinâmico"
,"Endereço IP estático"
,"Porta 1"
,"Porta 2"
,"Selecione a WAN Secundária!"
,"A ativação das portas Bridge Ethernet irá desativar a Ethernet WAN."
)

ipv6=new Array(
 "Definições 6 para 4"
,"Endereço 6 para 4"
,"Endereço de DNS primário"
,"Endereço de DNS secundário"
,"Definições de Endereço IPv6 LAN"
,"Endereço IPv6 da LAN"
,"Endereço de Ligação Local IPv6 LAN"
,"Definições de configuração automática do endereço"
,"Configuração Automática"
,"Tipo de Configuração Automática"
,"Tempo de Vida Útil de Aviso do Router"
,"Endereço IPv4 Remoto"
,"Endereço IPv4 Local"
,"Endereço IPv6 Local"
,"Configuração IPv6"
,"Ligação IPv6"
,"Sem Estado"
,"Com Estado (DHCPv6)"
,"Utilize a secção para configurar as definições de rede interna do seu router. O endereço Local de Ligação IPv6 da LAN é o Endereço IPv6 que utiliza para aceder à interface de gestão baseada na Internet. Se alterar aqui o endereço LAN IPv6, pode necessitar de ajustar as definições de rede do seu PC para aceder novamente à rede."
,"ativar DHCP-PD"
,"Definições de Configuração Automática de Endereço LAN"
,"Utilize esta secção para configurar a Configuração Automática IPv6 para atribuir endereços IP aos computadores na sua rede."
,"Ativar Configuração Automática"
,"SLAAC + DHCPv6 Sem Estado"
,"Endereço de Ligação Local IPv6 LAN"
,"Utilize esta secção para configurar o seu tipo de Ligação IPv6. Se não tiver a certeza do seu método de ligação, contacte o seu Fornecedor de Serviços de Internet."
,"Quando estiver a configurar o router para aceder à Internet IPv6, certifique-se de que escolhe o Tipo de Ligação IPv6 correto no menu pendente. Se não tiver a certeza da opção a escolher, contacte o seu Fornecedor de Serviços de Internet (ISP)."
,"Escolha o modo a utilizar pelo router para ligar à Internet IPv6."
,"Configuração automática (SLAAC/DHCPv6)"
,"IPv6 no Túnel IPv4"
,"6rd"
,"Apenas ligações locais"
,"Informação da Ligação IPv6"
,"Tipo de Ligação IPv6"
,"Estado da Rede"
,"Endereço IPv6 da WAN"
,"Gateway Predefinida IPv6"
,"Servidor de DNS IPv6 Preferido"
,"Servidor de DNS IPv6 Alternativo"
,"Endereço de Ligação Local IPv6 LAN"
,"DHCP-PD"
,"Rede IPv6 atribuída por DHCP-PD"
,"Endereço IPv6 da LAN"
,"Endereço IPv6"
,"Nome(se existir)"
,"IPv6 estático"
,"DHCPv6"
,"6 a 4"
,"PPPoA"
,"*Botão de ligação para IPv4 e IPv6"
,"*Botão de desligar para IPv4 e IPv6"
,"Endereço IPv6 Global"
,"Definições do Endereço IPv6 WAN"
,"Comprimento do Prefixo de Sub-rede"
,"Definições PPPoE ou Definições PPPoA"
,"Definições IPv6 sobre Túnel IPv4"
,"Endereço IPv6 Remotos"
,"Definições IPv6 DNS"
,"Definição DNS"
,"Obter endereço de Servidor DNS Automaticamente"
,"Utilize o endereço DNS seguinte"
,"Definições 6rd"
,"Comprimento da Máscara IPv4"
,"Prefixo Remoto"
,"Comprimento do Prefixo"
,"Intervalo de Endereços IPv6 (Início)"
,"Intervalo do Endereço IPv6 (Final)"
,"Tempo do Endereço IPv6"
,"Ativar DS-Lite"
,"Configuração DS-Lite"
,"Opção DS-Lite DHCPv6"
,"Configuração Manual"
,"Endereço de Ligação Local WAN"
,"IPv6 Dinâmico"
,"Passagem IPv6"
,"O seu endereço WAN IPv4 não é um endereço Global."
,"WAN IPv6 Address Status"
)

//---------------------------------WiFi---------------------------------
wpa=new Array(
 "Definições da Rede Sem Fios"
,"Ativar Sem Fios"
,"Nome da sua Rede Sem Fios"
,"(Também chamado SSID)"
,"Modo 802.11"
,"B/G Misto"
,"Modo N"
,"B/G/N misto"
,"Pesquisa Automática de Canais"
,"Canal da Ligação sem Fios"
," GHz - CH "
,"Estado da Visibilidade"
,"Visível"
,"Invisível"
,"Modo de Segurança Sem Fios"
,"Modo de segurança"
,"Nenhum"
,"WEP"
,"WPA-Personal"
,"WPA-Enterprise"
,"WEP"
,"WEP é a norma de encriptação sem fios. Para utilizá-lo, deve introduzir a(s) mesma(s) chave(s) no router e nas estações sem fios. Para chaves de 64 bit deve introduzir 10 dígitos hexadecimais em cada caixa de chave. Para chaves de 128 bit deve introduzir 26 dígitos hexadecimais em cada caixa de chave. Um dígito hexadecimal é um número de 0 a 9 ou uma letra de A a F. Para a utilização mais segura de WEP, defina o tipo de autenticação como &quot;Chave Partilhada&quot; quando a WEP está ativada."
,"Também pode introduzir qualquer linha de texto numa caixa de chave WEP, que será convertida numa chave hexadecimal utilizando valores ASCII dos caracteres. Pode inserir-se um máximo de 5 caracteres de texto para as chaves de 64 bits, e um máximo de 13 caracteres para chaves de 128 bits."
,"Autenticação"
,"Abrir"
,"Partilhado"
,"Encriptação WEP"
,"64Bit"
,"128Bit"
,"Chave WEP pré-definida"
,"Chave WEP 1"
,"Chave WEP 2"
,"Chave WEP 3"
,"Chave WEP 4"
,"Chave WEP"
,"HEX"
,"ASCII"
,"WPA"
,"Utilize o modo <B>WPA ou WPA2</b> para atingir um equilíbrio entre segurança forte e a melhor compatibilidade. Este modo utiliza WPA para clientes legacy enquanto mantém uma segurança mais elevada com estações que suportem WPA2. Além disso, será utilizada a cifra mais forte que o cliente suportar. Para a melhor segurança, utilize o modo <B>Apenas WPA2</B>. Este modo utiliza uma cifra AES(CCMP) e estações legacy não terão acesso com segurança WPA. Para a máxima compatibilidade, utilize <B>Apenas WPA</B>. Este modo utiliza cifra TKIP. Alguns dispositivos de jogos e legacy funcionam apenas neste modo.<BR><BR>Para conseguir um melhor desempenho sem fios, utilize o modo de segurança <B>Apenas WPA2</b> (ou, por outras palavras, cifra AES)."
,"Modo WPA"
,"Apenas WPA2"
,"Apenas WPA"
,"Tipo de Cifra"
,"TKIP"
,"AES"
,"Chave Pré-partilhada"
,"Insira uma frase de segurança de 8 a 63 caracteres alfanuméricos. Para um bom nível de segurança, a frase deve ser longa e não ser comum."
,"Chave de rede"
,"(8~63 ASCII ou 64 HEX)"
,"EAP (802.1x)"
,"Quando está ativado WPA enterprise, o router usa EAP (802.1x) para autenticar os clientes através de um servidor RADIUS remoto."
,"Endereço IP do Servidor RADIUS"
,"Porta do servidor RADIUS "
,"Frase Secreta Partilhada do servidor RADIUS"
,"(13 ASCII ou 26 HEX)"
,"(5 ASCII ou 10 HEX)"
,"As configurações estarão ativas após reiniciar."
,"Tem a certeza de que quer alterar?"
,"Definição de Wi-Fi"
,"Nesta secção, pode configurar a interface sem fios (ponto de acesso) disponível no router."
,"Banda de 2.4 GHz"
,"Banda de 5 GHz"
,"Banda Sem Fios"
,"Ativar a Pesquisa Automática de Canal"
,"Largura de Canal"
,"20/40MHz (Auto)"
,"20/40/80MHz (Auto)"
,"Apenas 802.11b"
,"Apenas 802.11g"
,"Apenas 802.11n"
,"Mista 802.11g e 802.11b"
,"Mista 802.11n e 802.11g"
,"Mista 802.11n, 802.11g e 802.11b"
,"Apenas 802,11a"
,"Apenas 802.11n"
,"Mista 802.11a e 802.11n"
,"802.11 a/n/ac Mista"
,"o comprimento aplica-se a todas as chaves"
,"Comprimento da Chave WEP"
,"Aviso! A definição do modo de segurança da banda de 2,4GHz como \"NENHUMA\" irá provocar riscos de segurança. Ainda assim, prefere continuar para a respetiva configuração?"
,"É necessário parar a função WPS para ativar a definição WEP para a banda de 2,4GHz. Ainda assim, prefere continuar para a respetiva configuração?"
,"Aviso! A definição do modo de segurança da banda de 5GHz como \"NENHUMA\" irá provocar riscos de segurança. Ainda assim, prefere continuar para a respetiva configuração?"
,"É necessário parar a função WPS para ativar a definição WEP para a banda de 5GHz. Ainda assim, prefere continuar para a respetiva configuração?"
,"64Bit (10 dígitos hexadecimais)"
,"128Bit (26 dígitos hexadecimais)"
,"Aviso! A definição do modo de segurança da banda de 2,4GHz como \"NENHUMA\" irá provocar riscos de segurança. Ainda assim, prefere continuar para a respetiva configuração?"
,"Aviso! A definição do modo de segurança da banda de 5GHz como \"NENHUMA\" irá provocar riscos de segurança. Ainda assim, prefere continuar para a respetiva configuração?"
,"É necessário parar a função WPS para ativar a definição WEP para a banda de 2,4GHz. Ainda assim, prefere continuar para a respetiva configuração?"
,"É necessário parar a função WPS para ativar a definição WEP para a banda de 5GHz. Ainda assim, prefere continuar para a respetiva configuração?"
,"Auto (WPA ou WPA2)"
)

wps=new Array(
 "NÃO CONFIGURADA"
,"Definir"
,"CONFIGURADO"
,"Versão"
,"NÃO UTILIZADA"
,"INATIVO"
,"PROCESSFAIL"
,"STARTPROCESS"
,"RECVEAPOLSTART"
,"SENDEAPREQID"
,"RECVEAPRSPID"
,"RECVWRGVENDORID"
,"RECVWRGVENDORTYPE"
,"SENDEAPREQSTART"
,"SENDM1"
,"RECVM1"
,"SENDM2"
,"RECVM2"
,"RECVM2D"
,"SENDM3"
,"RECVM3"
,"SENDM4"
,"RECVM4"
,"SENDM5"
,"RECVM5"
,"SENDM6"
,"RECVM6"
,"SENDM7"
,"RECVM7"
,"SENDM8"
,"RECVM8"
,"PROCEAPRSPACK"
,"PROCEAPREQDONE"
,"PROCEAPRSPDONE"
,"SENDEAPFAIL"
,"ERRHASHFAIL"
,"ERRHMACFAIL"
,"ERRDEVPWDAUTHFAIL"
,"CONFIGURADO"
,"Configuração Protegida Wi-Fi"
,"WPS"
,"PIN AP"
,"Gerar Novo PIN"
,"Modo Config"
,"Registado"
,"Registador de domínios"
,"Estado Config"
,"Método Config"
,"Código PIN"
,"Botão de pressão"
,"Estado WPS"
,"Ativação"
,"A ler..."
,"Configuração Protegida Wi-Fi (WPS)"
,"WPS é um padrão para a configuração fácil e segura de uma ligação sem fios. Nesta secção, pode ativar o WPS para uma ligação cliente utilizando a segurança WPA/WPA2."
,"O comprimento do Código PIN deve ser = 4 ou 8"
,"Erro de regra de Código PIN!"
,"Desativar Método WPS-PIN"
,"O comprimento do Código PIN deve ser = 4 ou 8"
,"Erro de regra de Código PIN!"
)

wlpfe=new Array(
 "Definições Sem Fios Avançadas"
,"Intervalo de marcação"
,"(mseg, amplitude:10~1024)"
,"Energia de Transmissão"
,"Limite RTS"
,"(1~2347, predefinido 2347)"
,"Fragmentação"
,"(256~2346, predefinido 2346)"
,"Intervalo DTIM"
,"(intervalo: 1~255)"
,"Suporta WMM"
,"Taxas TX"
,"Especifique as definições de configuração avançadas para os raios de gateways nesta página. Se necessário, os valores predefinidos da segurança de AP e os parâmetros de associação podem ser modificados."
,"Definições Sem Fios 2.4G avançadas"
,"Definições Sem Fios 5G avançadas"
,"GI Curto"
,"Coexistência HT 20/40"
)

//---------------------------------LAN---------------------------------
devlist=new Array(
 "Lista de Clientes LAN"
,"Nome do Anfitrião (se existir)"
,"Endereço IP"
,"Endereço MAC"
)

lanst=new Array(
 "Definições do Router"
,"Utilize esta secção para configurar as definições de rede interna do seu router. O endereço IP que está configurado aqui é o endereço IP que utiliza para aceder a interface de gestão baseada na Web. Se alterar aqui o endereço IP, poderá necessitar de ajustar as definições de rede do seu computador para aceder novamente à rede."
,"Endereço IP do Router"
,"Máscara de Sub-rede Predefinida"
,"Nome do Domínio Local"
,"Definições do Servidor DHCP"
,"Utilize esta secção para configurar o servidor DHCP integrado para atribuir endereços IP aos computadores na sua rede."
,"Ativar Servidor DHCP"
,"Intervalo de Endereços IP DHCP"
,"a"
,"(endereços na sub-rede LAN)"
,"Tempo de Reserva DHCP"
,"Endereço IP do DNS preferido"
,"Endereço IP do DNS alternativo"
,"Endereço IP WINS preferido"
,"Endereço IP WINS alternativo"
,"A definição do endereço IP da LAN produz efeitos depois de reiniciar."
,"Tem a certeza de que quer alterar?"
,"O intervalo de agrupamento IP é inválido."
,"Endereço de Início de Agrupamento IP"
,"Endereço de Fim de Agrupamento IP"
,"O nome do Domínio Local é inválido."
,"Esta secção permite-lhe configurar as definições de rede local do seu router. Tenha em atenção que esta secção é opcional e não deve alterar nenhuma das definições para colocar a sua rede a funcionar."
,"Configuração da Interface de IP"
,"Servidor DHCP"
,"Configuração do Servidor DHCP"
,"Reserva DHCP"
)

//---------------------------------Advanced---------------------------------
ddns=new Array(
 "DNS Dinâmico"
,"Ativar DDNS"
,"Fornecedor"
,"DynDNS.org (Dinâmico)"
,"DynDNS.org (Personalizado)"
,"No-IP.com"
,"TZO.com"
,"dhs.org"
,"Nome do anfitrião"
,"Nome de utilizador / E-mail"
,"Palavra-passe / Chave"
,"A conversão do endereço IP para nomes/domínios de anfitrião e vice-versa é gerida pelo DNS. A informação necessária (endereço IP de, pelo menos, um servidor DNS) é normalmente disponibilizada pelo seu ISP. Mas o dispositivo também tem capacidade para detetar automaticamente os servidores DNS disponíveis."
)

spap=new Array(
 "Aplicações populares"
,"-- Selecione um --"
,"Battle.net"
,"Teclado de marcação"
,"ICU II"
,"Zona de Jogos MSN"
,"PC-para-Telefone"
,"Quick Time 4"
,"Regras da Aplicação"
,"Ativação"
,"Portas de entrada"
,"Aplicação"
,"As regras da porta de serviço do servidor virtual e da porta de entrada da aplicação não podem ser as mesmas."
,"O valor da Porta de Entrada não pode ser o mesmo"
)

dmz=new Array(
 "Definições de Firewall"
,"Ativar SPI"
,"Anfitrião DMZ"
,"A opção DMZ (Zona Desmilitarizada) permite-lhe definir um único computador na sua rede fora do router. Se tem um computador que não consegue executar aplicações de Internet de forma adequada a partir do router, pode colocar o computador em DMZ para um acesso à Internet sem restrições."
,"<b>Nota:</b> A colocação de um computador na DMZ pode expor esse computador a vários riscos de segurança. Recomenda-se a utilização desta opção apenas como último recurso."
,"Ativar DMZ"
,"Endereço IP da DMZ"
,"Nome do Computador"
)

smap=new Array(
 "Serviços conhecidos"
,"-- Selecione um --"
,"AUTH (113)"
,"DNS (53)"
,"FTP (21)"
,"ISAKMP (500)"
,"POP3 (110)"
,"PPTP (1723)"
,"SMTP (25)"
,"TELNET (23)"
,"WEB (80)"
,"Utilizar regra de agendamento"
,"---SEMPRE LIGADO---"
,"Lista de Servidores Virtuais"
,"Portas de Serviço"
,"IP do servidor: Porta"
,"Ativar"
,"Regra de Agendamento Número"
,"O externo funciona como um servidor. Recebe os pedidos dos utilizadores remotos no seu endereço IP público e reencaminha-os automaticamente para o Servidor Virtual. "
,"Assim, um cliente na sua rede, depois de um NAT ou firewall, pode disponibilizar serviços como Servidor Virtual. "
,"Pode apenas ativar portas específicas ou intervalos de portas e protocolos (UDP/TCP). A partilha de ficheiros ou de serviços web, por ex. HTTP, FTP ou POP3 são possíveis. Os endereços IP privados dos servidores na rede local permanecem seguros. Se possuir um endereço IP dinâmico, pode pretender ativar um serviço DynDNS adicional."
,"O valor da Porta de Serviço não pode ser o mesmo."
,"erro de definição"
)

uctl=new Array(
 "Definição de Filtragem de URL"
,"Filtragem de URL"
,"Ativar"
,"Regras de Filtragem de URL"
,"URL"
,"Ativar"
,"O URL não pode ficar vazio!!"
,"http://' não é permitido!"
,"O Filtro de URL disponibiliza as ferramentas úteis para restringir o acesso à Internet. "
,"O Bloqueio de URL de Páginas de Internet permite-lhe criar rapidamente uma lista de todos os sítios da Internet que pretende permitir ou negar o acesso de utilizadores."
,"Filtro URL"
)

rtab=new Array(
 "Definição RIP"
,"RIP"
,"Ativar"
,"RIPv1"
,"RIPv2"
,"Regras de Encaminhamento"
,"Destino"
,"Máscara de Sub-rede"
,"Gateway"
,"Salto"
,"As rotas para o tráfego na sua rede são definidas pela tabela de encaminhamento. Normalmente, as entradas para o endereço IP e o Gateway são suficientes. Não é necessário configurar qualquer definição."
)

qos=new Array(
 "Alta"
,"Normal"
,"Baixa"
,"Configuração do Motor QoS"
,"Ativar Filtro de Pacote QoS"
,"Largura de banda a montante"
,"Largura de banda a jusante"
,"kbps"
,"Utilizar regra de agendamento"
,"---SEMPRE LIGADO---"
,"Regras QoS"
,"IP Local: Portas"
,"IP Remoto: Portas"
,"Prioridade QoS"
,"Ativar"
,"Utilizar Regra número"
,"Configuração do Motor QoS"
)

pmac=new Array(
 "Definições de Filtragem MAC"
,"Controlo de Endereço MAC"
,"Ativar"
,"Controlo de ligação"
,"Os clientes com e sem fios com <b>C</b> assinalado podem ligar a este dispositivo; e "
,"permitir"
,"recusar"
," a ligação de endereços MAC não especificados."
,"Controlo de Associação"
,"Clientes sem fios com <b>A</b> assinalado podem associar-se à rede sem fios LAN; e "
,"permitir"
,"recusar"
," a associação de endereços MAC não especificados."
,"Clientes DHCP"
,"-- Selecione um --"
,"Regras de Filtragem MAC"
,"Endereço MAC"
,"Endereço IP"
,"C"
,"A"
)

iopf=new Array(
 "Definição do Filtro Externo"
,"Definição do Filtro Interno"
,"Filtro Externo"
,"Filtro Interno"
,"Ativar"
,"Utilizar regra de agendamento"
,"---SEMPRE LIGADO---"
,"Lista de Regras de Filtro Externo"
,"Lista de Regras de Filtro Interno"
,"Permitir a passagem a todos exceto aos que cumprem as seguintes regras."
,"Recusar a passagem a todos exceto aos que cumprem as seguintes regras."
,"IP de Origem: Portas"
,"IP de Destino: Portas"
,"Ativar"
,"Regra de Agendamento Número"
,"Utilize o erro de número de regra!!"
)

snmp=new Array(
 "SNMP"
,"SNMP Local"
,"SNMP Remoto"
,"Obter Comunidade"
,"Definir Comunidade"
,"IP 1"
,"IP 2"
,"IP 3"
,"IP 4"
,"Versão SNMP"
,"V1"
,"V2c"
,"Endereço IP de Acesso WAN"
)

fmisc=new Array(
 "UPNP"
,"Universal Plug and Play(UPnP) suporta a funcionalidade Plug and Play ponto-a-ponto para dispositivos de rede."
,"Ativar UPnP"
,"PING WAN"
,"Se ativar esta função, a porta WAN do seu router responderá aos pedidos de ping a partir da Internet que sejam enviados para o endereço IP da WAN.‎"
,"Ativar Resposta Ping da WAN"
)

networkscan=new Array(
 "Seleção do Fornecedor de Rede"
,"Esta página irá pesquisar fornecedores de rede nas proximidades.<br>Por favor aguarde um pouco para cada pesquisa."
,"Método de Seleção de Rede 3G/4G"
,"Em progresso..."
,"Lista de Fornecedores de Rede"
,"Não existe qualquer fornecedor de rede"
,"Se não escolher Fornecedores de Rede, o modo altera para Automático"
,"As suas alterações foram guardadas. O router deve ser reiniciado para as alterações terem efeito."
,"Pode reiniciar agora ou pode continuar a fazer outras alterações e reiniciar mais tarde."
,"Disponível"
,"Atual"
,"Proibido"
,"Digitalizar"
,"Network Selection Method"
)

//---------------------------------System---------------------------------
sntp=new Array(
 "Configuração de Hora e Data"
,"Hora"
,"Fuso Horário"
,"Ativar Hora de Verão"
,"Sincronizar as definições da hora do seu computador"
,"Configuração automática de Hora e Data"
,"Sincronizar automaticamente com servidor horário na Internet"
,"Servidor NTP Utilizado"
,"Atualizar Agora"
,"Sinc. RESULTADO"
,"Início"
,"Fim"
,"Horas"
,"Dia"
,"Mês"
,"(Hora/Dia/Mês)"
,"Jan"
,"Fev"
,"Mar"
,"Abr"
,"Maio"
,"Jun"
,"Jul"
,"Ago"
,"Set"
,"Out"
,"Nov"
,"Dez"
,"Dom"
,"Seg"
,"Ter"
,"Qua"
,"Qui"
,"Sex"
,"Sáb"
,"A opção Configuração de Hora permite-lhe configurar, atualizar e manter a hora correta no sistema do relógio interno."
,"A partir desta secção, pode definir o fuso horário no qual que se encontra e definir o servidor NTP (Protocolo de Sincronização em Rede)."
,"A Hora de Verão também pode ser configurada para ajustar automaticamente a hora quando necessário."
,"Hora"
,"Definições da Hora"
)

tz=new Array(
 "* Ainda não configurado! A predefinição é GMT+00:00"
,"Linha Internacional de Data Oeste"
,"Midway Island, Samoa"
,"Havai"
,"Alasca"
,"Hora do Pacífico (EUA e Canadá)"
,"Tijuana"
,"Arizona"
,"Chihuahua, La Paz, Mazatlan"
,"Hora da Montanha (EUA e Canadá)"
,"América Central"
,"Hora Central (EUA e Canadá)"
,"Guadalajara, México, Monterrey"
,"Saskatchewan"
,"Bogotá, Lima, Quito"
,"Hora Oriental (EUA e Canadá)"
,"Indiana (Este)"
,"Hora do Atlântico (Canadá)"
,"Caracas, La Paz"
,"Santiago"
,"Terranova"
,"Brasília"
,"Buenos Aires, Georgetown"
,"Gronelândia"
,"Atlântico Médio"
,"Açores"
,"Ilhas de Cabo Verde"
,"Casablanca, Monróvia"
,"Dublin, Edimburgo, Lisboa, Londres"
,"Amesterdão, Berlim, Berna, Roma, Estocolmo, Viena"
,"Belgrado, Bratislava, Budapeste, Ljubljana, Praga"
,"Bruxelas, Copenhaga, Madrid, Paris"
,"Sarajevo, Skopje, Varsóvia, Zagreb"
,"África Central Ocidental"
,"Atenas, Beirute, Istambul, Minsk"
,"Bucareste"
,"Cairo"
,"Harare, Pretória"
,"Helsínquia, Kiev, Riga, Sofia, Tallinn, Vílnius"
,"Jerusalém (apenas 2007)"
,"Bagdade"
,"Kuwait, Riyadh"
,"Moscovo, S. Petersburgo, Volgogrado"
,"Nairobi"
,"Teerão"
,"Abu Dhabi, Muscat"
,"Baku"
,"Tbilisi"
,"Yerevan"
,"Kabul"
,"Ecaterimburgo"
,"Islamabad, Karachi, Tashkent"
,"Chennai, Kolkata, Mumbai, Nova Deli"
,"Kathmandu"
,"Almaty, Novosibirsk"
,"Astana, Dhaka"
,"Colombo"
,"Rangoon"
,"Banguecoque, Hanói, Jacarta"
,"Krasnoyarsk"
,"Pequim, Chongqing, Hong Kong, Urumqi"
,"Irkutsk"
,"Kuala Lumpur, Singapura"
,"Perth, Austrália Ocidental"
,"Taipei"
,"Ulaan Bataar"
,"Osaka, Sapporo, Tóquio"
,"Seul"
,"Yakutsk"
,"Adelaide"
,"Darwin"
,"Brisbane"
,"Camberra, Melbourne, Sidney"
,"Guam, Port Moresby"
,"Hobart"
,"Vladivostok"
,"Magadã, Ilhas de Salomão, Nova Caledónia"
,"Auckland, Wellington"
,"Fiji, Kamchatka, Ilhas Marshall"
,"Nuku'alofa"
,"* A configurar manualmente a variável TZ..."
,"Eniwetok, Kwajalein"
,"Cidade do México, Tegucigalpa"
,"Bruxelas, Copenhaga, Madrid, Paris, Vílnius"
,"Sarajevo, Skopje, Sófia, Varsóvia, Zagreb"
,"Atenas, Beirute, Cairo, Istambul, Minsk"
,"Pequim, Hong Kong, Taipei"
,"Índia"
)

atbox=new Array(
 "Administrador (o nome de utilizador predefinido é "
,")"
,"Nome de Início de Sessão"
,"Nova Palavra-passe"
,"Confirmar Palavra-passe"
,"Gestão remota"
,"Ativar Gestão Remota"
,"IP Com Permissão para Aceder"
,"Porta"
,"As novas palavras-passe de Administrador não são idênticas!"
,"Pretende guardar a sua palavra-passe como palavra-passe vazia?"
,"A Porta de Gestão Remota deve ser maior que 1024."
,"Administrador"
,"Aqui, pode alterar a palavra-passe para o administrador."
,"O nome de utilizador (admin) não pode ser alterado."
,"Definições de Administrador"
,"SSH"
,"Ativar SSH"
,"Permitir Wan"
,"Telnet"
,"Ativar Telnet"
,"Remote Administration"
)

rebo=new Array(
 "Atualização bem-sucedida!"
,"Ficheiro de atualização inválido!"
,"Certifique-se de que selecionou o ficheiro correto."
,"Este ficheiro não é compatível com o firmware ou o hardware atuais."
,"Não é permitido atualizar para esta versão!"
,"O processo de atualização foi cancelado por razões desconhecidas."
,"Tente novamente!"
,"Todas as definições foram restabelecidas!"
,"O dispositivo está a reiniciar..."
,"Por favor <font color=red><b>NÃO DESLIGUE</b></font> o dispositivo."
,"E aguarde durante "
," segundos..."
,"Ligue novamente manualmente."
,"Nota! O seu IP LAN pode alterar. Por favor ligue novamente."
,"Clique aqui para ligar novamente"
,"O sistema está pronto"
,"Reiniciar Router"
,"Mensagem de Estado"
,"O router estará funcional em"
,"Reiniciar Agora"
,"Reiniciar Mais Tarde"
)

system=new Array(
 "Restabelecer todas as definições para as predefinições?"
,"Guardar e Restaurar Definições"
,"Guardar as Definições no Disco Rígido Local"
,"Guardar"
,"Carregar as Definições a partir do Disco Rígido Local"
,"Carregar Definições"
,"Repor as Definições Predefinidas de Origem"
,"Restaurar para predefinições"
,"Ficheiro de atualização inválido!"
,"Ficheiro de atualização não permitido!"
,"Sistema"
,"Todas as definições serão automaticamente guardadas no seu dispositivo. Não é necessário guardar ou reiniciar manualmente. Se pretender reiniciar o dispositivo ainda assim, é aconselhável fazê-lo através do botão \"Reiniciar\" button."
,"Configurações do Sistema"
,"Reiniciar o Dispositivo"
,"Restabelecer todas as definições para as predefinições de fábrica?"
,"Reiniciar"
,"Reiniciar e Repor"
)

fwug=new Array(
 "Informações de Firmware"
,"Versão do Firmware Atual"
,"Data do Firmware Atual"
,"Atualização de Firmware"
,"Nota! Não desligue o dispositivo durante a atualização."
,"O procedimento para atualização demora cerca de 180 segundos."
,"Quando a atualização estiver concluída, o dispositivo reiniciará automaticamente."
,"Para atualizar o firmware, o seu PC tem de ter uma ligação com fios ao router. Introduza o nome do ficheiro de atualização do firmware e clique no botão Carregar."
,"Carregar"
,"Atualizar"
,"Nome de ficheiro incorreto"
,"Apenas são aceites ficheiros .bin."
,"Cancelar"
,"Está em curso outra atualização do firmware!"
,"Aceitar firmware não oficial."
,"Utilize o botão \"Atualizar\" para atualizar a versão do firmware para o seu dispositivo."
,"Atualização do Firmware"
,"Selecionar Firmware"
,"verificar Arquivo"
,"Nova informação de firmware"
,"Nova versão do firmware"
,"New Firmware Date"
)

logs=new Array(
 "Definições do SysLog"
,"Ativar o Registo no Servidor de Registo de Sistema"
,"Endereço IP do Servidor de Registo de Sistema"
,"Definições de E-mail"
,"Ativar Notificação de E-mail"
,"Porta e IP do Servidor SMTP"
,"Enviar alerta por E-mail para"
,"Assunto do E-mail"
,"Nome de utilizador SMTP"
,"Palavra-passe de SMTP"
,"Registar E-mail agora"
,"Uma mensagem de e-mail encontra-se na fila para enviar..."
,"Registo do Sistema"
,"O Registo do Sistema permite-lhe configurar o início de sessão local, remoto e de e-mail, além de visualizar os registos que foram criados."
,"Clear logs"
,"Log Number"
,"Message"
,"View Logs"
)

smsmsg=new Array(
 "Responder a Mensagem"
,"Reencaminhar Mensagem"
,"Criar Mensagem"
,"Mensagem de texto"
,"A introduzir mensagem..."
,"O comprimento máximo de uma mensagem é de 160 caracteres."
,"Recetor"
,"Acrescente \"+\" para o formato internacional do número de telefone."
,"Enviar"
,"A ler... Aguarde um momento..."
,"Comprimento atual do texto inserido"
,"Enviar mensagem"
,"Se pretende criar e enviar uma mensagem SMS, clique no botão abaixo."
,"O Destinatário não pode ficar vazio!"
,"The max. length of a message is 160 characters for pure alphabetical or numeric."
)

smsinbox=new Array(
 "Estado do SMS"
,"SMS recebido"
,"Novo SMS"
,"Capacidade Total"
,"Caixa de entrada"
,"De"
,"Marca da data/hora"
,"Texto"
,"SMS"
,"A ler... Aguarde um momento..."
,"Responder"
,"Reencaminhar"
,"Caixa de entrada de SMS"
,"Se pretende visualizar uma mensagem SMS, clique no botão abaixo."
,"Definição de SMSC"
,"Verifique se o cartão SIM está inserido."
,"O cartão SIM está bloqueado! Não é possível ler SMS do cartão SIM."
,"O Modem não está Pronto!"
,"O Modem está ocupado por uma chamada telefónica! Aguarde por favor..."
,"Envio bem sucedido!"
,"Envio falhado!"
,"O Modem está ocupado por uma chamada telefónica! O SMS será automaticamente enviado mais tarde."
,"Eliminação bem sucedida!"
,"Eliminação falhada!"
,"Comando AT falhou!"
,"O Modem está ocupado por uma chamada telefónica! O SMS será automaticamente eliminado mais tarde."
)

voiceforwd=new Array(
 "Todas as chamadas"
,"Sem Resposta"
,"Não é possível estabelecer a ligação"
,"Ocupado"
,"Estado"
,"Não registado"
,"Registar"
,"Ativar"
,"Desativar"
,"Número"
)

pinco=new Array(
 "A consultar estado... Aguarde um momento..."
,"Código PIN do cartão SIM"
,"Introduza 4~8 caracteres no campo do código PIN do cartão SIM!"
,"Função de Pedido de CÓDIGO PIN"
,"Introduzir código PIN do cartão SIM"
,"A alterar Código PIN..."
,"Bem sucedido!"
,"Introduza 4~8 caracteres no campo do Antigo código PIN!"
,"Introduza 4~8 caracteres no campo do Novo código PIN!"
,"Introduza 4~8 caracteres no campo de Verificar o código PIN!"
,"Função de Alterar CÓDIGO PIN"
,"Antigo Código PIN"
,"Novo Código PIN"
,"Verificar Código PIN"
,"Guardar!"
,"Introduza o Código PIN para desbloquear o cartão SIM"
,"CÓDIGO PIN"
,"Introduza o Código PUK para desbloquear o cartão SIM"
,"CÓDIGO PUK"
,"Novo CÓDIGO PIN"
,"A função já está desativada!"
,"A função já está ativada!"
,"Código PIN errado!"
,"É necessário ativar primeiro a função de pedido de Código PIN!"
,"Introduziu dois novos códigos PIN diferentes!"
,"Antigo Código PIN errado!"
,"Código PUK errado!"
,"Comando AT falhou!"
,"Pronto"
,"Bloqueado pelo PIN do cartão SIM"
,"Bloqueado pelo PUK do cartão SIM"
,"O cartão SIM apresenta alguns erros."
,"O Modem não respondeu."
,"O envio do comando AT falhou!"
,"O Modem não existe! Verifique se o cartão SIM está inserido!"
,"Aviso: mais 3 tentativas permitidas."
,"Tente novamente"
,"Continuar"
,"Aviso: "
," tentativas mais permitidas."
,"Introduza 4~8 caracteres no campo do CÓDIGO PIN!"
,"Introduza 8 caracteres no campo do CÓDIGO PUK!"
,"Controlo de PIN"
,"O Modem está a inicializar, por favor aguarde um minuto!"
,"Configuração do PIN"
,"Insira o código PIN 3 vezes falhar! Por favor, insira o código PUK."
)

ussd=new Array(
 "USSD"
,"Enviar"
,"ERRO"
)

scherebo=new Array(
 "Repor Ligação"
,"Reinício Automático"
,"Reiniciar-Agendamento"
,"Agendamento diário"
,"Agendamento Semanal Dia da Semana"
,"Dia do Mês"
)

sche=new Array(
 "Regra de Agendamento"
,"Ativar Agendamento"
,"Número de Regra"
,"Nome de Regra"
,"Ação"
,"Nenhuma regra adicionada, adicione regras antes de ativar!"
,"Tem a certeza de que pretende eliminar a regra "
,"??"
,"Agendamento"
)

rule=new Array(
 "O nome da regra não pode estar vazio!"
,"O nome do agendamento está duplicado com outra regra!"
,"(Regra:"
,")"
,"Verifique novamente!"
,"Hora de Início do dia da semana "
," é inválida!"
,"Hora de Fim do dia da semana "
," é inválida!"
,"Hora do dia da semana "
," é inválida!"
,"A hora de fim deve ser posterior à hora de início"
,"(O formato da hora do agendamento deve ser hh:mm)"
,"(0 < As horas da hora de início < 23 )"
,"(0 < Os minutos da hora de início < 59 )"
,"(0 < As horas da hora de fim < 23 )"
,"(0 < Os minutos da hora de fim < 59 )"
,"Selecione o dia da semana em ID de regra "
,"!!"
,"A hora da regra do Agendamento está vazia!!"
," Introduza, pelo menos, um agendamento!!"
,"Todos os Dias"
,"Domingo"
,"Segunda-feira"
,"Terça-feira"
,"Quarta-feira"
,"Quinta-feira"
,"Sexta-feira"
,"Sábado"
,"Definição de Regra de Agendamento"
,"Nome da Regra"
,"-- Selecione um --"
,"Política"
,"Voltar"
,"Inativar"
,"Ativar"
,"exceto os dias e as horas selecionados abaixo."
,"Dia da Semana"
,"Hora de Início (hh:mm)"
,"Hora de Fim (hh:mm)"
)

diagnostic=new Array(
 "Informação de serviço"
,"Operador"
,"Difusão de Célula"
,"MCC"
,"MNC"
,"LAC"
,"Tipo de Serviço"
,"Modo de Serviço Preferido"
,"Apenas GSM"
,"Apenas WCDMA"
,"Desconhecido"
,"Ligação PS (DADOS)"
,"Ligação CS (VOZ)"
,"IMSI"
,"SMSC"
,"Ligado"
,"Separado"
,"Estado do SIM"
,"Bloqueio do Código PIN"
,"Vezes para Repetir Código PIN"
,"Vezes para Repetir Código PUK"
,"Estado do módulo"
,"IMEI"
,"Versão FW"
,"Nome do módulo"
,"ID da célula"
)

voice=new Array(
 "Voz"
,"Reencaminhamento de Chamadas"
,"Reencaminhamento automático de chamadas recebidas para um número designado em condições diferentes."
,"Chamada em Espera"
,"Suspender a chamada em espera e possibilidade de falar numa nova chamada recebida."
,"Reencaminhamento de Chamada efetuada"
,"Colocação em Espera de Chamada efetuada"
)

sms=new Array(
 "Criar Mensagem"
,"Permite-lhe criar e enviar novas mensagens SMS."
,"caixa de entrada"
,"Permite-lhe ler novas mensagens SMS e eliminar/reencaminhar mensagens existentes."
,"Só pode responder a uma mensagem de cada vez!"
)

tr069=new Array(
 "TR-069"
,"TR-069 Setting"
,"ACS Setting"
,"ACS URL"
,"ACS UserName"
,"ACS Password"
,"CPE Setting"
,"ConnectionRequest Port"
,"ConnectionRequest UserName"
,"ConnectionRequest Password"
,"Inform Setting"
,"Inform"
,"Interval"
,"Interface"
)
