//Spanish
common=new Array(
 "Actualizar"
,"Ayuda"
,"Cierre de sesión"
,"Activar"
,"Desactivar"
,"Elemento"
,"Editar"
,"Eliminar"
,"Atrás"
,"Automático"
,"Manual"
,"Aplicar"
,"Restablecer"
,"Añadir"
,"segundos"
,"bytes"
,"ID"
,"Copiar a"
,"Página anterior"
,"Página siguiente"
,"Añadir nueva regla..."
,"Mejor"
,"minutos"
,"Activado"
,"Desactivado"
,"First Page"
,"Last Page"
,"Download"
,"Page"
)

others=new Array(
 "Reiniciar"
,"¿Reiniciar el router?"
,"Ha cerrado la sesión"
,"Página del producto"
,"Versión del firmware"
,"copyright"
,"Sugerencias útiles."
,"Más información..."
,"Guardar parámetros"
,"No guardar parámetros"
,"Sin cambios"
,"Sin cambios."
,"Continuar"
,"Parámetros guardados"
,"El cambio será efectivo inmediatamente."
,"Configuración finalizada"
,"El sistema está procesando, espere unos segundos ..."
,"ROUTER"
,"Nombre de usuario"
,"Contraseña"
,"Inicio de sesión"
,"Nombre de usuario o contraseña no válidos"
,"Introduzca un nombre de usuario válido."
,"Nombre de usuario o contraseña no válidos"
,"Ha cerrado la sesión satisfactoriamente."
,"Ha cerrado la sesión."
,"Antes inicie la sesión."
,"Introduzca un nombre de usuario válido"
,"Introduzca una contraseña válida"
,"Introduzca el nombre de usuario."
,"El valor introducido no puede estar vacío."
,"Espere unos segundos ..."
,"El administrador de la cuenta ya logined"
,"¿Acepta?"
)

dirary0=new Array(
 "Inicio"
,"Internet"
,"Wi-Fi"
,"LAN"
,"Avanzado"
,"Sistema"
,"Servicio WAN"
,"Conmutación por error"
,"IPv6"
,"Lista de dispositivos"
,"Parámetros de Wi-Fi"
,"WPS"
,"Wi-Fi avanzado"
,"Parámetros de LAN"
,"DHCP"
,"DNS"
,"Aplicaciones"
,"DMZ"
,"Servidor virtual"
,"Filtro de URL"
,"Enrutamiento"
,"Calidad de servicio"
,"Filtro de dirección MAC"
,"Filtro de salida"
,"Filtro de entrada"
,"SNMP"
,"Red avanzada"
,"Parámetros de hora"
,"Administración"
,"Reiniciar y restablecer"
,"Actualización de firmware"
,"Registros de sistema"
,"Programas"
,"Asistente"
,"Escaneado Por Red"
,"Reinicio de la conexión"
,"Configuración de PIN"
,"Servicio de mensajes"
,"Bandeja de entrada de SMS"
,"Crear mensaje"
,"Voz"
,"Envío de llamada"
,"Llamada en espera"
,"Diagnóstico"
,"TR-069"
,"WAN MULTIPLE"
)

valchk=new Array(
 "Compruebe de nuevo la configuración."
,"La dirección IP no es válida."
,"La máscara de subred no es válida."
,"El rango de la dirección IP no es válido."
,"La dirección IP de LAN no es válida."
,"el valor no es válido."
,"El puerto no es válido."
,"(Ejemplo de formato: 1-65.535.777)"
,"El rango de puerto no es válido. (Ejemplo de formato: 1-65.535)"
,"El MTU no es válido."
,"La hora no es válida."
,"La hora no es válida."
,"La dirección MAC no es válida."
,"La clave WEP no es válida."
,"La clave precompartida no es válida."
,"El correo electrónico no es válido."
,"Introduzca 10 o 26 dígitos hexadecimales en el campo Clave WEP."
,"Introduzca 5 o 13 caracteres ASCII en el campo Clave WEP."
,"Introduzca 64 dígitos hexadecimales u 8~63 caracteres ASCII en el campo Clave precompartida."
,"Introduzca 64 dígitos hexadecimales en el campo Clave precompartida."
," no es válida."
)

//---------------------------------status---------------------------------
sta=new Array(
 "General"
,"Hora"
,"Versión del firmware"
,"WAN"
,"Tipo de conexión"
,"IP estática"
,"Dirección MAC"
,"Dirección IP"
,"Máscara de subred"
,"Puerta de enlace predeterminada"
,"Servidor DNS"
,"Cliente DHCP"
,"Estado de red"
,"Cliente desconectado"
,"Conectando..."
,"Establecido"
,"Desconectando..."
,"Espere mientras haya tráfico..."
,"Tiempo de validez restante"
,"Renovar"
,"Liberar"
,"PPPoE"
,"Desconectado"
,"Tiempo de conexión"
,"Conectar"
,"Desconectar"
,"Reconectar"
,"PPTP"
,"L2TP"
,"4G LTE /3G"
,"Potencia de la señal"
,"Información de la tarjeta"
,"Estado del enlace"
,"Error de autenticación"
,"Se necesita PIN"
,"Error de contraseña"
,"No se ha detectado ningún módem"
,"No se ha podido conectar. Compruebe los parámetros e inténtelo de nuevo."
,"Nombre de red"
,"LAN"
,"Servidor DHCP"
,"LAN inalámbrica"
,"Inalámbrico"
,"SSID"
,"Seguridad"
,"Abierto"
,"Compartida"
,"Automático"
,"WPA-PSK"
,"WPA"
,"WPA2-PSK"
,"WPA2"
,"WPA-PSK / WPA2-PSK"
,"WPA/WPA2"
,"Ninguno"
,"WEP"
,"TKIP"
,"AES"
,"TKIP/AES"
,"Canal"
,"Automático"
,"Modo 802.11"
,"B/G combinado"
,"Modo N"
,"B/G/N combinado"
,"Configuración protegida Wi-Fi"
,"Ordenadores LAN"
,"Nombre"
,"MAC"
,"Día"
,"Hora"
,"Min"
,"S"
,"N/A"
,"Conmutación por error 3G"
,"Tarjeta 3G"
,"Internet"
,"SSID2"
,"Clientes totales"
,"Grupo DHCP"
,"Nombre del sistema"
,"Tiempo de actividad del sistema"
,"Versión de HW"
,"Versión de SW"
,"Conmutación por error"
,"Cargar recursos compartidos"
,"Tipo de servicio"
,"Teléfono"
,"No Servicio"
,"Estado"
)

//---------------------------------Internet---------------------------------
prim=new Array(
 "Tipo de conexión a Internet"
,"Mi conexión a Internet es"
,"IP estática"
,"IP dinámica (DHCP)"
,"PPPoE (nombre de usuario/contraseña)"
,"PPTP (Nombre de usuario / Contraseña)"
,"L2TP (Nombre de usuario / Contraseña)"
,"4G LTE /3G"
,"Copia de seguridad automática"
,"Activar comprobación de WAN con cables activa"
,"Host de Internet"
,"Introduzca una dirección IP en Internet."
,"Tipo de conexión de Dirección IP estática a Internet"
,"Dirección IP"
,"Máscara de subred"
,"Puerta de enlace predeterminada"
,"Servidor DNS primario"
,"Servidor DNS secundario"
,"MTU"
,"(bytes) Predeterminado de MTU = 1500"
,"Dirección MAC"
,"Clonar"
,"Borrar"
,"Tipo de conexión de IP dinámica (DHCP) a Internet"
,"Nombre de host"
,"Reconexión automática"
,"PPPoE"
,"Nombre de usuario"
,"Contraseña"
,"Verificar contraseña"
,"Nombre del servicio"
,"(opcional)"
,"Dirección IP"
,"Tiempo de inactividad máximo"
,"(bytes) Predeterminado de MTU = 1.492"
,"PPTP"
,"Modo de dirección"
,"IP dinámica"
,"IP estática"
,"Dirección IP de PPTP"
,"Máscara de subred PPTP"
,"Dirección IP de puerta de enlace PPTP"
,"Dirección IP del servidor PPTP"
,"Modo de reconexión"
,"Siempre activado"
,"Conexión a petición"
,"L2TP"
,"Dirección IP L2TP"
,"Máscara de subred L2TP"
,"Dirección IP de puerta de enlace L2TP"
,"Dirección IP del servidor L2TP"
,"Tipo de conexión a Internet 4G LTE /3G"
,"Nombre de cuenta/perfil"
,"Número marcado"
,"Autenticación"
,"PAP"
,"CHAP"
,"APN"
,"Código PIN"
,"Mantener activo"
,"Desactivar"
,"Utilizar ping"
,"DNS Query"
,"Utilizar solicitud de eco LCP"
,"Intervalo de eco LCP:"
,"Error de eco LCP:"
,"veces"
,"Dirección IP de solicitud ping"
,"Intervalo de solicitud ping"
,"Puertos Ethernet en modo Bridge"
,"Se ha cambiado la dirección MAC"
,"La nueva dirección MAC será efectiva después de reiniciar."
,"¿Reiniciar inmediatamente?"
,"Roaming"
,"Comprobación DNS"
,"Desactivación NAT"
,"Modo automático"
,"Modo Solo 4G"
,"Modo Solo 3G"
,"Modo Solo 2G"
,"Tipo de servicio preferido"
,"Configuración de servicio WAN"
,"opcional"
,"Puente transparente"
,"Interfaz WAN"
,"Cerrar"
,"WAN Ethernet"
,"Perfil de marcación"
,"Detección automática"
,"País"
,"Empresa de telecomunicaciones"
,"Red"
,"Otros"
,"Configuración de red"
,"Las nuevas contraseñas no son idénticas."
,"parámetro no válido."
,"Modo automático"
,"Modo de preferencia 3G"
,"Primer modo 2G"
,"Cargando"
,"Red 3G/4G"
,"WCDMA/HSP"
,"CDMA2000/EV-DO"
,"La dirección IP y la puerta de enlace predeterminada no son válidas."
,"El rango del tiempo de inactividad máximo debe estar entre"
,"Tipo de conexión a Internet 4G"
,"VLAN Tagging"
)

failover=new Array(
 "Parámetro de conmutación por error"
,"Tipo de conmutación por error"
,"Host remoto para mantener activo"
,"Lista de conmutación por error"
,"Interfaz"
,"Cambiar"
,"Conexión actual a Internet es"
,"El tipo de Internet con conmutación por error es"
,"Conmutación por error"
,"Tipo de conexión con conmutación por error"
,"Parámetro de interfaz de conmutación por error"
,"¿Está seguro de que desea eliminar la WAN secundaria?"
,"Configuración de copia de seguridad automática"
,"Copia de seguridad automática"
,"Host remoto para mantener activo"
,"Lista de conexiones WAN"
,"Interfaz"
,"Cambie o elimine la interfaz."
,"Host remoto para mantener activo no puede ser nulo."
,"Selección no válida."
,"WAN primaria"
,"WAN secundaria"
,"Si cambia el tipo de WAN, se borrarán todos los parámetros de conmutación por error.\n¿Acepta?"
,"Cargar recursos compartidos"
,"Parámetro de conmutación por error..."
,"Tipo de conexión de Cargar recursos compartidos"
,"Dirección IP dinámica"
,"Dirección IP estática"
,"Puerto 1"
,"Puerto 2"
,"¡Seleccione una WAN secundaria!"
,"Al activar los puertos Bridge Ethernet se desactivará Ethernet WAN."
)

ipv6=new Array(
 "Parámetros 6 a 4"
,"Dirección 6 a 4"
,"Dirección DNS primaria"
,"Dirección DNS secundaria"
,"Parámetros de la dirección IPv6 de LAN"
,"Dirección IPv6 de LAN"
,"Dirección de enlace local IPv6 de LAN"
,"Parámetros de configuración automática de la dirección"
,"Configuración automática"
,"Tipo de configuración automática"
,"Duración del anuncio del router"
,"Dirección IPv4 remota"
,"Dirección IPv4 local"
,"Dirección IPv6 local"
,"Configuración de IPv6"
,"Conexión IPv6"
,"Sin estado"
,"Con estado (DHCPv6)"
,"Utilice la sección para configurar los parámetros de red interna del router. La dirección local del enlace de IPv6 de LAN es la dirección IPv6 que utiliza para acceder a la interfaz de gestión basada en la web. Si cambia aquí la dirección IPv6 de LAN, puede que necesite ajustar los parámetros de red del PC para acceder de nuevo a la red."
,"Activar DHCP-PD"
,"Parámetros de la configuración automática de la dirección de LAN"
,"Utilice esta sección para configurar la configuración automática de IPv6 a fin de que asigne las direcciones IP a los ordenadores de su red."
,"Activar configuración automática"
,"SLAAC+DHCPv6 sin estado"
,"Dirección de enlace local IPv6 de LAN"
,"Utilice esta sección para configurar su tipo de conexión IPv6. Si no está seguro del método de conexión, póngase en contacto con su proveedor de servicios de Internet."
,"Al configurar el router para acceder a Internet IPv6, asegúrese de seleccionar el tipo de conexión IPv6 correcto en el menú desplegable. Si no está seguro de la opción que debe elegir, póngase en contacto con su Proveedor de servicios de Internet (ISP)."
,"Elija el modo que va a utilizar el router para conectar al IPv6 de Internet."
,"Configuración automática (SLAAC/DHCPv6)"
,"IPv6 sobre túnel IPv4"
,"6rd"
,"Sólo enlace local"
,"Información de conexión IPv6"
,"Tipo de conexión IPv6"
,"Estado de red"
,"Dirección IPv6 de WAN"
,"Puerta de enlace predeterminada de IPv6"
,"Servidor DNS IPv6 primario"
,"Servidor DNS IPv6 secundario"
,"Dirección de enlace local IPv6 de LAN"
,"DHCP-PD"
,"Red IPv6 asignada por DHCP-PD"
,"Dirección IPv6 de LAN"
,"Dirección IPv6"
,"Nombre (si hubiera)"
,"IPv6 estática"
,"DHCPv6"
,"6 a 4"
,"PPPoA"
,"*Botón de conexión para IPv4 e IPv6"
,"*Botón de desconexión para IPv4 e IPv6"
,"Dirección IPv6 global"
,"Parámetros de dirección IPv6 de WAN"
,"Longitud del prefijo de subred"
,"Parámetros PPPoE o parámetros PPPoA"
,"Parámetros de IPv6 sobre túnel IPv4"
,"Dirección IPv6 remota"
,"Parámetros de DNS IPv6"
,"Configuración de DNS"
,"Obtenga automáticamente la dirección del servidor DNS"
,"Utilice la siguiente dirección de DNS"
,"Parámetros 6rd"
,"Longitud de máscara IPv4"
,"Prefijo remoto"
,"Longitud del prefijo"
,"Rango de dirección IPv6 (inicio)"
,"Rango de dirección IPv6 (final)"
,"Duración de la dirección IPv6"
,"Activación de DS-Lite"
,"Configuración de DS-Lite"
,"Opción DHCPv6 de DS-Lite"
,"Configuración manual"
,"Dirección de enlace local de WAN"
,"IPv6 dinámica"
,"Transferencia IPv6"
,"La dirección de WAN IPv4 no es una dirección global."
,"WAN IPv6 Address Status"
)

//---------------------------------WiFi---------------------------------
wpa=new Array(
 "Parámetros de red inalámbrica"
,"Activar inalámbrica"
,"Nombre de la red inalámbrica"
,"(También denominado SSID)"
,"Modo 802.11"
,"B/G combinado"
,"Modo N"
,"B/G/N combinado"
,"Exploración de canal automática"
,"Canal inalámbrico"
," GHz - CH "
,"Estado de visibilidad"
,"Visible"
,"Invisible"
,"Modo de seguridad inalámbrica"
,"Modo de seguridad"
,"Ninguno"
,"WEP"
,"WPA-Personal"
,"WPA-Enterprise"
,"WEP"
,"WEP es el estándar de cifrado inalámbrico. Para utilizarlo, debe introducir las mismas claves en el router y en las estaciones inalámbricas. Para claves de 64 bits, debe introducir 10 dígitos hexadecimales en el cuadro de cada clave. Para claves de 128 bits, debe introducir 26 dígitos hexadecimales en el cuadro de cada clave. Un dígito hexadecimal es un número del 0 al 9 o una letra de la A a la F. Para una utilización más segura de WEP, defina el tipo de autenticación en &quot;Clave compartida&quot; cuanto WEP esté activado."
,"También puede introducir cualquier cadena de texto en un cuadro de clave WEP, que se convertirá en una clave hexadecimal utilizando los valores ASCII de los caracteres. Se puede introducir un máximo de 5 caracteres de texto para las claves de 64 bits y un máximo de 13 caracteres para las claves de 128 bits."
,"Autenticación"
,"Abierto"
,"Compartida"
,"Cifrado WEP"
,"64 bits"
,"128 bits"
,"Clave WEP predeterminada"
,"Clave WEP 1"
,"Clave WEP 2"
,"Clave WEP 3"
,"Clave WEP 4"
,"Clave WEP"
,"HEXADECIMAL"
,"ASCII"
,"WPA"
,"Utilice el modo <B>WPA o WPA2</b> para lograr un equilibrio entre una seguridad sólida y la mejor compatibilidad. Este modo utiliza WPA para los clientes heredados, al mismo tiempo que mantiene una mayor seguridad con las estaciones compatibles con WPA2. Asimismo, se utilizará el cifrado más sólido que pueda admitir el cliente. Para mayor seguridad, utilice el modo <B>Sólo WPA2</B>. Este modo utiliza el cifrado AES (CCMP) y no se permite el acceso con seguridad WPA de las estaciones heredadas. Para lograr la máxima compatibilidad, utilice <B>Sólo WPA</B>. Este modo utiliza el cifrado TKIP. Algunos juegos y dispositivos heredados sólo funcionan en este modo.<BR><BR>Para conseguir un mejor rendimiento inalámbrico, utilice el modo de seguridad <B>Sólo WPA2</b> (o, en otras palabras, el cifrado AES)."
,"Modo WPA"
,"Sólo WPA2"
,"Sólo WPA"
,"Tipo de cifrado"
,"TKIP"
,"AES"
,"Clave precompartida"
,"Introduzca una frase secreta alfanumérica de 8 a 63 caracteres. Para lograr una buena seguridad debe tener una longitud amplia y no debe ser una frase conocida habitual."
,"Clave de red"
,"(8~63 ASCII o 64 HEXADECIMALES)"
,"EAP (802.1x)"
,"Cuando está activada WPA enterprise, el router utiliza EAP (802.1x) para autentificar los clientes a través de un servidor remoto RADIUS."
,"Dirección IP del servidor RADIUS"
,"Puerto del servidor RADIUS"
,"Secreto compartido del servidor RADIUS"
,"(13 ASCII o 26 HEXADECIMALES)"
,"(5 ASCII o 10 HEXADECIMALES)"
,"Los parámetros serán efectivos después de reiniciar."
,"¿Está seguro de que desea cambiar?"
,"Configuración de WiFi"
,"En esta sección puede configurar la interfaz inalámbrica (punto de acceso) disponible en el router."
,"Banda de 2.4GHz"
,"Banda de 5GHz"
,"Banda de Frecuencia inalámbrica"
,"Activar exploración automática de canal"
,"Anchura de canal"
,"20/40 MHz (Automático)"
,"20/40/80MHz (Automático)"
,"Sólo 802.11b"
,"Solo 802.11g"
,"Sólo 802.11n"
,"Mezcla de 802.11g y 802.11b"
,"Mezcla de 802.11n y 802.11g"
,"Mezcla de 802.11n, 802.11g y 802.11b"
,"Solo 802.11a"
,"Sólo 802.11n"
,"Mezcla de 802.11a y 802.11n"
,"Mezcla de 802.11 a/n/ac"
,"esta longitud se aplica a todas las claves"
,"Longitud de la clave WEP"
,"¡Advertencia! Si se configura el modo de seguridad de la banda de 2,4 GHz en \"NINGUNO\", se producirán riesgos para la seguridad. ¿Seguro que desea configurarlo?"
,"Es necesario detener la función WPS para activar la configuración de WEP para la banda de 2,4 GHz. ¿Seguro que desea configurarlo?"
,"¡Advertencia! Si se configura el modo de seguridad de la banda de 5GHz en \"NINGUNO\", se producirán riesgos para la seguridad. ¿Seguro que desea configurarlo?"
,"Es necesario detener la función WPS para activar la configuración de WEP para la banda de 5GHz. ¿Seguro que desea configurarlo?"
,"64 Bits (10 dígitos hexadecimales)"
,"128 bits (26 dígitos hexadecimales)"
,"¡Advertencia! Si se configura el modo de seguridad de la banda de 2,4 GHz en \"NINGUNO\", se producirán riesgos para la seguridad. ¿Seguro que desea configurarlo?"
,"¡Advertencia! Si se configura el modo de seguridad de la banda de 5GHz en \"NINGUNO\", se producirán riesgos para la seguridad. ¿Seguro que desea configurarlo?"
,"Es necesario detener la función WPS para activar la configuración de WEP para la banda de 2,4 GHz. ¿Seguro que desea configurarlo?"
,"Es necesario detener la función WPS para activar la configuración de WEP para la banda de 5GHz. ¿Seguro que desea configurarlo?"
,"Automático (WPA o WPA2)"
)

wps=new Array(
 "NO CONFIGURADO"
,"Configurar"
,"CONFIGURADO"
,"Liberar"
,"NO UTILIZADO"
,"INACTIVO"
,"ERROR DE PROCESO"
,"INICIAR PROCESO"
,"RECVEAPOLSTART"
,"SENDEAPREQID"
,"RECVEAPRSPID"
,"RECVWRGVENDORID"
,"RECVWRGVENDORTYPE"
,"SENDEAPREQSTART"
,"ENVIAR M1"
,"RECIBIR M1"
,"ENVIAR M2"
,"RECIBIR M2"
,"RECIBIR M2D"
,"ENVIAR M3"
,"RECIBIR M3"
,"ENVIAR M4"
,"RECIBIR M4"
,"ENVIAR M5"
,"RECIBIR M5"
,"ENVIAR M6"
,"RECIBIR M6"
,"ENVIAR M7"
,"RECIBIR M7"
,"ENVIAR M8"
,"RECIBIR M8"
,"PROCEAPRSPACK"
,"PROCEAPREQDONE"
,"PROCEAPRSPDONE"
,"SENDEAPFAIL"
,"ERRHASHFAIL"
,"ERRHMACFAIL"
,"ERRDEVPWDAUTHFAIL"
,"CONFIGURADO"
,"Configuración protegida Wi-Fi"
,"WPS"
,"PIN AP"
,"Generar nuevo PIN"
,"Modo de configuración"
,"Registrado"
,"Registrador"
,"Estado de configuración"
,"Método de configuración"
,"Código PIN"
,"Botón de pulsación"
,"Estado de WPS"
,"Activación"
,"Leyendo..."
,"Configuración protegida Wi-Fi (WPS)"
,"WPS es un estándar que permite la configuración sencilla y segura de las conexiones inalámbricas. En esta sección, puede activar WPS para una conexión de cliente mediante la seguridad WPA/WPA2."
,"La longitud del código PIN debe ser = 4 u 8"
,"Error de regla de código PIN."
,"Desactivar el método PIN de WPS"
,"La longitud del código PIN debe ser = 4 u 8"
,"Error de regla de código PIN."
)

wlpfe=new Array(
 "Parámetros de Opciones inalámbricas avanzadas"
,"Intervalo de emisión de señales"
,"(mseg, rango:10~1024)"
,"Potencia de transmisión"
,"Umbral RTS"
,"(1~2.347, valor predeterminado: 2.347)"
,"Fragmentación"
,"(256~2346, valor predeterminado: 2346)"
,"Intervalo DTIM"
,"(rango: 1~255)"
,"Compatible con WMM"
,"Velocidades de TX"
,"Especifique los parámetros de configuración avanzados para las puertas de enlace desde esta página. La seguridad del AP y los parámetros de asociación pueden modificarse con relación a los valores predeterminados si se desea."
,"Parámetros inalámbricos de 2,4 G avanzados"
,"Parámetros inalámbricas de 5 G avanzados"
,"GI corta"
,"Coexistencia de HT 20 y 40"
)

//---------------------------------LAN---------------------------------
devlist=new Array(
 "Lista de clientes LAN"
,"Nombre de host (si hubiera)"
,"Dirección IP"
,"Dirección MAC"
)

lanst=new Array(
 "Parámetros del router"
,"Utilice esta sección para configurar los parámetros de red interna de su router. La dirección IP que está configurada aquí es la dirección IP que utiliza para acceder a la interfaz de gestión basada en la web. Si cambia aquí la dirección IP, puede que necesite ajustar los parámetros de red del PC para acceder de nuevo a la red."
,"Dirección IP del router"
,"Máscara de subred predeterminada"
,"Nombre de dominio local"
,"Parámetros del servidor DHCP"
,"Utilice esta sección para configurar el servidor DHCP integrado a fin de que asigne las direcciones IP a los ordenadores de su red."
,"Activar el servidor DHCP"
,"Intervalo de dirección IP de DHCP"
,"a"
,"(direcciones dentro de la subred de LAN)"
,"Tiempo de validez de DHCP"
,"Dirección IP de DNS primaria"
,"Dirección IP de DNS secundaria"
,"Dirección IP de WINS primario"
,"Dirección IP de WINS secundario"
,"La configuración de la dirección IP de LAN será efectiva después de reiniciar."
,"¿Está seguro de que desea cambiar?"
,"El rango del grupo de IP no es válido."
,"Dirección inicial del grupo de IP"
,"Dirección final del grupo de IP"
,"Nombre de dominio local no válido."
,"Esta sección permite configurar los parámetros de red local de su router. Tenga en cuenta que esta sección es opcional y no debería necesitar cambiar ninguno de estos parámetros para que la red funcione."
,"Configuración de la interfaz IP"
,"Servidor DHCP"
,"Configuración del servidor DHCP"
,"DHCP Reservation"
)

//---------------------------------Advanced---------------------------------
ddns=new Array(
 "DNS dinámico"
,"Activar DDNS"
,"Proveedor"
,"DynDNS.org (dinámico)"
,"DynDNS.org (personalizado)"
,"No-IP.com"
,"TZO.com"
,"dhs.org"
,"Nombre de host"
,"Nombre de usuario / Correo electrónico"
,"Contraseña / Clave"
,"La resolución de dirección IP a nombres de host/dominios y viceversa la gestiona el DNS. La información necesaria (dirección IP de al menos un servidor DNS) normalmente la proporciona su ISP. Pero el dispositivo también puede detectar automáticamente los servidores DNS disponibles."
)

spap=new Array(
 "Aplicaciones conocidas"
,"-- Seleccione una --"
,"Battle.net"
,"Dialpad"
,"ICU II"
,"Zona de juegos MSN"
,"PC a teléfono"
,"Quick Time 4"
,"Reglas de las aplicaciones"
,"Activación"
,"Puertos de entrada"
,"Aplicación"
,"El puerto de servicio del servidor virtual y el puerto de entrada de las reglas de las aplicaciones no pueden ser el mismo."
,"El valor del puerto de entrada no puede ser el mismo."
)

dmz=new Array(
 "Parámetros del cortafuegos"
,"Activar SPI"
,"Host DMZ"
,"La opción DMZ (zona desmilitarizada) permite definir un único ordenador de su red fuera del router. Si tiene un ordenador que no puede ejecutar correctamente aplicaciones de Internet desde detrás del router, puede poner el ordenador en la DMZ para disponer de acceso ilimitado a Internet."
,"<b>Nota:</b> al poner un ordenador en la DMZ, puede exponer dicho ordenador a diversos riesgos de seguridad. Sólo se recomienda el uso de esta opción como último recurso."
,"Activar DMZ"
,"Dirección IP de DMZ"
,"Nombre del ordenador"
)

smap=new Array(
 "Servicios muy conocidos"
,"-- Seleccione una --"
,"AUTH (113)"
,"DNS (53)"
,"FTP (21)"
,"ISAKMP (500)"
,"POP3 (110)"
,"PPTP (1723)"
,"SMTP (25)"
,"TELNET (23)"
,"WEB (80)"
,"Utilizar regla de programa"
,"---SIEMPRE ACTIVADO---"
,"Lista de servidores virtuales"
,"Puertos de servicio"
,"IP del servidor: Puerto"
,"Activar"
,"Regla de programa nº"
,"El Externamente actúa como servidor. Recibe las solicitudes de los usuarios remotos bajo su dirección IP pública y las reenvía automáticamente al servidor virtual. "
,"Así, un cliente de su red situado detrás de un NAT o cortafuegos puede proporcionar servicios como Servidor virtual. "
,"Solo tiene que activar puertos o intervalos de puertos y protocolos (UDP/TCP) específicos. Se permite la compartición de archivos o los servicios web, como para HTTP, FTP o POP3. Las direcciones IP privadas de los servidores de la red local permanecen seguras. Si no dispone de una dirección IP dinámica, puede activar adicionalmente DynDNS."
,"El valor del puerto de servicio no puede ser el mismo."
,"error de configuración"
)

uctl=new Array(
 "Parámetros de filtrado de URL"
,"Filtrado de URL"
,"Activar"
,"Reglas de filtrado de URL"
,"URL"
,"Activar"
,"La URL no puede estar vacía."
,"http://' no está permitido."
,"El filtro de URL proporciona herramientas útiles para restringir el acceso a Internet. "
,"La opción Bloqueo de URL del sitio web le permite crear rápidamente una lista de sitios web a los que desea permitir o impedir que accedan los usuarios."
,"Filtro de URL"
)

rtab=new Array(
 "Configuración de RIP"
,"RIP"
,"Activar"
,"RIPv1"
,"RIPv2"
,"Reglas de enrutamiento"
,"Destino"
,"Máscara de subred"
,"Puerta de enlace"
,"Punto de conexión"
,"Las rutas para el tráfico de su red se definen en la tabla de enrutamiento. Normalmente, las entradas para Dirección IP y Puerta de enlace son suficientes. No tiene que definir ningún parámetro."
)

qos=new Array(
 "Alta"
,"Normal"
,"Baja"
,"Configuración de QoS"
,"Activar filtro de paquetes de QoS"
,"Ancho de banda ascendente"
,"Ancho de banda descendente"
,"kbps"
,"Utilizar regla de programa"
,"---SIEMPRE ACTIVADO---"
,"Reglas de calidad de servicio (QoS)"
,"IP local: Puertos"
,"IP remota: Puertos"
,"Prioridad QoS"
,"Activar"
,"Utilizar regla nº"
,"Configuración de QoS"
)

pmac=new Array(
 "Parámetros de filtrado MAC"
,"Control de dirección MAC"
,"Activar"
,"Control de conexión"
,"Los clientes inalámbricos y con cables con la <b>C</b> marcada pueden conectarse a este dispositivo; y "
,"permitir"
,"denegar"
," direcciones MAC sin especificar para conectar."
,"Control de asociación"
,"Los clientes inalámbricos con la <b>A</b> marcada no se pueden asociar a la LAN inalámbrica; y "
,"permitir"
,"denegar"
," direcciones MAC sin especificar para asociar."
,"Clientes DHCP"
,"-- Seleccione una --"
,"Reglas de filtrado MAC"
,"Dirección MAC"
,"Dirección IP"
,"C"
,"A"
)

iopf=new Array(
 "Configuración del filtro de salida"
,"Configuración del filtro de entrada"
,"Filtro de salida"
,"Filtro de entrada"
,"Activar"
,"Utilizar regla de programa"
,"---SIEMPRE ACTIVADO---"
,"Lista de reglas de filtro de salida"
,"Lista de reglas de filtro de entrada"
,"Permitir el paso a todos excepto a los que cumplan las reglas siguientes."
,"Denegar el paso a todos excepto a los que cumplan las reglas siguientes."
,"IP de origen: puertos"
,"IP de destino: puertos"
,"Activar"
,"Regla de programa nº"
,"Error al utilizar el número de regla."
)

snmp=new Array(
 "SNMP"
,"SNMP local"
,"SNMP remoto"
,"Obtener comunidad"
,"Comunidad asignada"
,"IP 1"
,"IP 2"
,"IP 3"
,"IP 4"
,"Versión de SNMP"
,"V1"
,"V2c"
,"Dirección IP de acceso WAN"
)

fmisc=new Array(
 "UPNP"
,"Plug and Play universal (UPnP, Universal Plug and Play) admite la funcionalidad Plug and Play de igual a igual para los dispositivos de red."
,"Activar UPnP"
,"PING WAN"
,"Si activa esta característica, el puerto WAN del router responderá a las solicitudes ping procedentes de Internet enviadas a la dirección IP de WAN."
,"Activar Responder al ping WAN"
)

networkscan=new Array(
 "Selección de proveedor de red"
,"Esta página buscará proveedores de red próximos.<br>Espere mientras se busca."
,"Método de selección de red 3G/4G"
,"En curso..."
,"Lista de proveedores de red"
,"No hay ningún proveedor de red"
,"Si no selecciona Proveedores de red, el modo cambiará a Automático"
,"Se han guardado los cambios. Debe reiniciarse el router para que los cambios surtan efecto."
,"Puede reiniciar ahora o continuar haciendo cambios y reiniciar más tarde."
,"Disponible"
,"Actual"
,"Prohibido"
,"Explorar"
,"Network Selection Method"
)

//---------------------------------System---------------------------------
sntp=new Array(
 "Configuración de fecha y hora"
,"Hora"
,"Zona horaria"
,"Activar el horario de verano"
,"Sincronizar los parámetros de hora de su ordenador"
,"Configuración automática de fecha y hora"
,"Sincronizar automáticamente con el servidor de hora de Internet"
,"Servidor NTP utilizado"
,"Actualizar ahora"
,"Sinc. RESULTADO"
,"Iniciar"
,"Finalizar"
,"Hora"
,"Día"
,"Mes"
,"(Hora/Día/Mes)"
,"Ene"
,"Feb"
,"Mar"
,"Abr"
,"Mayo"
,"Jun"
,"Jul"
,"Ago"
,"Sep"
,"Oct"
,"Nov"
,"Dic"
,"Dom"
,"Lun"
,"Mar"
,"Miér"
,"Jue"
,"Vier"
,"Sáb"
,"La opción Configuración de la hora permite configurar, actualizar y mantener la hora correcta en el reloj interno del sistema."
,"En esta sección puede definir la zona horaria en la que se encuentra y definir el servidor NTP (Protocolo de hora de red)."
,"También puede configurar el horario de verano para que se ajuste automáticamente la hora cuando corresponda."
,"Hora"
,"Parámetros de hora"
)

tz=new Array(
 "* Todavía no está configurado. El valor predeterminado es GMT+00:00"
,"Línea de fecha internacional occidental"
,"Isla de Midway, Samoa"
,"Hawai"
,"Alaska"
,"Hora del Pacífico (EE.UU. y Canadá)"
,"Tijuana"
,"Arizona"
,"Chihuahua, La Paz, Mazatlán"
,"Hora de las Rocosas (EE.UU. y Canadá)"
,"América Central"
,"Hora central (EE.UU. y Canadá)"
,"Guadalajara, Ciudad de Méjico, Monterrey"
,"Saskatchewan"
,"Bogotá, Lima, Quito"
,"Hora del este (EE.UU. y Canadá)"
,"Indiana (Este)"
,"Hora del Atlántico (Canadá)"
,"Caracas, La Paz"
,"Santiago"
,"Terranova"
,"Brasilia"
,"Buenos Aires, Georgetown"
,"Groenlandia"
,"Atlántico central"
,"Azores"
,"Islas de Cabo Verde"
,"Casablanca, Monrovia"
,"Dublín, Edimburgo, Lisboa, Londres"
,"Ámsterdam, Berlín, Berna, Roma, Estocolmo, Viena"
,"Belgrado, Bratislava, Budapest, Liubliana, Praga"
,"Bruselas, Copenhague, Madrid, París"
,"Sarajevo, Skopje, Varsovia, Zagreb"
,"África central occidental"
,"Atenas, Beirut, Estambul, Minsk"
,"Bucarest"
,"Cairo"
,"Harare, Pretoria"
,"Helsinki, Kiev, Riga, Sofía, Tallin, Vilna"
,"Jerusalén (solo 2007)"
,"Bagdad"
,"Kuwait, Riad"
,"Moscú, San Petersburgo, Volgogrado"
,"Nairobi"
,"Teherán"
,"Abu Dabi, Muscat"
,"Bakú"
,"Tiflis"
,"Yereván"
,"Kabul"
,"Ekaterimburgo"
,"Islamabad, Karachi, Tashkent"
,"Chennai, Calcuta, Bombay, Nueva Delhi"
,"Katmandú"
,"Almaty, Novosibirsk"
,"Astana, Dacca"
,"Colombo"
,"Rangún"
,"Bangkok, Hanoi, Yakarta"
,"Krasnoyarsk"
,"Pekín, Chongqing, Hong Kong, Urumqi"
,"Irkutsk"
,"Kuala Lumpur, Singapur"
,"Perth, Australia occidental"
,"Taipei"
,"Ulan Bator"
,"Osaka, Sapporo, Tokio"
,"Seúl"
,"Yakutsk"
,"Adelaida"
,"Darwin"
,"Brisbane"
,"Camberra, Melbourne, Sidney"
,"Guam, Port Moresby"
,"Hobart"
,"Vladivostok"
,"Magadán, Islas Salomón, Nueva Caledonia"
,"Auckland, Wellington"
,"Fiji, Kamchatka, Islas Marshall"
,"Nuku'alofa"
,"* Configure la variable ZH manualmente..."
,"Eniwetok, Kwajalein"
,"Ciudad de Méjico, Tegucigalpa"
,"Bruselas, Copenhague, Madrid, París, Vilna"
,"Sarajevo, Skopje, Sofía, Varsovia, Zagreb"
,"Atenas, Beirut, El Cairo, Estambul, Minsk"
,"Pekín, Hong Kong, Taipei"
,"India"
)

atbox=new Array(
 "Administrador (el nombre de inicio de sesión predeterminado es "
,")"
,"Nombre de inicio de sesión"
,"Nueva contraseña"
,"Confirmar contraseña"
,"Administración remota"
,"Activar gestión remota"
,"IP con acceso permitido"
,"Puerto"
,"Las nuevas contraseñas del administrador no son idénticas."
,"¿Desea guardar su contraseña en una contraseña vacía?"
,"El puerto de gestión remoto debe ser superior a 1.024."
,"Administrador"
,"Aquí puede cambiar la contraseña para el administrador."
,"El nombre de usuario (admin) no se puede cambiar."
,"Parámetros del administrador"
,"SSH"
,"Activar SSH"
,"Permitir Wan"
,"Telnet"
,"Activar Telnet"
,"Remote Administration"
)

rebo=new Array(
 "Actualización correcta."
,"Archivo de actualización no válido."
,"Asegúrese de que tiene el archivo correcto."
,"El archivo no es compatible con el firmware o hardware actual."
,"No está permitida la actualización a esta versión."
,"El proceso de actualización se ha cancelado por motivos desconocidos."
,"Inténtelo de nuevo."
,"Se han reiniciado todos los parámetros."
,"El dispositivo se está reiniciando..."
,"<font color=red><b>NO APAGUE</b></font> el dispositivo."
,"Y espere durante "
," segundos..."
,"Vuelva a conectar manualmente."
,"Nota: su IP de LAN puede cambiar, vuelva a conectar."
,"Haga clic aquí para volver a conectar"
,"El sistema está preparado"
,"Reiniciar router"
,"Mensaje de estado"
,"El router estará activo en"
,"Reiniciar ahora"
,"Reiniciar más tarde"
)

system=new Array(
 "¿Reiniciar todos los parámetros en los valores predeterminados?"
,"Guardar y restablecer parámetros"
,"Guardar parámetros en la unidad de disco duro local"
,"Guardar"
,"Cargar parámetros de la unidad de disco duro local"
,"Parámetros de carga"
,"Restablecer los parámetros predeterminados de fábrica"
,"Restablecer los ajustes predeterminados"
,"Archivo de actualización no válido."
,"Archivo de actualización no permitido."
,"Sistema"
,"Se guardarán todos los parámetros en el dispositivo automáticamente. No es necesario que guarde manualmente ni que reinicie. Si desea reiniciar el dispositivo de todos modos, lo mejor es hacerlo mediante el botón \"Reiniciar\"."
,"Parámetros del sistema"
,"Reiniciar el dispositivo"
,"¿Restablecer todos los parámetros en los valores predeterminados de fábrica?"
,"Reiniciar"
,"Reiniciar y restablecer"
)

fwug=new Array(
 "Información del firmware"
,"Versión del firmware actual"
,"Fecha actual del firmware"
,"Actualización de firmware"
,"Nota: no apague la unidad cuando se está actualizando."
,"El procedimiento de actualización tarda alrededor de 180 segundos."
,"Una vez actualizada correctamente, la unidad se reiniciará automáticamente."
,"Para actualizar el firmware, el PC debe tener una conexión con cables al router. Introduzca el nombre del archivo de actualización de firmware y haga clic en el botón Cargar."
,"Cargar"
,"Actualizar"
,"Nombre de archivo incorrecto"
,"Sólo se aceptan archivos .bin."
,"Cancelar"
,"Hay otra actualización de firmware en curso."
,"Aceptar firmware no oficial."
,"Utilice el botón \"Actualizar\" para actualizar la versión del firmware de su dispositivo."
,"Actualización de firmware"
,"Seleccionar firmware"
,"Compruebe archivo"
,"Nueva información sobre el firmware"
,"Nueva versión de firmware"
,"Nuevo firmware Fecha"
)

logs=new Array(
 "Parámetros de SysLog"
,"Activar inicio de sesión en el servidor Syslog"
,"Dirección IP del servidor Syslog"
,"Parámetros de correo electrónico"
,"Activar notificación de correo electrónico"
,"IP y puerto del servidor SMTP"
,"Enviar alerta por correo electrónico a"
,"Asunto del mensaje de correo electrónico"
,"Nombre de usuario de SMTP"
,"Contraseña de SMTP"
,"Enviar registro por correo electrónico ahora"
,"Hay un mensaje de correo electrónico en la cola para enviar..."
,"Registro del sistema"
,"El registro del sistema permite configurar los registros locales, remotos y de correo electrónico y ver los registros que se han creado."
,"Clear logs"
,"Log Number"
,"Message"
,"View Logs"
)

smsmsg=new Array(
 "Responder al mensaje"
,"Enviar mensaje"
,"Crear mensaje"
,"Mensaje de texto"
,"Introducir mensaje..."
,"La longitud máxima de un mensaje es de 160 caracteres."
,"Destinatario"
,"Añada '+' para el formato internacional del número de teléfono."
,"Enviar"
,"Leyendo... Espere..."
,"Longitud del texto introducido actual"
,"Enviar mensaje"
,"Si desea crear y enviar un mensaje SMS, haga clic en el botón siguiente."
,"El destinatario no puede estar vacío."
,"The max. length of a message is 160 characters for pure alphabetical or numeric."
)

smsinbox=new Array(
 "Estado de SMS"
,"SMS recibido"
,"Nuevo SMS"
,"Capacidad total"
,"Bandeja de entrada"
,"De"
,"Marca de tiempo"
,"Texto"
,"SMS"
,"Leyendo... Espere..."
,"Responder"
,"Reenviar"
,"Bandeja de entrada de SMS"
,"Si desea ver el mensaje SMS, haga clic en el botón siguiente."
,"Configuración de SMSC"
,"Compruebe si la tarjeta SIM está insertada o no."
,"¡Tarjeta SIM bloqueada! No se puede leer SMS desde tarjeta SIM."
,"El módem no está listo."
,"El módem está ocupado por una llamada de teléfono. Espere..."
,"Envío correcto."
,"Error de envío."
,"El módem está ocupado por una llamada de teléfono. El SMS se enviará automáticamente más tarde."
,"Eliminar correcto."
,"Error al eliminar."
,"Error del Comando AT."
,"El módem está ocupado por una llamada de teléfono. El SMS se eliminará automáticamente más tarde."
)

voiceforwd=new Array(
 "Todas las llamadas"
,"Sin respuesta"
,"Inaccesible"
,"Ocupado"
,"Estado"
,"Anular registro"
,"Registro"
,"Activar"
,"Desactivar"
,"Número"
)

pinco=new Array(
 "Estado de la consulta... Espere..."
,"Código PIN de SIM"
,"Introduzca 4~8 caracteres en el campo Código PIN de SIM."
,"Función Solicitud de código PIN"
,"Introduzca el código PIN de SIM"
,"Cambiar código PIN..."
,"¡Correcto!"
,"Introduzca 4~8 caracteres en el campo Código PIN antiguo."
,"Introduzca 4~8 caracteres en el campo Código PIN nuevo."
,"Introduzca 4~8 caracteres en el campo Verificar código PIN."
,"Función Cambio de código PIN"
,"Código PIN antiguo"
,"Nuevo código PIN"
,"Verificar código PIN"
,"¡Guardar!"
,"Introduzca el código PIN para desbloquear la tarjeta SIM"
,"Código PIN"
,"Introduzca el código PUK para desbloquear la tarjeta SIM"
,"Código PUK"
,"Nuevo código PIN"
,"La función ya está desactivada."
,"La función ya está activada."
,"Código PIN incorrecto."
,"Primero debe activar la función Activar solicitud de código PIN."
,"Ha introducido dos códigos PIN diferentes."
,"Código PIN antiguo incorrecto."
,"Código PUK incorrecto."
,"Error del Comando AT."
,"Listo"
,"Bloqueado por PIN de SIM"
,"Bloqueado por PUK de SIM"
,"Tarjeta SIM con algunos errores."
,"El módem no tiene respuesta."
,"Error del comando Enviar AT."
,"El módem no existe. Compruebe si está insertada la tarjeta SIM."
,"Advertencia: 3 intentos más permitidos."
,"Reintentar"
,"Continuar"
,"Advertencia: "
," intentos más permitidos."
,"Introduzca 4~8 caracteres en el campo Código PIN."
,"Introduzca 8 caracteres en el campo Código PUK."
,"Control de PIN."
,"El módem se está inicializando; espere un momento."
,"Configuración de PIN"
,"Insertar código PIN 3 veces fallan! Por favor, introduzca el código PUK."
)

ussd=new Array(
 "USSD"
,"Enviar"
,"ERROR"
)

scherebo=new Array(
 "Reinicio de la conexión"
,"Reinicio automático"
,"Programa de reinicio"
,"Programar diario"
,"Programa semanal, día de la semana"
,"Día del mes"
)

sche=new Array(
 "Regla de programa"
,"Activar programa"
,"Regla nº"
,"Nombre de la regla"
,"Acción"
,"No se ha añadido ninguna regla, añada las reglas antes de activar."
,"¿Está seguro de que desea borrar la regla? "
,"??"
,"Programar"
)

rule=new Array(
 "El nombre de regla no puede estar vacío."
,"El nombre del programa está duplicado con otra regla."
,"(Regla:"
,")"
,"vuelva a comprobarlo."
,"La hora de inicio del día de la semana "
," no es válida."
,"La hora final del día de la semana "
," no es válida."
,"La hora del día de la semana "
," no es válida."
,"La hora final debe ser posterior a la hora de inicio"
,"(El formato de la hora programada debe ser hh:mm)"
,"(0 < Las horas de la hora de inicio deben ser < 23 )"
,"(0 < Los minutos de la hora de inicio deben ser < 59 )"
,"(0 < Las horas de la hora final deben ser < 23 )"
,"(0 < Los minutos de la hora final deben ser < 59 )"
,"Seleccione un día de la semana en la ID de regla "
,"!!"
,"La hora de la regla de programa está vacía."
," Introduzca como mínimo un programa."
,"Cada día"
,"Domingo"
,"Lunes"
,"Martes"
,"Miércoles"
,"Jueves"
,"Viernes"
,"Sábado"
,"Configuración de la regla de programa"
,"Nombre de la regla"
,"-- elija una --"
,"Política"
,"Atrás"
,"Desactivar"
,"Activar"
,"excepto los días y horas seleccionadas a continuación."
,"Día de la semana"
,"Hora de inicio (hh:mm)"
,"Hora final (hh:mm)"
)

diagnostic=new Array(
 "Información de servicio"
,"Operador"
,"Difusión de celda"
,"MCC"
,"MNC"
,"LAC"
,"Tipo de servicio"
,"Modo de preferencia de servicio"
,"Sólo GSM"
,"Sólo WCDMA"
,"Desconocido"
,"Conexión PS (DATOS)"
,"Conexión CS (VOZ)"
,"IMSI"
,"SMSC"
,"Conectado"
,"Desconectado"
,"Estado de SIM"
,"Bloqueo de código PIN"
,"Veces de reintento de código PIN"
,"Veces de reintento de código PUK"
,"Estado del módulo"
,"IMEI"
,"Versión de FW"
,"Nombre del módulo"
,"ID de celda"
)

voice=new Array(
 "Voz"
,"Envío de llamada"
,"Reenviando automáticamente las llamadas entrantes a un número designado en condiciones diferentes."
,"Llamada en espera"
,"Suspender llamada actual y poder hablar con una nueva llamada entrante."
,"Ir a Envío de llamada"
,"Ir a Llamada en espera"
)

sms=new Array(
 "Crear mensaje"
,"Permitir crear y enviar nuevo mensaje SMS."
,"bandeja de entrada"
,"Permitir leer nuevos mensajes SMS y eliminar/reenviar mensaje existente."
,"¡Solo puede contestar a un mensaje cada vez!"
)

tr069=new Array(
 "TR-069"
,"TR-069 Setting"
,"ACS Setting"
,"ACS URL"
,"ACS UserName"
,"ACS Password"
,"CPE Setting"
,"ConnectionRequest Port"
,"ConnectionRequest UserName"
,"ConnectionRequest Password"
,"Inform Setting"
,"Inform"
,"Interval"
,"Interface"
)
