//Italian
common=new Array(
 "Aggiorna"
,"Guida"
,"Disconnetti"
,"Abilita"
,"Disabilita"
,"Elemento"
,"Modifica"
,"Elimina"
,"Indietro"
,"Automatico"
,"Manuale"
,"Applica"
,"Reimposta"
,"Aggiungi"
,"secondi"
,"byte"
,"ID"
,"Copia in"
,"Pagina precedente"
,"Pagina successiva"
,"Aggiungi nuova regola..."
,"Ottima"
,"minuti"
,"Abilitato"
,"Disabilitato"
,"First Page"
,"Last Page"
,"Download"
,"Page"
)

others=new Array(
 "Riavvia"
,"Riavviare il router?"
,"Disconnesso"
,"Pagina prodotto"
,"Versione firmware"
,"copyright"
,"Suggerimenti utili..."
,"Altro..."
,"Salva impostazioni"
,"Non salvare le impostazioni"
,"Non modificare"
,"Non modificare."
,"Continua"
,"Impostazione salvata."
,"La modifica ha effetto immediato."
,"Impostazione completata"
,"Sistema in elaborazione, attendere qualche secondo..."
,"ROUTER"
,"Nome utente"
,"Password"
,"Accesso"
,"Nome utente o password non valido"
,"Inserire un nome utente valido"
,"Nome utente o password non valido"
,"Disconnessione riuscita."
,"Disconnesso."
,"Prima accedere."
,"Inserire un nome utente valido"
,"Inserire una password valida"
,"Inserire il nome utente"
,"Il valore inserito non può essere vuoto."
,"Attendere qualche secondo..."
,"L'amministratore di account già logined"
,"Confermare?"
)

dirary0=new Array(
 "Home"
,"Internet"
,"Wi-Fi"
,"LAN"
,"Avanzate"
,"Sistema"
,"Servizio WAN"
,"Failover"
,"IPv6"
,"Elenco dispositivi"
,"Impostazioni Wi-Fi"
,"WPS"
,"Avanzate Wi-Fi"
,"Impostazioni LAN"
,"DHCP"
,"DNS"
,"Applicazioni"
,"DMZ"
,"Server virtuale"
,"Filtro URL"
,"Routing"
,"QOS"
,"Filtro indirizzo MAC"
,"Filtro di uscita"
,"Filtro d'ingresso"
,"SNMP"
,"Rete avanzate"
,"Impostazioni orario"
,"Gestione"
,"Riavvia e Reimposta"
,"Aggiornamento firmware"
,"Log di sistema"
,"Pianificazioni"
,"Procedura guidata"
,"Network Scan"
,"Reimposta connessione"
,"Configurazione PIN"
,"Message Service"
,"Posta in arrivo SMS"
,"Crea messaggio"
,"Voce"
,"Inoltro chiamata"
,"Chiamata in attesa"
,"Diagnostico"
,"TR-069"
,"MULTIWAN"
)

valchk=new Array(
 "Controllare di nuovo le impostazioni."
,"Indirizzo IP non valido."
,"Subnet mask non valida."
,"Intervallo indirizzo IP non valido."
,"Indirizzo IP LAN non valido."
,"Valore non valido."
,"Porta non valida."
,"(es. formato 1-65535,777)"
,"Intervallo di porta non valido. (es. formato 1-65535)"
,"MTU non valido."
,"Ora non valida."
,"Ora non valida."
,"Indirizzo MAC non valido."
,"Chiave WEP non valida."
,"Chiave di precondivisione non valida."
,"E-mail non valida."
,"Inserire 10 o 26 cifre esadecimali nel campo Chiave WEP."
,"Inserire 5 o 13 caratteri ASCII nel campo Chiave WEP."
,"Inserire 64 cifre esadecimali o da 8 a 63 caratteri ASCII nel campo Chiave precondivisa."
,"Inserire 64 cifre esadecimali nel campo Chiave precondivisa."
," non valida."
)

//---------------------------------status---------------------------------
sta=new Array(
 "Generale"
,"Ora"
,"Versione firmware"
,"WAN"
,"Tipo di connessione"
,"IP statico"
,"Indirizzo MAC"
,"Indirizzo IP"
,"Subnet Mask"
,"Gateway predefinito"
,"Server DNS"
,"Client DHCP"
,"Stato rete"
,"Client disconnesso"
,"Connessione in corso..."
,"Stabilita"
,"Disconnessione in corso..."
,"In attesa del traffico..."
,"Ora di lease rimanente"
,"Rinnova"
,"Versione"
,"PPPoE"
,"Disconnesso"
,"Ora connessione"
,"Connetti"
,"Disconnetti"
,"Riconnetti"
,"PPTP"
,"L2TP"
,"4G LTE /3G"
,"Forza del segnale"
,"Informazioni scheda"
,"Stato collegamento"
,"Errore autenticazione"
,"PIN richiesto"
,"Errore password"
,"Nessun modem rilevato"
,"Impossibile connettere. Controllare le inpostazioni e riprovare."
,"Nome rete"
,"LAN"
,"Server DHCP"
,"LAN wireless"
,"Wireless"
,"SSID"
,"Protezione"
,"Apri"
,"Condiviso"
,"Automatico"
,"WPA-PSK"
,"WPA"
,"WPA2-PSK"
,"WPA2"
,"WPA-PSK/WPA2-PSK"
,"WPA/WPA2"
,"Nessuna"
,"WEP"
,"TKIP"
,"AES"
,"TKIP/AES"
,"Canale"
,"Automatico"
,"Modalità 802.11"
,"B/G misto"
,"Modalità N"
,"B/G/N misto"
,"Impostazione Wi-Fi protetto"
,"Computer in LAN"
,"Nome"
,"MAC"
,"Giorno"
,"Ora"
,"Min"
,"Sec"
,"N/D"
,"Failover 3G"
,"Scheda 3G"
,"Internet"
,"SSID2"
,"Client totali"
,"Pool DHCP"
,"Nome sistema"
,"Uptime sistema"
,"Versione HW"
,"Versione SW"
,"Failover"
,"Loadsharing"
,"Tipo di servizio"
,"Telefono"
,"Nessun Servizio"
,"Stato"
)

//---------------------------------Internet---------------------------------
prim=new Array(
 "Tipo di connessione Internet"
,"La mia connessione Internet è"
,"IP statico"
,"IP dinamico (DHCP)"
,"PPPoE (Nome utente / Password)"
,"PPTP (Nome utente / Password)"
,"L2TP (Nome utente / Password)"
,"4G LTE /3G"
,"Backup automatico"
,"Abilita controllo alive WAN cablata"
,"Host Internet"
,"Inserire un indirizzo IP in Internet."
,"Tipo di connessione Internet indirizzo IP statico"
,"Indirizzo IP"
,"Subnet Mask"
,"Gateway predefinito"
,"Server DNS primario"
,"Server DNS secondario"
,"MTU"
,"(byte) MTU predefiniti = 1500"
,"Indirizzo MAC"
,"Clona"
,"Cancella"
,"Tipo di connessione Internet (DHCP) IP dinamico"
,"Nome host"
,"Riconnessione automatica"
,"PPPoE"
,"Nome utente"
,"Password"
,"Verifica password"
,"Nome servizio"
,"(facoltativo)"
,"Indirizzo IP"
,"Tempo massimo di inattività"
,"(byte) MTU predefiniti = 1492"
,"PPTP"
,"Modalità indirizzo"
,"IP dinamico"
,"IP statico"
,"Indirizzo IP PPTP"
,"Subnet Mask PPTP"
,"Indirizzo IP Gateway PPTP"
,"Indirizzo IP server PPTP"
,"Modalità riconnessione"
,"Sempre attivo"
,"Connetti on-demand"
,"L2TP"
,"Indirizzo IP L2TP"
,"Subnet Mask L2TP"
,"Indirizzo IP Gateway L2TP"
,"Indirizzo IP server L2TP"
,"Tipo di connessione Internet 4G LTE /3G"
,"Nome profilo/account"
,"Numero composto"
,"Autenticazione"
,"PAP"
,"CHAP"
,"APN"
,"Codice Pin"
,"Mantieni alive"
,"Disabilita"
,"Usa ping"
,"DNS Query"
,"Usa richiesta Echo LCP"
,"Intervallo ICP-Echo:"
,"Errore ICP-Echo:"
,"volte"
,"Ping indirizzo IP"
,"Intervallo ping"
,"Porte Ethernet bridge"
,"L'indirizzo MAC è stato modificato"
,"Il nuovo indirizzo MAC diventa effettiva dopo il riavvio."
,"Riavviare adesso?"
,"Roaming"
,"Controllo DNS"
,"Disabilita NAT"
,"Modalità automatica"
,"Solo modalità 4G"
,"Solo modalità 3G"
,"Solo modalità 2G"
,"Tipo di servizio preferito"
,"Configurazione servizio WAN"
,"facoltativo"
,"Bridge trasparente"
,"Interfaccia WAN"
,"Chiudi"
,"WAN Ethernet"
,"Profilo chiamata"
,"Rilevamento automatico"
,"Paese"
,"Telecom"
,"Network"
,"Altri"
,"Impostazione di rete"
,"Le nuove password non coincidono."
,"Impostazione non valida"
,"Modalità automatica"
,"Modalità preferita 3G"
,"Modalità prima 2G"
,"Caricamento"
,"Rete 3G/4G"
,"WCDMA/HSP"
,"CDMA2000/EV-DO"
,"Indirizzo IP e gateway predefinito non valido!"
,"Tempo massimo di inattività chiamata deve essere tra"
,"Tipo di connessione Internet 3G"
,"VLAN Tagging"
)

failover=new Array(
 "Impostazione failover"
,"Tipo di failover"
,"Host remoto per Keep alive"
,"Elenco failover"
,"Interfaccia"
,"Cambia"
,"L'attuale connessione Internet è"
,"Il tipo di Internet failover è"
,"Failover"
,"Tipo di connessione failover"
,"Impostazione interfaccia failover"
,"Eliminare WAN secondaria?"
,"Impostazione backup automatico"
,"Backup automatico"
,"Host remoto per Keep alive"
,"Elenco connessioni WAN"
,"Interfaccia"
,"Cambiare o eliminare l'interfaccia."
,"L'host remoto per Keep Alive non può essere null."
,"Selezione non valida."
,"WAN primaria"
,"WAN secondaria"
,"Cambiando il tipo di WAN si cancelleranno le impostazioni di failover.\nContinuare?"
,"Caricamento condivisione"
,"Impostazione failover..."
,"Caricamento condivisione tipo di connessione"
,"Indirizzo IP dinamico"
,"Indirizzo IP statico"
,"Porta 1"
,"Porta 2"
,"Selezionare WAN secondaria!"
,"L'abilitazione delle porte Bridge Ethernet comporta la disabilitazione della WAN Ethernet."
)

ipv6=new Array(
 "Impostazioni da 6 a 4"
,"Indirizzo da 6 a 4"
,"Indirizzo DNS primario"
,"Indirizzo DNS secondario"
,"Impostazioni indirizzo IPv6 LAN"
,"Indirizzo IPv6 LAN"
,"Indirizzo locale collegamento IPv6 LAN"
,"Impostazioni di autoconfigurazione indirizzo"
,"Autoconfigurazione"
,"Tipo di autoconfigurazione"
,"Durata annunci router"
,"Indirizzo IPv4 remoto"
,"Indirizzo IPv4 locale"
,"Indirizzo IPv6 locale"
,"Impostazione IPv6"
,"Connessione IPv6"
,"Senza stato"
,"Con stato (DHCPv6)"
,"Usare questa sezione per configurare le impostazioni di rete interna del router. L'indirizzo locale collegamento IPv6 LAN configurato qui è quello utilizzato per accedere all'interfaccia di gestione su base web. Se si cambia l'indirizzo IPv6 LAN qui, si dovranno cambiare le impostazioni di rete del PC per accedere di nuovo alla rete."
,"Abilita DHCP-PD"
,"Impostazioni di autoconfigurazione indirizzo LAN"
,"Utilizzare questa sezione per impostare l'autoconfigurazione IPv6 per assegnare gli indirizzi IP ai computer nella rete."
,"Abilita autoconfigurazione"
,"SLAAC+Senza stato DHCPv6"
,"Indirizzo locale collegamento IPv6 LAN"
,"Usare questa sezione per configurare il tipo di connessione IPv6. Se non si è certi sul metodo di connessione, contattare il proprio fornitore di servizi Internet."
,"Quando si configura il router per accedere a Internet IPv6 accertarsi di scegliere il tipo di connessione IPv6 corretta dal menu a discesa. Se non si è certi sull'opzione da scegliere, contattare il proprio fornitore di servizi Internet.(ISP.)"
,"Scegliere la modalità del router per la connessione a Internet IPv6."
,"Configurazione automatica (SLAAC/DHCPv6)"
,"Tunnel IPv4 su IPv6"
,"6rd"
,"Solo collegamento locale"
,"Informazioni di condivisione IPv6"
,"Tipo di condivisione IPv6"
,"Stato della rete"
,"Indirizzo IPv6 WAN"
,"Gateway predefinito IPv6"
,"Server DNS IPv6 primario"
,"Server DNS IPv6 secondario"
,"Indirizzo locale collegamento IPv6 LAN"
,"DHCP-PD"
,"Rete Ipv6 assegnata da DHCP-PD"
,"Indirizzo IPv6 LAN"
,"Indirizzo IPv6"
,"Nome (se presente)"
,"IPv6 stativo"
,"DHCPv6"
,"Da 6 a 4"
,"PPPoA"
,"*Pulsante connetti per IPv4 e IPv6"
,"*Pulsante disconnetti per IPv4 e IPv6"
,"Indirizzo IPv6 globale"
,"Impostazioni indirizzo IPv6 WAN"
,"Lunghezza prefisso subnet"
,"Impostazioni PPPoA o PPPoE"
,"Impostazioni Tunnel IPv4 su IPv6"
,"Indirizzo IPv6 remoto"
,"Impostazioni DNS IPv6"
,"Impostazioni DNS"
,"Ottieni indirizzo server DNS automaticamente"
,"Usa il seguente indirizzo DNS"
,"Impostazioni 6rd"
,"Lunghezza maschera IPv4"
,"Prefisso remoto"
,"Lunghezza prefisso"
,"Intervallo indirizzo IPv6 (inizio)"
,"Intervallo indirizzo IPv6 (fine)"
,"Durata indirizzo IPv6"
,"Abilita DS-Lite"
,"Configurazione DS-Lite"
,"Opzione DHCPv6 DS-Lite"
,"Configurazione manuale"
,"Indirizzo locale-Link WAN"
,"IPv6 dinamico"
,"Passthrough IPv6"
,"L'indirizzo WAN IPv4 non è un indirizzo globale."
,"WAN IPv6 Address Status"
)

//---------------------------------WiFi---------------------------------
wpa=new Array(
 "Impostazioni di rete wireless"
,"Abilita wireless"
,"Nome rete wireless"
,"(chiamata anche SSID)"
,"Modalità 802.11"
,"B/G misto"
,"Modalità N"
,"B/G/N misto"
,"Analisi automatica canale"
,"Canale wireless"
," GHz - CH "
,"Stato visibilità"
,"Visibile"
,"Invisibile"
,"Modalità protezione wireless"
,"Modalità protezione"
,"Nessuna"
,"WEP"
,"WPA-personale"
,"WPA-azienda"
,"WEP"
,"WEP è lo standard di crittografia wireless. Per utilizzarlo è necessario inserire le stesse chiavi nelle stazioni router e wireless. Per le chiavi a 64 bit, inserire 10 cifre esadecimali in ogni casella. Per le chiavi a 128 bit, inserire 26 cifre esadecimali in ogni casella. Una cifra esadecimale è un numero da 0 a 9 o una lettera da A a F. Per la massima protezione WEP impostare il tipo di autenticazione su &quot;Shared Key&quot; quando è abilitao il WEP."
,"Nella casella WEP è possibile inserire anche una stringa di testo, che verrà poi convertita in una chiave esadecimale con i valori ASCII delle lettere. Nelle chiavi a 64 bit possono essere inseriti 5 caratteri massimo, per quelle a 128 bit, massimo 13 caratteri."
,"Autenticazione"
,"Apri"
,"Condiviso"
,"Crittografia WEP"
,"64 Bit"
,"128 Bit"
,"Chiave WEP predefinita"
,"Chiave WEP 1"
,"Chiave WEP 2"
,"Chiave WEP 3"
,"Chiave WEP 4"
,"Chiave WEP"
,"HEX"
,"ASCII"
,"WPA"
,"Usare la modalità <B>WPA o WPA2</b> per ottenere un bilanciamento tra alta protezione e compatibilità ottimale. Questa modalità utilizza WPA per client legacy mantenendo un'elevata protezione nelle stazioni idonee a WPA2. Viene usata anche la cifratura massima supportata dal client. Per una maggiore protezione, usare la modalità <B>solo WPA2</B>. Questa modalità utilizza la cifratura AES(CCMP) e le stazioni legacy non possono accedere con la protezione WPA. Per la massima compatibilità, usare <B>solo WPA</B>. Questa modalità utilizza la cifratura TKIP. Alcuni dispositivi di gioco e legacy operano solo in questa modalità.<BR><BR>Per ottenere migliori prestazioni wireless, usare la modalità di protezione <B>Solo WPA2</b> (cioè la cifratura AES)."
,"Modalità WPA"
,"Solo WPA2"
,"Solo WPA"
,"Tipo di cifratura"
,"TKIP"
,"AES"
,"Chiave precondivisa"
,"Inserire una passphrase alfanumerica da 8 a 63 caratteri. Per una protezione ottimale deve essere sufficientemente lunga e non deve essere una frase conosciuta."
,"Chiave di rete"
,"(8~63 ASCII o 64 HEX)"
,"EAP (802.1x)"
,"Quando è abilitata la WPA aziendale, il router usa EAP (802.1x) per autenticare client tramite server RADIUS remoto."
,"Indirizzo IP server RADIUS"
,"Porta server RADIUS"
,"Segreto condiviso server RADIUS"
,"(13 ASCII o 26 HEX)"
,"(5 ASCII o 10 HEX)"
,"Le impostazioni diventano effettive dopo il riavvio."
,"Modificare?"
,"Impostazione Wi-Fi"
,"In questa sezione è possibile configurare l'interfaccia wireless (access point) disponibile sul router."
,"Banda 2.4GHz"
,"Banda 5GHz"
,"Banda wireless"
,"Abilita analisi automatica canale"
,"Larghezza canale"
,"20/40MHz (Auto)"
,"20/40/80MHz (Auto)"
,"Solo 802.11b"
,"Solo 802.11g"
,"Solo 802.11n"
,"Misto 802.11g e 802.11b"
,"Misto 802.11n e 802.11g"
,"Misto 802.11n, 802.11g e 802.11b"
,"Solo 802.11a"
,"Solo 802.11n"
,"Misto 802.11a e 802.11n"
,"Misto 802.11 a/n/ac"
,"la lunghezza si applica a tutte le chiavi"
,"Lunghezza chiave WEP"
,"Avvertenza! L'impostazione della modalità di sicurezza della banda 2.4 GHz su \"NESSUNA\" procurerà rischi per la sicurezza. Procedere con la configurazione?"
,"Per abilitare l'impostazione WEP per la banda 2.4 GHz è necessario interrompere la funzione WPS. Procedere con la configurazione?"
,"Avvertenza! L'impostazione della modalità di sicurezza della banda 5GHz su \"NESSUNA\" procurerà rischi per la sicurezza. Procedere con la configurazione?"
,"Per abilitare l'impostazione WEP per la banda 5GHz è necessario interrompere la funzione WPS. Procedere con la configurazione?"
,"64Bit (10 cifre esadecimali)"
,"128Bit (26 cifre esadecimali)"
,"Avvertenza! L'impostazione della modalità di sicurezza della banda 2.4 GHz su \"NESSUNA\" procurerà rischi per la sicurezza. Procedere con la configurazione?"
,"Avvertenza! L'impostazione della modalità di sicurezza della banda 5GHz su \"NESSUNA\" procurerà rischi per la sicurezza. Procedere con la configurazione?"
,"Per abilitare l'impostazione WEP per la banda 2.4 GHz è necessario interrompere la funzione WPS. Procedere con la configurazione?"
,"Per abilitare l'impostazione WEP per la banda 5GHz è necessario interrompere la funzione WPS. Procedere con la configurazione?"
,"Auto (WPA o WPA2)"
)

wps=new Array(
 "NON CONFIGURATA"
,"Imposta"
,"CONFIGURATA"
,"Versione"
,"NOUSED"
,"IDLE"
,"PROCESSFAIL"
,"STARTPROCESS"
,"RECVEAPOLSTART"
,"SENDEAPREQID"
,"RECVEAPRSPID"
,"RECVWRGVENDORID"
,"RECVWRGVENDORTYPE"
,"SENDEAPREQSTART"
,"SENDM1"
,"RECVM1"
,"SENDM2"
,"RECVM2"
,"RECVM2D"
,"SENDM3"
,"RECVM3"
,"SENDM4"
,"RECVM4"
,"SENDM5"
,"RECVM5"
,"SENDM6"
,"RECVM6"
,"SENDM7"
,"RECVM7"
,"SENDM8"
,"RECVM8"
,"PROCEAPRSPACK"
,"PROCEAPREQDONE"
,"PROCEAPRSPDONE"
,"SENDEAPFAIL"
,"ERRHASHFAIL"
,"ERRHMACFAIL"
,"ERRDEVPWDAUTHFAIL"
,"CONFIGURATA"
,"Impostazione Wi-Fi protetto"
,"WPS"
,"PIN AP"
,"Genera nuovo PIN"
,"Modalità configurazione"
,"Iscritto"
,"Registrazione"
,"Stato configurazione"
,"Metodo configurazione"
,"Codice PINCodice Pin"
,"Pulsante Push"
,"Stato WPS"
,"Attiva"
,"Lettura in corso..."
,"Impostazione Wi-Fi protetto (WPS)"
,"WPS è uno standard per impostare una connessione wireless in modo semplice e sicuro. In questa sezione è possibile abilitare WPS per una connessione client usando la protezione WPA/WPA2."
,"Lunghezza codice PIN = 4 o 8"
,"Errore regola codice PIN!"
,"Disabilita metodo WPS-PIN"
,"Lunghezza codice PIN = 4 o 8"
,"Errore regola codice PIN!"
)

wlpfe=new Array(
 "Impostazioni wireless avanzate"
,"Intervallo beacon"
,"(msec, intervallo:10~1024)"
,"Potenza trasmissione"
,"Soglia RTS"
,"(1~2347, predefinita 2347)"
,"Frammentazione"
,"(256~2346, predefinita 2346)"
,"Intervallo DTIM"
,"(intervallo: 1~255)"
,"Idoneo WMM"
,"Frequenze TX"
,"Specificare le impostazioni avanzate di configurazione per i gateway radio. La protezione AP e i parametri di associazione possono essere modificati rispetto ai valori predefiniti."
,"Impostazioni wireless 2.4G avanzate"
,"Impostazioni wireless 5G avanzate"
,"GI breve"
,"Coesistenza HT 20/40"
)

//---------------------------------LAN---------------------------------
devlist=new Array(
 "Elenco client LAN"
,"Nome host (se presente)"
,"Indirizzo IP"
,"Indirizzo MAC"
)

lanst=new Array(
 "Impostazioni router"
,"Usare questa sezione per configurare le impostazioni di rete interna del router. L'indirizzo IP configurato qui è quello utilizzato per accedere all'interfaccia di gestione su base web. Se si cambia l'indirizzo IP qui, si dovranno cambiare le impostazioni di rete del PC per accedere di nuovo alla rete."
,"Indirizzo IP router"
,"Subnet Mask predefinita"
,"Nome dominio locale"
,"Impostazioni server DHCP"
,"Utilizzare questa sezione per configurare il server DHCP integrato e assegnare l'indirizo IP ai computer nella rete."
,"Abilita server DHCP"
,"Intervallo indirizzo IP DHCP"
,"a"
,"(indirizzi all'interno della subnet LAN)"
,"Durata di lease DHCP"
,"Indirizzo IP DNS primario"
,"Indirizzo IP DNS secondario"
,"Indirizzo IP WINS primario"
,"Indirizzo IP WINS secondario"
,"L'impostazione dell'indirizzo IP LAN diventa effettiva dopo il riavvio."
,"Modificare?"
,"Intervallo pool IP non valido."
,"Indirizzo iniziale Pool IP"
,"Indirizzo finale Pool IP"
,"Nome dominio locale non valido."
,"Questa sezione consente di configurare le impostazioni di rete locale del router. La sezione è facoltativa e non è richiesta la modifica delle impostazioni per far funzionare la rete."
,"Configurazione interfaccia IP"
,"Server DHCP"
,"Configurazione server DHCP"
,"DHCP Reservation"
)

//---------------------------------Advanced---------------------------------
ddns=new Array(
 "DNS dinamico"
,"Abilita DDNS"
,"Provider"
,"DynDNS.org(Dinamico)"
,"DynDNS.org(Personalizzato)"
,"No-IP.com"
,"TZO.com"
,"dhs.org"
,"Nome host"
,"Nome utente / E-mail"
,"Password / Chiave"
,"La risoluzione dell'indirizzo IP a nome host/dominio e viceversa è gestita dal DNS. Le informazioni richieste (indirizzo IP di almeno un server DNS) normalmente è fornita dal proprio ISP. Comunque il dispositivo è in grado di rilevare i server DNS anche automaticamente."
)

spap=new Array(
 "Applicazioni più popolari"
,"-- Fai una selezione --"
,"Battle.net"
,"Dialpad"
,"ICU II"
,"MSN Gaming Zone"
,"PC-to-Phone"
,"Quick Time 4"
,"Regole applicazione"
,"Attiva"
,"Porte d'ingresso"
,"Applicazione"
,"La porta per il server virtuale e la porta in ingresso delle regole applicazioni non devono coincidere."
,"Il valore porta in ingresso non può essere uguale"
)

dmz=new Array(
 "Impostazioni firewall"
,"Abilita SPI"
,"Host DMZ"
,"L'opzione DMZ (zona demilitarizzata) consente di impostare un singolo computer sulla propria rete esterna al router. Se il computer non può eseguire applicazioni Internet da oltre il router, è possibile inserire il computer in DMZ per accesso a Internet limitato."
,"<b>Nota:</b> l'inserimento del computer in DMZ può esporlo a diversi rischi per la sicurezza. L'uso di quest'opzione è consigliato solo come ultima risorsa."
,"Abilita DMZ"
,"Indirizzo IP DMZ"
,"Nome del computer"
)

smap=new Array(
 "Servizi conosciuti"
,"-- Fai una selezione --"
,"AUTH (113)"
,"DNS (53)"
,"FTP (21)"
,"ISAKMP (500)"
,"POP3 (110)"
,"PPTP (1723)"
,"SMTP (25)"
,"TELNET (23)"
,"WEB (80)"
,"Usa regola di pianificazione"
,"---SEMPRE ON---"
,"Elenco server virtuali"
,"Porte servizio"
,"IP server: Porta"
,"Abilita"
,"Regola pianificazione N."
,"L'esterno agisce da server. Riceve le richieste degli utenti remoti nel suo indirizzo IP pubblico e le inoltra automaticamente al server virtuale. "
,"In questo modo un client nella rete dietro NAT o firewall può fornire servizi come un server virtuale. "
,"È sufficiente abilitare porte specifiche o intervalli di porta e protocolli (UDP/TCP). Sono possibili la condivisione file o i servizi web, come HTTP, FTP o POP3. Gli indirizzi IP privati dei server nella rete locali restano protetti. Se si ha un indirizzo IP dinamico, è possibile abilitare anche DynDNS."
,"Il valore porta di servizio non può essere uguale."
,"errore impostazione"
)

uctl=new Array(
 "Impostazioni filtro URL"
,"Filtro URL"
,"Abilita"
,"Regole filtro URL"
,"URL"
,"Abilita"
,"L'URL non può essere vuoto."
,"http://' non consentito."
,"Il filtro URL offre strumenti utili per limitare l'accesso a Internet. "
,"Il blocco URL sito web consente di creare rapidamente un elenco dei siti web per i quali si desidera consentire o rifiutare l'accesso."
,"Filtro URL"
)

rtab=new Array(
 "Impostazione RIP"
,"RIP"
,"Abilita"
,"RIPv1"
,"RIPv2"
,"Regole di routing"
,"Destinazione"
,"Subnet Mask"
,"Gateway"
,"Hop"
,"Gli instradamenti del traffico nella rete sono definiti nella tabella di routing. Normalmente sono sufficienti l'indirizzo IP e il Gateway. Non è necessario definire altre impostazioni."
)

qos=new Array(
 "Alto"
,"Normale"
,"Basso"
,"Impostazione motore QoS"
,"Abilita filtro pacchetto QoS"
,"Larghezza di banda upstream"
,"Larghezza di banda downstream"
,"kbps"
,"Usa regola di pianificazione"
,"---SEMPRE ON---"
,"Regole QoS"
,"IP locale: Porte"
,"IP remoto: Porte"
,"Priorità QoS"
,"Abilita"
,"Usa regola N."
,"Impostazione motore QoS"
)

pmac=new Array(
 "Impostazioni filtro MAC"
,"Controllo indirizzo MAC"
,"Abilita"
,"Controllo connessione"
,"I client cablati e wireless con spunta <b>C</b> possono connettersi a questo dispositivo, e "
,"consenti"
,"nega"
," connessione a indirizzi MAC non specificati."
,"Controllo associazione"
,"I client wireless con spunta <b>A</b> possono associarsi alla LAN wireless, e "
,"consenti"
,"nega"
," associazione a indirizzi MAC non specificati."
,"Client DHCP"
,"-- Fai una selezione --"
,"Regole filtro MAC"
,"Indirizzo MAC"
,"Indirizzo IP"
,"C"
,"A"
)

iopf=new Array(
 "Impostazione filtro di uscita"
,"Impostazione filtro d'ingresso"
,"Filtro di uscita"
,"Filtro d'ingresso"
,"Abilita"
,"Usa regola di pianificazione"
,"---SEMPRE ON---"
,"Elenco regole filtro di uscita"
,"Elenco regole filtro d'ingresso"
,"Consenti a tutti di passare tranne quelli corrispondenti alle seguenti regole."
,"Nega a tutti di passare tranne quelli corrispondenti alle seguenti regole."
,"IP sorgente: porte"
,"IP destinazione: porte"
,"Abilita"
,"Regola pianificazione N."
,"Usare l'errore numero regola!"
)

snmp=new Array(
 "SNMP"
,"SNMP Locale"
,"SNMP Remoto"
,"Ottieni comunità"
,"Imposta comunità"
,"IP 1"
,"IP 2"
,"IP 3"
,"IP 4"
,"Versione SNMP"
,"V1"
,"V2c"
,"Indirizzo IP server WAN"
)

fmisc=new Array(
 "UPNP"
,"Universal Plug and Play (UPnP) supporta la funzione Plug and Play peer-to-peer per i dispositivi di rete."
,"Abilita UPnP"
,"PING WAN"
,"Se si abilita questa funzione, la porta WAN del router risponderà alle richieste di ping da Internet inviate all'indirizzo IP WAN."
,"Abilita risposta ping della WAN"
)

networkscan=new Array(
 "Selezione provider di rete"
,"Questa pagina analizza i fornitori di rete nelle vicinanze. <br>Attendere il termine delle scansioni."
,"Metodo di selezione rete 3G/4G"
,"In avanzamento..."
,"Elenco dei provider di rete"
,"Nessun provider di rete"
,"Se non si sceglie un provider di rete, la modalità passa ad automatico"
,"Le modifiche sono state salvate. Il router deve essere riavviato per confermare le modifiche."
,"È possibile avviare adesso oppure continuare a apportare modifiche e riavviare più tardi."
,"Disponibile"
,"Corrente"
,"Vietato"
,"Analizza"
,"Network Selection Method"
)

//---------------------------------System---------------------------------
sntp=new Array(
 "Configurazione data e ora"
,"Ora"
,"Fuso orario"
,"Abilita ora legale"
,"Sincronizza le impostazioni dell'ora del computer"
,"Configurazione automatica data e ora"
,"Sincronizza automaticamente con server ora Internet"
,"Server NTP utilizzato"
,"Aggiorna adesso"
,"Sincronizza RISULTATO"
,"Avvio"
,"Fine"
,"Ora"
,"Giorno"
,"Mese"
,"(Ora/Giorno/Mese)"
,"Gen"
,"Feb"
,"Mar"
,"Apr"
,"Mag"
,"Giu"
,"Lug"
,"Ago"
,"Set"
,"Ott"
,"Nov"
,"Dic"
,"Dom"
,"Lun"
,"Mar"
,"Mer"
,"Gio"
,"Ven"
,"Sab"
,"L'opzione di configurazione dell'ora consente di impostare, aggiornare e conservare l'ora corretta dell'orologio interno di sistema."
,"Da questa sezione è possibile impostare il proprio fuso orario e il server NTP (Network Time Protocol)."
,"L'ora legale può essere configurata per regolare automaticamente l'ora."
,"Ora"
,"Impostazioni orario"
)

tz=new Array(
 "* Non ancora configurato. L'ora predefinita è GMT+00:00"
,"Linea cambiamento data internazionale (occidentale)"
,"Midway Island, Samoa"
,"Hawaii"
,"Alaska"
,"Ora costa pacifica (USA e Canada)"
,"Tijuana"
,"Arizona"
,"Chihuahua, La Paz, Mazatlan"
,"Fuso occidentale (USA e Canada)"
,"America Centrale"
,"Fuso centrale (USA e Canada)"
,"Guadalajara, Messico, Monterrey"
,"Saskatchewan"
,"Bogota, Lima, Quito"
,"Fuso orientale (USA e Canada)"
,"Indiana (Est)"
,"Ora costa atlantica (USA e Canada)"
,"Caracas, La Paz"
,"Santiago"
,"Terranova"
,"Brasilia"
,"Buenos Aires, Georgetown"
,"Groenlandia"
,"Medio-Atlantico"
,"Azzorre"
,"Isola di Capo Verde"
,"Casablanca, Monrovia"
,"Dublino, Edimburgo, Lisbona, Londra"
,"Amsterdam, Berlino, Berna, Roma, Stoccolma, Vienna"
,"Belgrado, Bratislava, Budapest, Ljubljana, Praga"
,"Bruxelles, Copenaghen, Madrid, Parigi"
,"Sarajevo, Skopje, Varsavia, Zagabria"
,"Africa centro-occidentale"
,"Atene, Beirut, Istanbul, Minsk"
,"Bucarest"
,"Cairo"
,"Harare, Pretoria"
,"Helsinki, Kiev, Riga, Sofia, Tallinn, Vilnius"
,"Gerusalemme (solo 2007)"
,"Baghdad"
,"Kuwait, Riyad"
,"Mosca, San Pietroburgo, Volgograd"
,"Nairobi"
,"Teheran"
,"Abu Dhabi, Muscat"
,"Baku"
,"Tbilisi"
,"Yerevan"
,"Kabul"
,"Ekaterinburg"
,"Islamabad, Karachi, Tashkent"
,"Chennai, Kolkata, Mumbai, Nuova Delhi"
,"Kathmandu"
,"Almaty, Novosibirsk"
,"Astana, Dhaka"
,"Colombo"
,"Rangoon"
,"Bangkok, Hanoi, Giacarta"
,"Krasnoyarsk"
,"Beijing, Chongqing, Hong Kong, Urumqi"
,"Irkutsk"
,"Kuala Lumpur, Singapore"
,"Perth, Australia occidentale"
,"Taipei"
,"Ulaan Bataar"
,"Osaka, Sapporo, Tokio"
,"Seul"
,"Yakutsk"
,"Adelaide"
,"Darwin"
,"Brisbane"
,"Canberra, Melbourne, Sidney"
,"Guam, Port Moresby"
,"Hobart"
,"Vladivostok"
,"Magadan, Isole Salomone, Nuova Caledonia"
,"Auckland, Wellington"
,"Fiji, Kamchatka, Isole Marshall"
,"Nuku'alofa"
,"* Configurare la variabile TZ manualmente..."
,"Eniwetok, Kwajalein"
,"Città del Messico, Tegucigalpa"
,"Bruxelles, Copenaghen, Madrid, Parigi, Vilnius"
,"Sarajevo, Skopje, Sofia, Varsavia, Zagabria"
,"Atene, Beirut, Cairo, Istanbul, Minsk"
,"Beijing, Hong Kong, Taipei"
,"India"
)

atbox=new Array(
 "Amministratore (Il nome di accesso predefinito è "
,")"
,"Nome di accesso"
,"Nuova password"
,"Conferma password"
,"Gestione remota"
,"Abilita gestione remota"
,"IP consentito per l'accesso"
,"Porta"
,"Le nuove password amministratore non coincidono."
,"Salvare la password nella password vuota?"
,"La porta di gestione remota deve essere maggiore di 1024."
,"Amministratore"
,"Qui è possibile cambiare la password amministratore."
,"Il nome utente (amministratore) non può essere modificato."
,"Impostazioni amministratore"
,"SSH"
,"Abilita SSH"
,"Consenti WAN"
,"Telnet"
,"Abilita Telnet"
,"Remote Administration"
)

rebo=new Array(
 "Aggiornamento riuscito."
,"File di aggiornamento non valido."
,"Verificare di avere il file corretto."
,"Il file non è compatibile con il firmware o hardware corrente."
,"L'aggiornamento di questa versione non è consentito."
,"Il processo di aggiornamento è stato annullato per motivi sconosciuti."
,"Riprovare."
,"Tutte le impostazioni sono state reimpostate."
,"Riavvio del dispositivo in corso..."
,"<font color=red><b>NON SPEGNERE</b></font> il dispositivo."
,"Attendere "
," secondi..."
,"Riconnettere manualmente."
,"Nota. L'IP LAN potrebbe essere cambiato, riconnettersi."
,"Fare clic qui per riconnettersi"
,"Il sistema è pronto"
,"Riavvia router"
,"Messaggio di stato"
,"Il router sarà attivo tra"
,"Riavvia adesso"
,"Riavvia più tradi"
)

system=new Array(
 "Reimpostare le impostazioni predefinite?"
,"Salva e ripristina impostazioni"
,"Salva impostazioni su disco rigido locale"
,"Salva"
,"Carica impostazioni dal disco rigido locale"
,"Impostazioni caricamento"
,"Ripristina impostazioni predefinite di fabbrica"
,"Remposta predefinite"
,"File di aggiornamento non valido."
,"Aggiornamento file non consentito."
,"Sistema"
,"Tutte le impostazioni verranno salvate automaticamente sul dispositivo. Non è necessario salvare manualmente o riavviare. Se si desidera comunque riavviare il dispositivo, utilizzare il pulsante \"Riavvia\"."
,"Impostazioni di sistema"
,"Riavvia dispositivo"
,"Reimpostare tutte le impostazioni di fabbrica?"
,"Riavvia"
,"Riavvia e Reimposta"
)

fwug=new Array(
 "Informazioni firmware"
,"Versione firmware corrente"
,"Data firmware corrente"
,"Aggiornamento firmware"
,"Nota. Non spegnere l'unità durante l'aggiornamento."
,"La procedura di aggiornamento dura circa 180 secondi."
,"Al termine dell'aggiornamento, l'unità si riavvia automaticamente."
,"Per aggiornare il firmware, il PC deve essere cablato al router. Inserire il nome del file di aggiornamento firmware e fare clic sul pulsante Carica."
,"Carica"
,"Aggiorna"
,"Nome file errato"
,"Sono accettati solo i file .bin."
,"Annulla"
,"È in corso un altro aggiornamento firmware."
,"Accetta firmware non ufficiale."
,"Usare il pulsante \"Aggiorna\" per aggiornare la versione firmware del dispositivo."
,"Aggiornamento firmware"
,"Seleziona firmware"
,"controllare File"
,"Nuove informazioni Firmware"
,"Nuova versione del firmware"
,"Nuovo Data Firmware"
)

logs=new Array(
 "Impostazioni SysLog"
,"Abilita accesso al server Syslog"
,"Indirizzo IP server SysLog"
,"Impostazioni e-mail"
,"Abilita notifiche e-mail"
,"Porta e Ip server SMTP"
,"Invia avviso e-mail a"
,"Oggetto e-mail"
,"Nome utente SMTP"
,"Password SMTP"
,"Accedi a e-mail adesso"
,"Un'e-mail è in coda per l'invio..."
,"Log di sistema"
,"Il Log di sistema consente di configurare l'accesso e-mail, locale e remoto e di visualizzare i log creati."
,"Clear logs"
,"Log Number"
,"Message"
,"View Logs"
)

smsmsg=new Array(
 "Rispondi a messaggio"
,"Inoltra messaggio"
,"Crea messaggio"
,"Testo messaggio"
,"Inserisci messaggio..."
,"La lunghezza massima del messaggio è 160 caratteri."
,"Ricevitore"
,"Aggiungi '+' per numero di telefono in formato internazionale."
,"Invia"
,"Lettura in corso... Attendere un attimo..."
,"Lunghezza testo corrente inserito"
,"Invio messaggio"
,"Se si desidera creare e inviare messaggi SMS, fare clic sul pulsante sotto."
,"Il destinatario non può essere vuoto."
,"The max. length of a message is 160 characters for pure alphabetical or numeric."
)

smsinbox=new Array(
 "Stato SMS"
,"SMS ricevuti"
,"Nuovo SMS"
,"Capacità totale"
,"Posta in arrivo"
,"Da"
,"Data e ora"
,"Testo"
,"SMS"
,"Lettura in corso... Attendere un attimo..."
,"Rispondi"
,"Inoltra"
,"Posta in arrivo SMS"
,"Se si desidera visualizzare i messaggi SMS, fare clic sul pulsante sotto."
,"Impostazione SMSC"
,"Verificare se la scheda SIM è inserita."
,"Scheda SIM bloccata. Impossibile leggere SMS da scheda SIM."
,"Modem non pronto."
,"Modem impegnato dalla chiamata telefonica. Attendere..."
,"Invio riuscito."
,"Invio non riuscito."
,"Il modem è occupato da una chiamata telefonica. L'SMS verrà inviato automaticamente più tardi."
,"Eliminazione riuscita."
,"Eliminazione non riuscita."
,"Comando AT non riuscito."
,"Il modem è occupato da una chiamata telefonica. L'SMS verrà eliminato automaticamente più tardi."
)

voiceforwd=new Array(
 "Tutte le chiamate"
,"Nessuna risposta"
,"Irraggiungibile"
,"Occupato"
,"Stato"
,"Annulla registrazione"
,"Registra"
,"Attiva"
,"Disattiva"
,"Numero"
)

pinco=new Array(
 "Stato query... Attendere un attimo..."
,"Codice PIN SIM"
,"Inserire 4~8 cifre nel campo codice PIN SIM."
,"Funzione di richiesta del CODICE PIN"
,"Inserimento codice PIN SIM"
,"Cambio codice PIN in corso..."
,"Riuscito."
,"Inserire 4~8 cifre nel campo del vecchio codice PIN."
,"Inserire 4~8 cifre nel campo del nuovo codice PIN."
,"Inserire 4~8 cifre nel campo verifica codice PIN."
,"Funzione di modifica del CODICE PIN"
,"Vecchio codice PIN"
,"Nuovo codice PIN"
,"Verifica codice PIN"
,"Salva"
,"Inserire il codice PIN per sbloccare la scheda SIM"
,"CODICE PIN"
,"Inserire il codice PUK per sbloccare la scheda SIM"
,"CODICE PUK"
,"Nuovo CODICE PIN"
,"La funzione è già disabilitata."
,"La funzione è già abilitata."
,"Codice PIN errato."
,"Prima occorre abilitare la funzione di richiesta del codice PIN."
,"Sono stati inseriti due tipi di codici PIN."
,"Vecchio codice PIN errato."
,"Codice PUK errato."
,"Comando AT non riuscito."
,"Pronto"
,"Bloccato da PIN SIM"
,"Bloccato da PUK SIM"
,"Scheda SIM con errori."
,"Il modem non ottiene risposta."
,"Invio comando AT non riuscito."
,"Il modem non esiste. Verificare che scheda SIM sia inserita."
,"Avvertenza: ancora 3 tentativi a disposizione."
,"Riprova"
,"Continua"
,"Avvertenza: "
," ancora 3 tentativi a disposizione."
,"Inserire 4~8 cifre nel campo CODICE PIN."
,"Inserire 8 cifre nel campo CODICE PUK."
,"Controllo PIN"
,"Modem in inizializzazione, attendere."
,"Configurazione PIN"
,"Inserire il codice PIN per 3 volte fallire! Inserire codice PUK."
)

ussd=new Array(
 "USSD"
,"Invia"
,"ERRORE"
)

scherebo=new Array(
 "Reimposta connessione"
,"Riavvio automatico"
,"Pianificazione riavvio"
,"Pianificazione diario"
,"Pianificazione settimanale per giorno"
,"Data del mese"
)

sche=new Array(
 "Regola pianificazione"
,"Abilita pianificazione"
,"Regola N."
,"Nome regola"
,"Azione"
,"Nessuna regola aggiunta. Aggiungere regole prima di abilitare."
,"Eliminare regola "
,"?"
,"Pianificazione"
)

rule=new Array(
 "Il nome regola non può essere vuoto."
,"Il nome pianificato è duplicato in un'altra regola."
,"(Regola:"
,")"
,"Controllare di nuovo."
,"Ora di avvio del giorno della settimana "
," non valida."
,"Ora di fine del giorno della settimana "
," non valida."
,"Ora del giorno della settimana "
," non valida."
,"L'ora di fine deve essere maggiore di quella di avvio"
,"(Il formato dell'ora pianificata deve essere hh:mm)"
,"(0 < l'ora di avvio < 23 )"
,"(0 < i minuti dell'ora di avvio < 59 )"
,"(0 < l'ora di fine < 23 )"
,"(0 < i minuti dell'ora di fine < 59 )"
,"Selezionare il giorno della settimana nell'ID regola "
,"."
,"L'ora nella regola pianificazione è vuota."
," Inserire almeno una pianificazione."
,"Ogni giorno"
,"Domenica"
,"Lunedì"
,"Martedì"
,"Mercoledì"
,"Giovedì"
,"Venerdì"
,"Sabato"
,"Impostazione regola pianificazione"
,"Nome della regola"
,"-- seleziona una voce --"
,"Criterio"
,"Indietro"
,"Inattiva"
,"Attiva"
,"eccetto i giorni e le ore selezionate sotto."
,"Giorno della settimana"
,"Ora di avvio (hh:mm)"
,"Ora di fine (hh:mm)"
)

diagnostic=new Array(
 "Informazioni sul servizio"
,"Operatore"
,"Trasmissione di cella"
,"MCC"
,"MNC"
,"LAC"
,"Tipo di servizio"
,"Modalità scelta servizio"
,"Solo GSM"
,"Solo WCDMA"
,"Sconosciuto"
,"PS attach(DATI)"
,"PS attach(VOCE)"
,"IMSI"
,"SMSC"
,"Collegato"
,"Scollegato"
,"Stato SIM"
,"Blocco codice PIN"
,"Numero tentativi Codice PIN"
,"Numero tentativi Codice PUK"
,"Stato del modulo"
,"IMEI"
,"Versione FW"
,"Nome del modulo"
,"ID cella"
)

voice=new Array(
 "Voce"
,"Inoltro chiamata"
,"Inoltro automatico delle chiamate in entrata a un numero assegnato in condizioni differenti."
,"Chiamata in attesa"
,"Sospendere la chiamata corrente e rispondere alla nuova chiamata in ingresso."
,"Vai a Inoltro chiamata"
,"Vai a Chiamata in attesa"
)

sms=new Array(
 "Crea messaggio"
,"Consente di creare e inviare nuovi messaggi SMS."
,"Posta in arrivo"
,"Consente di leggere i nuovi messaggi e eliminare/inoltrare i messaggi esistenti."
,"Rispondere a un messaggio per volta!"
)

tr069=new Array(
 "TR-069"
,"TR-069 Setting"
,"ACS Setting"
,"ACS URL"
,"ACS UserName"
,"ACS Password"
,"CPE Setting"
,"ConnectionRequest Port"
,"ConnectionRequest UserName"
,"ConnectionRequest Password"
,"Inform Setting"
,"Inform"
,"Interval"
,"Interface"
)
