#!/bin/sh
case "$1" in
save)
	/etc/scripts/dbsave.sh
	;;
freset)
	devconf del
	;;
isfreset)
	SIZE=`devconf dump | scut -p "Data size :" -f 1`
	if [ "$SIZE" = "0" ]; then
		echo "YES"
	else
		echo "NO"
	fi
	;;
init)
	if [ $# -ne 9 ]; then
		echo "Usage:"
		echo "  mfc init <lanmac> <wlan24mac> <wlan5mac> <wanmac> <countrycode> <hw version> <pin> <wifipassword>"
		exit 1
	fi
	
	LANMAC=`echo -e $2 | tr [A-Z] [a-z]`
	WLAN24MAC=`echo -e $3 | tr [A-Z] [a-z]`
	WLAN5MAC=`echo -e $4 | tr [A-Z] [a-z]`
	WANMAC=`echo -e $5 | tr [A-Z] [a-z]`
	CCODE="$6"
	HWVER="$7"
# siyou, now do not write ip to bootcode config.
#	IP="$8"
	PIN="$8"
	WIFIPWD="$9"
	[ "$LANMAC" != "" ] && DEVDATA="$DEVDATA -e lanmac=$LANMAC -e wlan24mac=$WLAN24MAC -e wlan5mac=$WLAN5MAC"
	[ "$WANMAC" != "" ] && DEVDATA="$DEVDATA -e wanmac=$WANMAC"
	[ "$CCODE" = "" ] && CCODE="US"
	[ "$HWVER" != "" ] && DEVDATA="$DEVDATA -e hwver=$HWVER"
	[ "$PIN" != "" ] && DEVDATA="$DEVDATA -e pin=$PIN"
	[ "$WIFIPWD" != "" ] && DEVDATA="$DEVDATA -e psk=$WIFIPWD"
	echo "clean devdata"
	devdata clean
	echo "devdata set -e countrycode=$CCODE $DEVDATA -f" > /dev/console
	devdata set -e countrycode=$CCODE $DEVDATA -f

	# Set MAC Address and IP Address into u-boot config.
	#[ "$LANMAC" != "" ] && UBCFG="$UBCFG ethaddr=$LANMAC"
	#[ "$IP" != "" ] && UBCFG="$UBCFG ipaddr=$IP"
	#echo "ubcfg set $UBCFG" > /dev/console
	#ubcfg set $UBCFG
	# Show devdata and uboot data
	echo "-------- devdata dump ----------------------" > /var/mfcdump
	devdata dump >> /var/mfcdump
	#echo "-------- ubcfg get ethaddr ipaddr-----------" >> /var/mfcdump
	#ubcfg get ethaddr ipaddr >> /var/mfcdump
	#echo "--------------------------------------------" >> /var/mfcdump
	cat /var/mfcdump
	rm /var/mfcdump
	;;
evm)
	if [ $# -ne 11 ]; then
		echo "Usage:"
		echo "  mfc evm <INF> <ATETXFREQOFFSET> <ATETXMODE> <ATETXMCS> <ATETXBW> <ATETXLEN> <ATECHANNEL> <ATETXANT> <ATETXPOW0> <ATETXPOW1>"
		exit 1
	fi
	INF=$2

	iwpriv $INF set ATE=ATESTART
	iwpriv $INF set ATEDA=FF:FF:FF:FF:FF:FF
	iwpriv $INF set ATETXGI=0
	iwpriv $INF set ATETXLEN=$7
	iwpriv $INF set ATETXCNT=1000000
	iwpriv $INF set ATETXANT=$9
	iwpriv $INF set ATECHANNEL=$8
	iwpriv $INF set ATETXMODE=$4
	iwpriv $INF set ATETXMCS=$5
	iwpriv $INF set ATETXBW=$6
	iwpriv $INF set ATETXPOW0=${10}
	iwpriv $INF set ATETXPOW1=${11}
	iwpriv $INF set ATETXFREQOFFSET=$3
	iwpriv $INF set ATEIPG=200	
	iwpriv $INF set ATE=TXFRAME
	;;
wlan5)
	DATPATH="/var/run/RT3572.dat"
	cp /etc/scripts/mfc/RT3572.dat $DATPATH
	MACADDR=`xmldbc -g /runtime/devdata/wlanmac2`
	echo "" >> $DATPATH
	[ "$MACADDR" != "" ] && echo "MacAddress=$MACADDR" >> $DATPATH
	echo "" >> $DATPATH
	case "$4" in
	"HT20")
		echo "HT_BW=0" >> $DATPATH
		;;
	"HT40")
		echo "HT_BW=1" >> $DATPATH
		echo "HT_EXTCHA=1" >> $DATPATH
		;;
	esac
	echo "Channel=$3" >> $DATPATH
	echo "SSID=$2" >> $DATPATH
	killall hostapd
	ifconfig wifia0 down
	ifconfig wifia0.1 down
	brctl delif br0 wifia0
	rmmod rt5592ap
	insmod /lib/modules/rt5592ap.ko
	ifconfig wifia0 txqueuelen 1000
	ifconfig wifia0 up
	brctl addif br0 wifia0
	brctl setbwctrl br0 wifia0 900
	echo 1 > /proc/sys/net/ipv4/conf/br0/forwarding
	;;
wlan24)
	DATPATH="/var/run/RT2860.dat"
	cp /etc/scripts/mfc/RT3352.dat $DATPATH
	MACADDR=`xmldbc -g /runtime/devdata/wlanmac`
	echo "" >> $DATPATH
	[ "$MACADDR" != "" ] && echo "MacAddress=$MACADDR" >> $DATPATH
	echo "" >> $DATPATH
	case "$4" in
	"HT20")
		echo "HT_BW=0" >> $DATPATH
		;;
	"HT40")
		echo "HT_BSSCoexistence=0" >> $DATPATH
		echo "HT_BW=1" >> $DATPATH
		echo "HT_EXTCHA=1" >> $DATPATH
		;;
	esac
	echo "Channel=$3" >> $DATPATH
	echo "SSID=$2" >> $DATPATH
	killall hostapd
	ifconfig wifig0 down
	ifconfig wifig0.1 down
	brctl delif br0 wifig0
	rmmod rt5592ap
	insmod /lib/modules/rt5592ap.ko
	ifconfig wifig0 up
	brctl addif br0 wifig0
	brctl setbwctrl br0 wifig0 900
	echo 1 > /proc/sys/net/ipv4/conf/br0/forwarding
	;;
dump)
	devdata dump
	;;
dumpv2)
	# Show devdata and uboot data
	echo "-------- Firmware Version-------------------" > /var/mfcdump
	echo FW_Ver=`cat /etc/config/buildver``cat /etc/config/buildrev` Build `cat /etc/config/buildno` >> /var/mfcdump
	echo "-------- devdata dump ----------------------" >> /var/mfcdump
	devdata dump >> /var/mfcdump
	echo "-------- ubcfg get ethaddr ipaddr-----------" >> /var/mfcdump
	ubcfg get ethaddr ipaddr >> /var/mfcdump
	echo "--------------------------------------------" >> /var/mfcdump
	cat /var/mfcdump
	rm /var/mfcdump
	;;
ver)
	echo Ver `cat /etc/config/buildver``cat /etc/config/buildrev` Build `cat /etc/config/buildno`
	;;
get)
	[ "$2" != "" ] && devdata get -e $2
	;;
set)
	[ "$2" != "" ] && devdata set -e $2
	;;
test)
	case $2 in
	on)
		usockc /var/gpio_ctrl DEBUG
		;;
	off)
		usockc /var/gpio_ctrl NODEBUG
		;;
	esac
	;; 
button)
	case $2 in
	reset)
		usockc /var/gpio_ctrl GPIO_FRESET
		cat /var/gpio_ctrl_result
		;;
	wps)
		usockc /var/gpio_ctrl GPIO_WPSPBC
		cat /var/gpio_ctrl_result
		;;
	esac
	;;
led)
	case "$2" in
	wps_blue)
		usockc /var/gpio_ctrl WPS_BLUE
		;;
	wan_green)
		usockc /var/gpio_ctrl INET_GREEN_ON
		;;
	wan_orange)
		usockc /var/gpio_ctrl INET_ORANGE_ON
		;;
	status_green)
		usockc /var/gpio_ctrl STATUS_GREEN
		;;
	status_orange)
		usockc /var/gpio_ctrl STATUS_AMBER
		;;
	esac
	;;
usb)
        USBSTOR=`cat /proc/bus/usb/devices  | grep Driver=usb-storage`
        if [ "$USBSTOR" != "" ]; then
                echo "Yes"
        else
                echo "NO"
        fi
        ;;
*)
	echo "Usage: mfc {command} <params>"
	echo "Commands:"
	echo "  init <lanmac> <wlan24mac(must Even)> <wlan5mac(must Even)> <wanmac> <countrycode> <hw version> <pin> <wifipassword>"
	echo "                           Init flash"
	echo "                           *bootip: Set boot loader IP not device IP."
	echo ""
	echo "  save                     Save current setting to flash"
	echo ""
	echo "  evm <INF> <ATETXFREQOFFSET> <ATETXMODE> <ATETXMCS> <ATETXBW> <ATETXLEN>"
	echo "       <ATECHANNEL> <ATETXANT> <ATETXPOW0> <ATETXPOW1>"
	echo "                           save ATE wireless parameters for 5GHz or 2.4GHz band"
	echo ""
	echo "  wlan5  <ssid> <channel> <bandwidth>"
	echo "  wlan24 <ssid> <channel> <bandwidth>"
	echo "                           Config the wireless setting for testing."
	echo "                           Where the 'bandwidth' should be the value of 'HT20' or 'HT40'."
	echo "  dump                     Dump environment vairables."
	echo "  dumpv2                   Dump environment vairables."
	echo "  ver                      Show firmware version"
	echo ""
	echo "  get <name>               Get current WAN mac address"
	echo "  freset                   Factory reset"
	echo "  isfreset                 Check if the device is reset to factory default."
	echo ""
	echo "  test on                  turn on test mode"
	echo "  test off                 turn off test mode"
	echo ""
	echo "  button {reset|wps}"
	echo "      reset                Get factory reset button status."
	echo "      wps                  Get WPS button status."
	echo ""
	echo "  led { wps_blue | wan_green | wan_orange | status_green | status_orange }"
	echo "      wps_blue             Set the WPS Led to blue  "
	echo "      wan_green            Set the WAN Led to green "
	echo "      wan_orange           Set the WAN Led to orange"
	echo "      status_green         Set the status Led to green"
	echo "      status_orange        Set the status Led to orange"
	;;
esac
